### ISSUE TITLE
not display HTML data using API

### ISSUE THREAD

**Issue by sanjaypraja** [chymz/ng2-ckeditor#103]
Hi,
I have tried to implement HTML editor in my project everything is working fine but when i tried to bind data from database using API, HTML editor does not display data in editor. if tried to bind data with class property then it works. Please look it.

**Comment by kzimny** [comment]
How the ckeditor is configured? Can you post your code?

**Comment by sanjaypraja** [comment]
Binding in *.html file
<ckeditor [(ngModel)]="componentDetails.componentData" name="componentDetails.componentData" debounce="500" [config]="{uiColor: '#99000'}">
</ckeditor>

in *.ts file, we call api request in ngOnInit() get the data and bind into "componentDetails" object

this.sub = this.route.params.subscribe(params => {
            let id = params['id'];
            this.service.getComponentDetails(id)
                 .subscribe(
                       body => {
                        this.componentDetails = <ComponentEditDetails>body.data;                          
                    },
                    error => this.handleError
                 )
        })

I have done few R&D and find that data bind **ng-reflect-model** in ckeditor but not bind in editor html body.
![image](https://cloud.githubusercontent.com/assets/2256488/25114207/8ac143f8-241a-11e7-8084-5e4e99bb3c82.png)

**Comment by kzimny** [comment]
Appropriated to your html code, the date should be loaded in iframe. Maybe something is set wrong in the config.js file? Can you try to load the ckeditor from CDN repository, just for a test? Load the ckeditor from CDN as follow:
`<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>`

**Comment by sanjaypraja** [comment]
tried with new CDN path but not success :( . I think problem with delay in data binding bcz when i tried with class property with hard code value, it's binding.

**Comment by kzimny** [comment]
try to load data without promise method. look at this [thread](https://github.com/chymz/ng2-ckeditor/issues/91)

**Comment by sanjaypraja** [comment]
we are not using promise method. I tried to debug script and find that sometime CKEditorComponent is calling ( then data bind) and sometime it is not calling (then data not bind).

**Comment by sanjaypraja** [comment]
problem has been resolved.  In [thread](https://github.com/chymz/ng2-ckeditor/issues/23) to use [config]="{extraPlugins: 'divarea'}".
