### ISSUE TITLE
Cannot read property 'isInline' of null when using with ckeditor 4.6.2

### ISSUE THREAD

**Issue by naveedahmed1** [chymz/ng2-ckeditor#104]
When using it with Ckeditor 4.6.2, I receive below error on component destroy.

```
errors.ts:42 ERROR TypeError: Cannot read property 'isInline' of null
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.focusManager.f (ckeditor.js:224)
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.focusManager.<anonymous> (ckeditor.js:225)
    at ckeditor.js:26
    at ZoneDelegate.invokeTask (zone.js:398)
    at Object.onInvokeTask (ng_zone.ts:253)
    at ZoneDelegate.invokeTask (zone.js:397)
    at Zone.runTask (zone.js:165)
    at ZoneTask.invoke (zone.js:460)
    at timer (zone.js:1540)
```

**Comment by kzimny** [comment]
How are you showing the ckeditor on the page? In a pop-up window? It seems that the ckeditor instance is not exist anymore. Can you check whether the instance exist:

`if(this.ckeditor.instance)`

**Comment by waiwaiku** [comment]
similar issue +1

**Comment by kzimny** [comment]
Software development is not magic. In most cases it is very difficulty to give an advice without source code. Please provide an example how your angular class component work. Please don't ask a question with "similar issue" anymore...

**Comment by waiwaiku** [comment]
// one solution
let time = 1000; // or time > 1000
ngOnDestroy() {
    if (this.instance) {
      setTimeout(() => {
        this.instance.removeAllListeners();
        this.instance.destroy();
        this.instance = null;
      }, time); // set the time
    }
  }

**Comment by naveedahmed1** [comment]
**In my index.html file I have**

<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.6.2/ckeditor.js" async></script>

**In my Module**
```
import { CKEditorModule } from 'ng2-ckeditor';

@NgModule({
    imports: [CKEditorModule
....
]})
export class MyAppModule { }
```

**In my component**
```
public ckConfig ={
            uiColor: '#f6f7f8',
            toolbarGroups: [
                { name: 'basicstyles', groups: ['basicstyles', 'cleanup'] },
                { name: 'paragraph', groups: ['list'] },
                { name: 'clipboard', groups: ['undo'] }
            ],
            removeButtons: 'Anchor,Outdent,Indent,Strike,Superscript,Subscript,PasteText,Cut,Copy,Paste,Scayt,PasteFromWord,SelectAll',
            forcePasteAsPlainText: true,
            extraPlugins: 'divarea',
            removePlugins: 'elementspath,resize',
            height: 250
        }
```

**In my template**

`<ckeditor formControlName="description" debounce="500" [config]="ckConfig" placeHolder="Description"></ckeditor>`

**Comment by kzimny** [comment]
Why are you using third party ckeditor CDN library? Please try the following and it will work.
**For ckeditor 4.5:**
`<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>`
in your component:
`public ckConfig ={ uiColor: '#f6f7f8', extraPlugins: 'divarea' }`
**For ckeditor 4.6:**
`<script src="//cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>`
in your component:
`public ckConfig ={ uiColor: '#f6f7f8'}`

**Comment by waiwaiku** [comment]
I have a better idea ：
```
ngOnDestroy() {
if (this.instance) {
    this.instance.focusManager.blur(true);  // add the action
    this.instance.removeAllListeners();
    this.instance.destroy();
    this.instance = null;
}
```

Hope to update @kzimny.

**Comment by YuriFontella** [comment]
With that same error:
<script src="https://cdn.ckeditor.com/4.6.2/full/ckeditor.js"></script>

No errors:
<script src="https://cdn.ckeditor.com/4.6.1/full/ckeditor.js"></script>

**Comment by kzimny** [comment]
Please look at the following [bug description](https://dev.ckeditor.com/ticket/16809). There is no solution for version 4.6.2 at the moment, use version 4.6.1 or 4.5.11 with divarea plugin instead. The proposed solution from @waiwaiku doesn't work for me.
