### ISSUE TITLE
when blurring "source toolbar " edit area,CKEDITOR.focusManager errors happend

### ISSUE THREAD

**Issue by keryhu** [chymz/ng2-ckeditor#105]
Hi,
 I use  "ng2-ckeditor": "^1.1.6",and "@angular/cli": "1.0.0",

and
    
`public ckeditorConfigJson = {uiColor: '#666666'};`

         <ckeditor
          formControlName="ckContent"
          [config]="ckeditorConfigJson"
          debounce="500">
        </ckeditor>

  

 

> When I click on the source button, enter the source mode, once the mouse left the edit area, this error occurs

```
zone.js:169 Uncaught TypeError: Cannot read property '$' of undefined
    at CKEDITOR.focusManager.d (ckeditor.js:238)
    at CKEDITOR.focusManager.<anonymous> (ckeditor.js:238)
    at ckeditor.js:28
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at ZoneTask.invoke (zone.js:460)
    at timer (zone.js:1540)
d @ ckeditor.js:238
(anonymous) @ ckeditor.js:238
(anonymous) @ ckeditor.js:28
ZoneDelegate.invokeTask @ zone.js:398
Zone.runTask @ zone.js:165
ZoneTask.invoke @ zone.js:460
timer @ zone.js:1540
zone.js:169 Uncaught TypeError: Cannot read property '$' of undefined
    at CKEDITOR.focusManager.d (ckeditor.js:238)
    at CKEDITOR.focusManager.<anonymous> (ckeditor.js:238)
    at ckeditor.js:28
    at ZoneDelegate.invokeTask (zone.js:398)
    at Zone.runTask (zone.js:165)
    at ZoneTask.invoke (zone.js:460)
    at timer (zone.js:1540)
d @ ckeditor.js:238
(anonymous) @ ckeditor.js:238
(anonymous) @ ckeditor.js:28
ZoneDelegate.invokeTask @ zone.js:398
Zone.runTask @ zone.js:165
ZoneTask.invoke @ zone.js:460
timer @ zone.js:1540
```

**Comment by kzimny** [comment]
Can you try with the following setting `[config]="{extraPlugins: 'divarea'}"`. Is the editor still open when you get the error message?

**Comment by keryhu** [comment]
now this error 

```
plugin.js Failed to load resource: the server responded with a status of 404 (Not Found)
vendor.bundle.js:1295 ERROR Error: [CKEDITOR.resourceManager.load] Resource name "divarea" was not found at "http://localhost:4200/assets/ckeditor/plugins/divarea/plugin.js?t=H0CG".
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:249) [angular]
    at f (ckeditor.js:244) [angular]
    at Array.B (ckeditor.js:244) [angular]
    at u (ckeditor.js:244) [angular]
    at HTMLScriptElement.CKEDITOR.env.ie.f.$.onerror (ckeditor.js:245) [angular]
    at HTMLScriptElement.wrapFn [as __zone_symbol___onerror] (polyfills.bundle.js:12164) [angular]
    at Object.onInvokeTask (vendor.bundle.js:4327) [angular]
    at ZoneDelegate.invokeTask (polyfills.bundle.js:11362) [angular]
    at Zone.runTask (polyfills.bundle.js:11130) [<root> => angular]
    at HTMLScriptElement.ZoneTask.invoke (polyfills.bundle.js:11425) [<root>]
defaultErrorLogger @ vendor.bundle.js:1295

```

**Comment by kzimny** [comment]
Yes, because the plugin is not installed on your localhost. Load the ckeditor from CDN as follow and try again: `<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>`

**Comment by keryhu** [comment]
If i use custom plugins and use this `<script src="assets/ckeditor/ckeditor.js"></script>`. and had download `div editing area` plugins .why still 404?

**Comment by kzimny** [comment]
Is your page working with `<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>` ?

**Comment by keryhu** [comment]
yes, if use `<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>` , no errors.

**Comment by kzimny** [comment]
great! look at [stackoverflow](http://stackoverflow.com/questions/15031840/ckeditor-div-based-editor). The divarea plugin need to be set in config file as follow:
`CKEDITOR.editorConfig = function( config ) {
    config.extraPlugins = 'divarea'
};`

Please close the thread and good luck!

**Comment by Bill-Y-Huang** [comment]
with Angular 5, ng2-ckeditor: 
<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script> , as keryhu said, no errors.
<script src="//cdn.ckeditor.com/4.9.2/full/ckeditor.js"></script>, errors.

<div class="form-group">
                <label for="description"><strong>Description</strong></label>
                <ckeditor class="form-control" id="description"
                  formControlName="description"
                  [config]="{uiColor: '#a4a4a4', extraPlugins: 'divarea'}"
                  debounce="500">
                </ckeditor>
              </div>

**Comment by kzimny** [comment]
Please use the full-all version with all included plugins:
`<script src="https://cdn.ckeditor.com/4.9.2/full-all/ckeditor.js"></script>`
Look at online [ng2-ckeditor demo](https://stackblitz.com/edit/ng2-ckeditor).

**Comment by l-ning** [comment]
@kzimny hello, if my use local js file , how about ? thank you ,very much

**Comment by kzimny** [comment]
are you looking for [this ](https://github.com/chymz/ng2-ckeditor/issues/228) solution?

**Comment by l-ning** [comment]
@kzimny yes,Download this plug-in to report an error , It's available online
