### ISSUE TITLE
Divarea plugin breaks the Enter key "new line"

### ISSUE THREAD

**Issue by wnabil** [chymz/ng2-ckeditor#107]
As i see in other issue about the error 
`[CKEDITOR] Error code: editor-destroy-iframe.`
The way to fix this error is to use the divarea plugin.However, when i use this plugin the Enter key or Return key "new line" stops working.
If i look inside the source of the editor i can see the p and br tags appears but they are inserted at the bottom of the editor 
EX:

> <"PTag">line1line2</"PTag">

> <"PTag">&nbsp;</"PTag">

> <"PTag">&nbsp;</"PTag">

disabling the plugin fix the problem but the iframe error will return.

**Comment by kzimny** [comment]
The problem with divarea and focus has been reported as a [bug ](https://dev.ckeditor.com/ticket/16809#comment:7) on CKEditor development page. As a workaround use version 4.6.1 instead.
