### ISSUE TITLE
Does not seem to work with Angular 4.x.x

### ISSUE THREAD

**Issue by AlanObject** [chymz/ng2-ckeditor#108]
Currently ng2-ckeditor has version problems with Angular 4 which I am using.  when you attempt nom install you get:

npm WARN ng2-ckeditor@1.1.6 requires a peer of @angular/core@^2.1.0 but none was installed.
npm WARN ng2-ckeditor@1.1.6 requires a peer of @angular/forms@^2.1.0 but none was installed.
npm WARN ng2-ckeditor@1.1.6 requires a peer of @angular/common@^2.1.0 but none was installed.

 Is anyone aware of this and is there any workaround?

I opened a stackoverflow ticket with this issue [here](http://stackoverflow.com/questions/43709675/how-to-resolve-dependencies-for-ng2-ckeditor/43710014#43710014).

**Comment by AlanObject** [comment]
Update:  ng2-ckeditor works fine if you extract the src directory and simply compile it with your Angular4 project.  There doesn't seem to be any compatibility issues so this must just be a packaging limitation.

**Comment by chymz** [comment]
Fixed in `1.1.7`
