### ISSUE TITLE
CKEditor Uncaught TypeError: Cannot call method 'unselectable' of null

### ISSUE THREAD

**Issue by zeflq** [chymz/ng2-ckeditor#109]
i got the error #44 after route change ,it seems liks the CKEDITOR.instances.editorX.destroy(); is missing on ngOnDestroy() http://docs.ckeditor.com/#!/api/CKEDITOR.editor-method-destroy
i pushed a PR #106

**Comment by danielehrhardt** [comment]
Same here!!

**Comment by chymz** [comment]
PR merged & published
