### ISSUE TITLE
Dialog button onClick event not fired "possible bug"

### ISSUE THREAD

**Issue by wnabil** [chymz/ng2-ckeditor#111]
I am trying to make a custom event for send it to server button.
i got the button object and i can see the onClick event inside it but anyway the event not firing.
```js
declare var CKEDITOR:any;

@Component({
.
.
.
ngAfterViewInit() {
  CKEDITOR.on( 'dialogDefinition', function( ev ) {
      var dialogName = ev.data.name;
      var dialogDefinition = ev.data.definition;
      if (dialogName == 'image') {
        dialogDefinition.onLoad = function() {
          var dialog = CKEDITOR.dialog.getCurrent();
          var uploadTab = dialogDefinition.getContents('Upload');
          var uploadButton = uploadTab.get('uploadButton');
          console.log('uploadButton', uploadButton); // => logging the button
          uploadButton.onClick = (evt)=>{
            console.log('send it to server btn', evt); // not working when click send it so server
          };
        };
      }
    });
}
```

**Comment by kzimny** [comment]
Strange implementation... Try the following:
https://github.com/chymz/ng2-ckeditor/issues/93
https://github.com/chymz/ng2-ckeditor/issues/100

`import { Component, Input, OnInit, ViewChild } from "@angular/core";

@Component({
    selector: "app-html-control",
    template: `
    <ckeditor
        [(ngModel)]="section.Content"
        [config]="ckeConfig"
        #ckeditor
        debounce="500">
            <ckbutton [name]="'imageExplorer'"
                [command]="'openImageExplorer'"
                (click)="openImageExplorer($event)"
                [icon]="/Images/folder.png"
                [label]="'Open file explorer'"
                [toolbar]="'insert,1'">
            </ckbutton>
        </ckeditor>
`,
})
export class HtmlControlComponent implements OnInit {
    ckeConfig: any;
    @ViewChild("ckeditor") ckeditor: any;

    constructor() { }

    ngOnInit() {
        this.ckeConfig = {
            height: 500,
            language: "en",
            allowedContent: true,
            extraPlugins: "divarea",
            toolbar: [
                { name: "editing", items: ["Scayt", "Find", "Replace", "SelectAll"] },
                { name: "clipboard", items: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo"] },
                { name: "links", items: ["Link", "Unlink", "Anchor"] },
                { name: "tools", items: ["Maximize", "ShowBlocks", "Preview", "Print", "Templates"] },
                { name: "document", items: ["Source"] },
                { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe", "imageExplorer"] },
                "/",
                { name: "basicstyles", items: ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat"] },
                { name: "paragraph", items: ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "CreateDiv", "-", "Blockquote"] },
                { name: "justify", items: ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"] },
                { name: "styles", items: ["Styles", "Format", "FontSize", "-", "TextColor", "BGColor"] }
            ]
        };

    }

    openImageExplorer($event: any) {

    }

}`

**Comment by wnabil** [comment]
Well it works if i create a custom button but what i was trying to do is overriding the default send to server button
