### ISSUE TITLE
Unable to pass a config object from controller

### ISSUE THREAD

**Issue by dotlouis** [chymz/ng2-ckeditor#112]
Hi,
I tried passing a config object from a controller like this, but it does not work. It sets the default config object.
```HTML
        <ckeditor
                [(ngModel)]="mailTemplate.body"
                [ngModelOptions]="{standalone: true}"
                [config]="ckeConfig"
                debounce="500">
        </ckeditor>
```
```JS
//in controller class
public ckeConfig = {
        toolbarGroups: [
            { name: 'mode' },
            { name: 'tools' },
            { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
            { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align' ] },
            { name: 'colors' }
        ],
        removeButtons: 'Save,Templates,Find,Replace,Scayt,SelectAll,Subscript,Superscript',
        protectedSource: [ /<?#[\s\S]*?>/g ]
    };
```

The only way I could do it it by passing it directly inline in the HTML like so:
```HTML
        <ckeditor
                [(ngModel)]="mailTemplate.body"
                [ngModelOptions]="{standalone: true}"
                [config]="{
        toolbarGroups: [
            { name: 'mode' },
            { name: 'tools' },
            { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
            { name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align' ] },
            { name: 'colors' }
        ],
        removeButtons: 'Save,Templates,Find,Replace,Scayt,SelectAll,Subscript,Superscript',
        protectedSource: [ /<?#[\s\S]*?>/g ]
    }"
                debounce="500">
        </ckeditor>
```

However regex pattern is not supported in angular templates so I can't do anything with it.
A little help would be appreciated.
Thanks :)

**Comment by kzimny** [comment]
What do you mean with Controller? In Angular 2 controller class does not exist, except you have own controller class implementation. Anyway... Try the following:

`import { Component, Input, OnInit, ViewChild } from "@angular/core";

@Component({
    selector: "app-html-control",
    template: `
                <ckeditor
                    [(ngModel)]="section.Content"
                    [config]="ckeConfig"
                    #ckeditor
                    debounce="500">
                  </ckeditor>
`,
})
export class HtmlControlComponent implements OnInit {
    ckeConfig: any;
    @ViewChild("ckeditor") ckeditor: any;

    constructor() { }

    ngOnInit() {

        this.ckeConfig = {
            height: 500,
            language: "en",
            allowedContent: true,
            extraPlugins: "divarea",
            toolbar: [
                { name: "editing", items: ["Scayt", "Find", "Replace", "SelectAll"] },
                { name: "clipboard", items: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo"] },
                { name: "links", items: ["Link", "Unlink", "Anchor"] },
                { name: "tools", items: ["Maximize", "ShowBlocks", "Preview", "Print", "Templates"] },
                { name: "document", items: ["Source"] },
                { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe"] },
                "/",
                { name: "basicstyles", items: ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat"] },
                { name: "paragraph", items: ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "CreateDiv", "-", "Blockquote"] },
                { name: "justify", items: ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"] },
                { name: "styles", items: ["Styles", "Format", "FontSize", "-", "TextColor", "BGColor"] }
            ]
        };
    }
}`
