### ISSUE TITLE
Divara plugin dosent work

### ISSUE THREAD

**Issue by OdaiTu** [chymz/ng2-ckeditor#113]
![image](https://cloud.githubusercontent.com/assets/12837840/25694604/07af14e0-30b8-11e7-92d5-e81452da1d17.png)

and this is my code

`<ckeditor
                          name="content"
                          #content="ngModel"
                          required 
                          [config]="{language : 'Ar', height: 500 , fontSize_defaultLabel: '22px' ,
                                      'font-size': '22px',
                                      extraPlugins: 'divarea'
                                    }"
                          [(ngModel)]="selectedNews[0]?.content && selectedNews[0].content"
                          [ngModelOptions]="{standalone: true}"
                          debounce="1000"
                          >
                        </ckeditor>`

**Comment by chymz** [comment]
See : https://github.com/chymz/ng2-ckeditor/issues/24#issuecomment-280364961
