### ISSUE TITLE
how to add more than one plugin

### ISSUE THREAD

**Issue by OdaiTu** [chymz/ng2-ckeditor#114]
i try to add a imageupload plugin but i have the divara plguin so an errors comes up when i write this code
`[config]="[{language : 'Ar', height: 500 , fontSize_defaultLabel: '22px' ,
                                      'font-size': '22px',
                                      extraPlugins: {'divarea', 'uploadimage'}
                                      
                                    }]"`
and how to config the image uploading and drag and drop files i see the ckeditor congif but its not about angular 2

**Comment by chymz** [comment]
`extraPlugins: 'divarea,uploadimage'`

Please read official docs : http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-extraPlugins

**Comment by OdaiTu** [comment]
thank you i have another questions
i want to add more plugins to my ckeditor
so i installed their from ckbuilder good ? 
now how to add them to my ckeditor that already exist <installed by npm> and url in index.html

**Comment by OdaiTu** [comment]
@chymz
