### ISSUE TITLE
Cannot find name 'object' in angular 2 cli

### ISSUE THREAD

**Issue by zap-deepak** [chymz/ng2-ckeditor#119]
Hi,
I have insalled ng2-ckeditor using cli :- npm install ng2-ckeditor --save
Then Include CKEditor javascript files in my index file :- <script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
Then imported module in module file:
import { CKEditorModule } from 'ng2-ckeditor';
in imports "CKEditorModule"

and trying to use in html 
<ckeditor [formControl]="description" [config]="config" ></ckeditor>

It show error: 
ERROR in /var/www/html/eventswebsite/frontendapp/node_modules/ng2-ckeditor/lib/ckeditor.component.d.ts (43,26): Cannot find name 'object'.

"ng2-ckeditor/lib/ckeditor.component.d.ts (43,26): Cannot find name 'object'."

**Comment by zap-deepak** [comment]
its working if i change 
ckeditorInit(config: object) {
to:
ckeditorInit(config: any) {

in npm module ckeditor component file.

**Comment by zap-deepak** [comment]
But this is not proper solution of this issue if i again use npm install problem will be same again.
so can please provide any proper solution of this problem.

**Comment by chymz** [comment]
I've patched source, i'll will publish this soon on npm

**Comment by dphaener** [comment]
@chymz Any updates on this?

**Comment by eliteluxury** [comment]
@chymz Could you teach me how to solve this problem?
