### ISSUE TITLE
Ckeditor dosent appera

### ISSUE THREAD

**Issue by OdaiTu** [chymz/ng2-ckeditor#122]
hello 
i have installed the ckeditor via npm and then i wanted to download it form the original site  because i downloaded it with some plugins and now i put the ckeditor folder in my assets and call the ckeditor.js in my index.html and put this come in my component html file
`<textarea name="content" 
                                    id="editor1" 
                                    rows="20" 
                                    cols="80"
                                    ngModel>
                          </textarea>
                              <script type="text/javascript">
                                  CKEDITOR.replace("editor1" , {
                                    language: 'Ar'
                                  });
                              </script>`

but nothing appear just the text area 
in my console js tag the ckeditor comes with 200 status

so where is the problem ?

**Comment by OdaiTu** [comment]
its now good but im facing another problem
the textarea dont binding the data to my model !!!

**Comment by chymz** [comment]
Not related to this repo
