### ISSUE TITLE
ckeditor.js:21 [CKEDITOR] Error code: editor-destroy-iframe.

### ISSUE THREAD

**Issue by 02harleen** [chymz/ng2-ckeditor#123]
Hi, I have use angular 4 and ckeditor 4.6.2. If I am go to next component show this error :- `[CKEDITOR] Error code: editor-destroy-iframe. 
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-destroy-iframe`

Please tell us how to solve this error.

**Comment by RodolfoSilva** [comment]
Maybe you can try #24, but this solution not work with `'fullPage'`

**Comment by rmcsharry** [comment]
The correct solution to this issue is [here](https://stackoverflow.com/questions/3613215/how-to-properly-destroy-ckeditor-instance/3613307#3613307)

Basically implement an onDestory lifecycle hook and destroy the iFrame there.
