### ISSUE TITLE
Webpack Compilation Issue

### ISSUE THREAD

**Issue by Jonatino** [chymz/ng2-ckeditor#126]
Getting the following error on the latest ng2-ckeditor when building with webpack.

```[at-loader] Checking finished with 1 errors
Error in bail mode: [at-loader] ./node_modules/ng2-ckeditor/lib/ckeditor.component.d.ts:43:26 
    TS2304: Cannot find name 'object'.
```

**Comment by michalstepien** [comment]
Yep it is not pusblished in npm. NPM has 1.1.7 and package 1.1.8

**Comment by michalstepien** [comment]
Workaround use:  "ng2-ckeditor": "https://github.com/chymz/ng2-ckeditor/tarball/master"

**Comment by maulin** [comment]
@chymz is there an eta on when the fix will be published to npm?

**Comment by chymz** [comment]
1.1.8 published
