### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by jgpATs2w** [chymz/ng2-ckeditor#127]
Chromium Version 51.0.2704.79 Built on Ubuntu 14.04, running on LinuxMint 17.3 (64-bit)
![screenshot from 2017-06-02 15 18 48](https://cloud.githubusercontent.com/assets/4340243/26727366/e6819490-47a6-11e7-8185-0cf3c2c745de.png)

**Comment by chymz** [comment]
Fixed : demo use latest versions
