### ISSUE TITLE
CSS is loaded every time when CKEditor is created

### ISSUE THREAD

**Issue by amirduran** [chymz/ng2-ckeditor#131]
Every time when I load ckeditor in my application, contents.css is downloaded. For example, I have 100 comments, that I want to display in CKEditor (one by one), then contents.css will be downloaded 100 times. Can we stop this?
<div *ngFor="let comment of comments">

```
<div *ngFor="let comment of comments">
<ckeditor class="editor-suggestion"
        [(ngModel)]="comment.text"
	[config]="Helpers.getCkEditorConfig()"
	(change)="onTextChange($event)"
	debounce="500">
</div>
```

**Comment by amirduran** [comment]
Any update on this question?

**Comment by chymz** [comment]
It's the default behavior of CKEditor, see this : http://jsfiddle.net/xykk4nss/
