### ISSUE TITLE
error trying to use editor

### ISSUE THREAD

**Issue by figuerres** [chymz/ng2-ckeditor#135]
'CKEditor 4.x is missing (http://ckeditor.com/)'

i am using angular-cli , current angular 4 bits  using info from https://github.com/chymz/ng2-ckeditor/issues/134

my app starts up, but when i navigate to the view that has an editor i get only a small textarea and the error in the console log.

**Comment by figuerres** [comment]
my bad !!!   typeo in sample code paste into my code....

**Comment by whitesnow9291** [comment]
How are you
I am getting same warning. And I did check all code but not found any type
Where did you find typo?

**Comment by figuerres** [comment]
In my case it was a bad html tag as I recall,a missing < OR > I think.... something like that anyway.

**Comment by whitesnow9291** [comment]
Thanks. I am using Angular 4, and want to use ng2-ckeditor.
I am not sure how to set systemjs configuration.
 System.config({
    "map": {
      "ng2-ckeditor": "npm:ng2-ckeditor",
    },
    "packages": {
      "ng2-ckeditor": {
        "main": "lib/index.js",
        "defaultExtension": "js",
      },
    }
  });
In my project, there is no systemjs, so I didn't set this configuration.
And implemented all other settings.
The result is simple textbox with warning 'CKEditor 4.x is missing (http://ckeditor.com/)'.
So Do I have to set systemjs surely to implement ckeditor?
without doing this, how to use this plugin?
Thanks.

**Comment by figuerres** [comment]
You do not need system is, I use angular cli and it works. When I am at work I can lookup the info but it is documented here, I just do not have the link right now.

**Comment by figuerres** [comment]
look at this [https://github.com/chymz/ng2-ckeditor/issues/134](url)

in your html file - index.html or whatever, add the tag for the cdn that has the script.
add the npm .

make a view that uses the plugin.
