### ISSUE TITLE
CKEditor is empty if ngModel is populated before `instanceready`

### ISSUE THREAD

**Issue by tjwoon** [chymz/ng2-ckeditor#136]
Using `<ckeditor>` the way the example shows seems to exhibit a problem:

```
import { Component } from '@angular/core';

@Component({
  selector: 'sample',
  template: `
  <ckeditor
    [(ngModel)]="ckeditorContent"
    [config]="{uiColor: '#99000'}"
    (change)="onChange($event)"
    (ready)="onReady($event)"
    (focus)="onFocus($event)"
    (blur)="onBlur($event)"
    debounce="500">
  </ckeditor>
  `
})
export class Sample{
  constructor(){
    this.ckeditorContent = `<p>My HTML</p>`;
  }
}
```

If my ngModel value is set before the CKEditor's `instanceready` event has fired, my CKEditor element will be blank.

I noticed this on my page when my Web Service call returns data before my CKEditor's instanceready event has fired. I worked around it by calling my Web Service only _after_ the instanceready event, like this:

```
import { Component } from '@angular/core';

@Component({
  selector: 'sample',
  template: `
  <ckeditor
    [(ngModel)]="ckeditorContent"
    [config]="{uiColor: '#99000'}"
    (change)="onChange($event)"
    (ready)="onReady($event)"
    (focus)="onFocus($event)"
    (blur)="onBlur($event)"
    debounce="500">
  </ckeditor>
  `
})
export class Sample{
  ckeditorContent = '';
  constructor(){}
  onReady() {
    this.ckeditorContent = `<p>My HTML</p>`;
  }
}
```

Has anyone else encountered the same problem?

I am using ng2-ckeditor@1.1.8 and CKEDITOR@4.6.2.

**Comment by chymz** [comment]
Sorry, can you make a sample repo to reproduce your problem ?
Demo working fine : https://embed.plnkr.co/hnB0R3/

**Comment by kzimny** [comment]
if passing data in conctructor is not working because of some delay, try to load data in ngOnInit() {}

**Comment by sudosandwich3** [comment]
I noticed this happens when ngModel is set to a value (say undefined) and then after the component is initialized the model is changed again before the ready event fires.

**Comment by sudosandwich3** [comment]
@chymz here is a sample https://plnkr.co/edit/gXLp80 You may have to adjust the timeout to trigger the issue, but it is possible for the editor value and the model value to not be the same in the model is changed before the ready method is called.

**Comment by kzimny** [comment]
I have updated your [plunker](https://plnkr.co/edit/sWOmnC?p=preview). Is that what you are looking for? If you model value change between initial instatiation and component initialization, you can change the value in onReady() event like that:
```js
import {Component, ViewChild} from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <ckeditor [(ngModel)]="content" debounce="500" (ready)="onReady($event)" #ckeditor>
      <p>Hello <strong>world</strong></p>
    </ckeditor>
    <div [innerHTML]="content"></div>
  `,
})
export class App {
  
  @ViewChild("ckeditor") ckeditor: any;
  content: string;
  myModelChanged: string;

  constructor() {
    this.content = '<p>Old Text</p>';
    
    setTimeout(() => {  
      this.myModelChanged = '<p>Is the way feasible?</p>';
    }, 50);
    
  }
  
  onReady(): void {
    if(this.ckeditor)
    {
      this.content = this.myModelChanged;
      // or
      //this.ckeditor.instance.setData(this.myModelChanged);
    }
  }
}
```

**Comment by kzimny** [comment]
Issue closed due to inactivity
