### ISSUE TITLE
Change of focus loses recent changes

### ISSUE THREAD

**Issue by JonathanG2nd** [chymz/ng2-ckeditor#137]
If you have an editor, and you make a change in it and quickly lose focus, the most recent changes will not get updated to the ngModel.  It will be displayed in the editor box, but if you look at the underlying data it won't have the new information.

E.G. if you have 4 boxes, paste something in the 4, and then click in each one to add a number(1-4 for example) it can go quick enough that the number won't always be updated in the underlying data.

I believe the debounce affects it, and so with a higher debounce it is easier to cause, but even with a debounce of 0 it can still happen.

**Comment by chymz** [comment]
I've quiclky tested it : https://plnkr.co/edit/aRgZA0?p=preview

But cant reproduce :(

**Comment by JonathanG2nd** [comment]
I will adjust to try and get it working, it may be because I am using an ngFor and divarea.  I will post a link when I get it reproduced.

**Comment by JonathanG2nd** [comment]
https://plnkr.co/edit/Jxgvr8LzxOe3SEsZ5oub?p=preview

You have to click outside of it fairly quickly(it isn't common, but a user did notice it and complained).  If you hover the mouse outside of the box, hit a single character, and then click outside, the underlying data doesn't update.

**Comment by chymz** [comment]
Sorry i've tested on Firefox and Chrome but cant reproduce your problem.

**Comment by JonathanG2nd** [comment]
You have to click pretty quickly, (it was hard for me to reproduce the issue before I figured it out as well.)  What I end up doing it hovering my mouse outside, with my hand on the button, and immediately after I click "1" I click outside the box.

To clarify, I am using Chrome.

Here is an image showing it, where I did it 3 times in a row.  (This is in the plunker, the text at the bottom is linked to the text in the editor).
![screen shot 2017-06-23 at 3 17 57 pm](https://user-images.githubusercontent.com/27022183/27500836-6a733e62-5827-11e7-95c1-6a7fe39ee37f.png)

**Comment by kzimny** [comment]
tested on Firefox, chrome and Edge. I can not reproduce your problem either.

**Comment by osamamourad** [comment]
I have the same issue after pasting any text, I have to write something after the paste for the model to be updated with the new value.

**Comment by kzimny** [comment]
tested again with chrom and edge, still no issue. Please test on my [online demo](https://stackblitz.com/edit/ng2-ckeditor). How to reproduce your problem? Without an example, it will be hard to help you, therefore:
1. provide your code example
2. maybe could you capture a video
