### ISSUE TITLE
Setting Style does not work

### ISSUE THREAD

**Issue by isaac2004** [chymz/ng2-ckeditor#138]
Using the demo, if I try to set text background color, it is not being added to the 
<div [innerHTML]=content> area. I am not sure if innerHTML can handle CSS injected as well.

**Comment by isaac2004** [comment]
FYI this seems to be an issue on the editor as well. You can get some styling using a safeHtmlPipe (google it ) but for things like Code Snippet, the styling isn't being passed along

**Comment by kzimny** [comment]
To set the toolbar color you can add the config property uiColor as follow:
```js
                this.ckeConfig = {
                    height: 500,
                    language: "en",
                    uiColor: "#AADC6E",
                };
```
To change the body color you have two options:
1. Add this line to your code:
```js
<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>
<script type="text/javascript">
	CKEDITOR.addCss(".cke_editable{background-color: red}");
</script>
```
2. **After the ckeditor is initialized**
```js
@ViewChild("ckeditor") ckeditor: any;

YourInitializeMethod() {
this.ckeditor.instance.editable().setStyle('background-color', 'green');
}
```
