### ISSUE TITLE
Add plugins with ng2-ckeditor

### ISSUE THREAD

**Issue by Romgua** [chymz/ng2-ckeditor#139]
Hi,

Is it possible to add some plugins to ng2-ckeditor like an image/file uploader ? Because is not possible with default ng2-ckeditor.

An example =>
![upload_image_ckeditor](https://user-images.githubusercontent.com/16555125/27577055-911c6a52-5b1f-11e7-9d9d-cfbf6d09fb78.png)

Thanks !

**Comment by kzimny** [comment]
Look at: https://github.com/chymz/ng2-ckeditor/issues/96
Add a button to toolbar and implement your own logic. It's not difficult.

**Comment by sakshiarora11** [comment]
> [``]( @ #url)
