### ISSUE TITLE
It is not working with Angular 2 rc 3

### ISSUE THREAD

**Issue by juligomez2** [chymz/ng2-ckeditor#14]
Im trying to deploy in my app this fantastic component, but with the changes in RC 3 with forms dont work properly... You will update the component to the last version? Thank you!

**Comment by tylerjgarland** [comment]
I'd advise waiting until the forms component is stabilized before asking for changes. Angular has moved two versions of RC in the past few weeks alone. Wait until RTM.

**Comment by chymz** [comment]
Thanks for your answer @tylerjgarland, I agree !
If you can't wait @juligomez2, feel free to send a PR

**Comment by chymz** [comment]
Resolved in 1.0.4 (6eaff6db2e9b3a44f5802db03d715fb8d8fe59bd)
