### ISSUE TITLE
Not working with Angular 2 Material (md-tabs) 

### ISSUE THREAD

**Issue by dineshdedhia** [chymz/ng2-ckeditor#142]
**Before Installing divarea plugin**

Cannot read property 'unselectable' of null

**After Install in divarea plugin** 

I am getting this error
ERROR in ./~/divarea/divarea.vue
Module parse failed: /home/developer5/Projects/pms-client/node_modules/divarea/divarea.vue Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
 <template>
  <div class="divarea-wrapper">
        <div class="divarea-col"></div>
 @ ./~/divarea/index.js 11:16-40
 @ ./src/app/scheduling/scheduling.module.ts
 @ ./src async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

**Comment by kzimny** [comment]
Have you tried the full version of the ckeditor 4.5 as follows: 
`<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>`
and in your component:
`public ckConfig ={ uiColor: '#f6f7f8', extraPlugins: 'divarea' }`

**Comment by dineshdedhia** [comment]
Yes, Still the problem is same. Not working in 2nd <md-tab>

**Comment by chymz** [comment]
You have installed the npm package https://www.npmjs.com/package/divarea and its a Vue component.

CKEditor 4.x have its own plugins manager, you dont have to install it via NPM.

Please read CKEditor docs : http://docs.cksource.com/Main_Page
