### ISSUE TITLE
How to add image browser plugin

### ISSUE THREAD

**Issue by hemnath11** [chymz/ng2-ckeditor#144]
I need to browse image files from server... how to integrate image browser plugin

**Comment by kzimny** [comment]
Actually there is no plugin for ckeditor to browse for files from server written in angular2. You need to implement the logic yourself. But this is not a big challenge. Try something like that:
```html
                <ckeditor
                    [(ngModel)]="YourModelNameHere"
                    [config]="ckeConfig"
                    #ckeditor
                    debounce="500">
<ckbutton [name]="'imageExplorer'"
 [command]="'openImageExplorer'"
 (click)="openImageExplorer($event)"
 [icon]="'./images/Icon.png'"
 [label]="'Open image explorer'"
 [toolbar]="'insert,1'">
</ckbutton>
                  </ckeditor>

        <app-dialog-modal *ngIf="showFiles"
             [visible]="showFiles"
             (onDecline)="onCloseImage()"
             (onConfirm)="onAddImage()">
        </app-dialog-modal>
```

in your config:
```js 
this.ckeConfig = {
            height: 400,
            language: "en",
            allowedContent: true,
            toolbar: [
                { name: "clipboard", items: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo"] },
                { name: "links", items: ["Link", "Unlink", "Anchor"] },
                { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe", "imageExplorer"] }
            ]
        };
```

```js
    openImageExplorer($event: any) {
        this.showFiles = true; // open pop-up window
    }
```

from your dialog window insert the link to your image as follows:
```js
    onCloseImage() {
        this.showFiles = false; // close the pop-up window
    }

onAddImage() {
        try
        {
            let link = this.ckeditor.instance.document.createElement("img");
            link.setAttribute("alt", "Image");
            link.setAttribute("src", "./Images/test.png");

            this.ckeditor.instance.insertElement(link);
        }
        catch(error)
        {
            console.log((<Error>error).message);
        }

        this.showFiles = false; // close the pop-up window
    }
```

**Comment by OdaiTu** [comment]
@kzimny  thank you for nice codeing
i would ask about the last block of code

this.ckeditor

how to pass the ckeditor to the editor place
this code in the modal component right ?!

**Comment by kzimny** [comment]
the this.ckeditor variable is defined as @ViewChild("ckeditor") as follows: @ViewChild("ckeditor") ckeditor: any; Does it help?

**Comment by OdaiTu** [comment]
@kzimny  i got this on console
Cannot read property 'instance' of undefined

**Comment by OdaiTu** [comment]
@kzimny

**Comment by kzimny** [comment]
It's difficult to say why you get undefined error message. Maybe you try to get ckeditor instance before it exist... When do you get the message? Paste some code, that would help.

**Comment by OdaiTu** [comment]
@kzimny  thank you

i have a component 'this component is my modal witch contain the file upload manger' 
another component with name add_news contain the ckeditor and in this component i call the modal when click the ck button ,

onAddimage function in the modal component and the viewchild ref in the modal component 
when execute the onAddImage function with your code above i got the error

here is add_news html file

![image](https://user-images.githubusercontent.com/12837840/30062153-d1b09e48-9252-11e7-8153-c7c6cc9b9c2a.png)


and here is the modal component

![image](https://user-images.githubusercontent.com/12837840/30062187-e53330ca-9252-11e7-9f80-d88a5e3b8a2d.png)

![image](https://user-images.githubusercontent.com/12837840/30062203-f807918c-9252-11e7-8c68-9d28015d25e1.png)

**Comment by kzimny** [comment]
remove this.onAddImage() from ngOnInit() method from your modal component. If I understand it correctly the ckeditor is placed in your add_news.component.ts class. And the modal component is placed in separate .ts class with selector name <modal-placeholder></modal-placeholder>. If so, you can define an output variables with EventEmitter in your modal_placeholder.ts class and listen on emitter in your add_news.component.ts class. Function onAddImage() need to be placed in add_news.component.ts class. 
```js
import { Component, EventEmitter, Input, Output } from "@angular/core";

@Component({
    selector: "modal-placeholder",
    templateUrl: "./dialogmodal.template.html"
})
export class DialogModalComponent {
    @Input() visible: boolean;

    @Output() onConfirm: EventEmitter<void> = new EventEmitter<void>();
    @Output() onDecline: EventEmitter<void> = new EventEmitter<void>();

    confirm() {
        this.onConfirm.emit();
    }

    close() {
        this.onDecline.emit();
    }
}
```

**Comment by OdaiTu** [comment]
@kzimny thank you its know clear to me the steps but i think its a problem since i use the modal and its dec with @Modal i think the @output and eventEmitter dosent fire !!

**Comment by kzimny** [comment]
Well,..."the proof of the pudding is in the eating". I think your question doesn't belong to topic ng2-ckeditor. Maybe you will find more information searching for @Output() onConfirm: EventEmitter<void> on google? An example how to use emitter can be found here https://blog.schwarty.com/checking-for-angular-2-output-wire-up-5fbe4bafadb7

**Comment by OdaiTu** [comment]
Worked Perfect

**Comment by kzimny** [comment]
Yep, for me too. Look at my implementation [http://www.znf.ch/stork/built-in-modules](http://www.znf.ch/stork/built-in-modules)

**Comment by Vishnupriya112** [comment]
@kzimny for me, 
openImageExplorer function is not invoked

**Comment by Vishnupriya112** [comment]
Uncaught TypeError: Cannot read property 'instance' of undefined . Am getting this error
