### ISSUE TITLE
hide footer

### ISSUE THREAD

**Issue by alan345** [chymz/ng2-ckeditor#146]
Hi !
this is really great !

Can we hide the footer ? 
![image](https://user-images.githubusercontent.com/15246526/28751056-5aaa2c14-74b2-11e7-80bc-ede2e730dda3.png)

Thanks

**Comment by kzimny** [comment]
Did you try to set the configuration options as follows?

in your config:
```js 
this.ckeConfig = {
            height: 400,
            language: "en",
            allowedContent: true,
            removePlugins: "elementspath",
            resize_enabled: false
        };
```

Similar question has been asked in CKEditor [forum](https://ckeditor.com/forums/CKEditor-3.x/Remove-tags-bottom-bar).

**Comment by chymz** [comment]
Thanks @kzimny !

**Comment by alan345** [comment]
Thanks
