### ISSUE TITLE
in full-all mode font color will be white

### ISSUE THREAD

**Issue by saostad** [chymz/ng2-ckeditor#147]
in full-all mode default font color from black changed to white, which is same as background color and text is not readable, 
is this a bug?
what is the solution?

Hi here is my configuration:

in component:

   ```
<ckeditor
        [config]="{extraPlugins: 'divarea'}"
        [(ngModel)]="selectedCategory.short_desc"
        debounce="500"
         name="short_desc">
    </ckeditor> 
```
and in index.html as reference:

`<script src="https://cdn.ckeditor.com/4.7.0/full-all/ckeditor.js"></script>`

**Comment by chymz** [comment]
Can't reproduce : https://plnkr.co/edit/mFde9dwC4A5KStS6pAcy?p=preview

Can you share more code ?
