### ISSUE TITLE
External plugins

### ISSUE THREAD

**Issue by Alcasser** [chymz/ng2-ckeditor#148]
Hi,
Is there any way to add external plugins?
As in ckeditor documentation: 

```
CKEDITOR.plugins.addExternal('youtube', '../node_modules/ckeditor-youtube-plugin/youtube/');

config.extraPlugins = 'youtube';
``` 

Thanks

**Comment by alex-ponce** [comment]
Same question. Interested in adding several plugins

**Comment by pgarzina** [comment]
mb smth like this?
`
 [config]="{
extraPlugins: 'uploadimage,font,footnotes' 
}"
`

**Comment by duffbuster** [comment]
@pgarzina this doesn't work unless ckeditor knows where the plugin.js file for the extra plugin is...

**Comment by Alcasser** [comment]
As mentioned by @duffbunster its about adding plugins which are not contained in the cdn version (local plugins)

**Comment by naveedahmed1** [comment]
Any update on this?

**Comment by ttugates** [comment]
I was able to go here, and after selecting all the plugins I wanted..  Chose download, with radio button set to Optimized..

Then copied all contents to Angular Project.

Then just instead of CDN.
<script src="ckeditor/ckeditor.js"></script>

Lastly, I used to have to do this, and now I dont.. At least for all plugins..  So will add just in case:

```
@ViewChild('ck') public ckeditor: CKEditorComponent;
public ckConfig: any;

 this.ckConfig = {
      removePlugins: 'resize',    
      extraPlugins: 'divarea,uploadimage'
    };
```

I am using other plugins not listed in extraPlugins..

**Comment by chymz** [comment]
Thanks @ttugates !

**Comment by fairmutex** [comment]
I got Local custom plugins to work along with ng2-ckeditor/ckeditor4 in angular 7 and probably it even works with previous versions too. I don't mean to necro but some might find it useful. 

For this I used the custom plugin from [here](https://github.com/ckeditor/ckeditor-docs-samples/tree/master/tutorial-timestamp)

Place your plugin in the assets folder as below
![image](https://user-images.githubusercontent.com/4706582/54873037-5ec3c200-4dce-11e9-9cf9-3911d779cf69.png)

and modify your index.html as below

```
<script src="https://cdn.ckeditor.com/4.5.11/full-all/ckeditor.js"></script>
<script type="text/javascript">
   CKEDITOR.plugins.addExternal('timestamp', '/assets/ckeditor/plugins/timestamp/', 'plugin.js');
</script>

```

The forward slash leading the assets folder is everything here. If it is not there it will try to get the plugin from their CDN

also add it to the config

```
  this.ckeConfig = {  
    allowedContent: false,    
    extraPlugins: 'divarea,timestamp',    
    forcePasteAsPlainText: false    
  };   
```

**Comment by sem1colon** [comment]
I tried the exact steps, it's not working. Can you please recheck this.

**Comment by ARoshanZamir** [comment]
> <script type="text/javascript">
>    CKEDITOR.plugins.addExternal('timestamp', '/assets/ckeditor/plugins/timestamp/', 'plugin.js');
> </script>

When I do your instruction I get the following error : 



> core.js:6241 ERROR Error: [CKEDITOR.resourceManager.load] Resource name "placeholder" was not found at "/assets/ckeditor/plugins/placeholder/plugin.js?t=J8Q8".
>     at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:270)
>     at e (ckeditor.js:265)
>     at Array.x (ckeditor.js:265)
>     at t (ckeditor.js:265)
>     at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:266)
>     at HTMLScriptElement.wrapFn (zone-evergreen.js:1218)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:399)
>     at Object.onInvokeTask (core.js:41645)
>     at ZoneDelegate.invokeTask (zone-evergreen.js:398)
>     at Zone.runTask (zone-evergreen.js:167)



I put the following in the index.html :

```
  <script type="text/javascript">
    CKEDITOR.plugins.addExternal('placeholder', '/assets/ckeditor/plugins/placeholder/', 'plugin.js');
  </script>
```

**Comment by kzimny** [comment]
Add the plugin to your config file:

```
  this.ckeConfig = {  
    allowedContent: false,    
    extraPlugins: 'divarea,placeholder',    
    forcePasteAsPlainText: false    
  }; 
```

**Comment by ARoshanZamir** [comment]
> Add the plugin to your config file:
> 
> ```
>   this.ckeConfig = {  
>     allowedContent: false,    
>     extraPlugins: 'divarea,placeholder',    
>     forcePasteAsPlainText: false    
>   }; 
> ```

**I got the same error** 

This is my completed code:

Index.html
```
  <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

  <script type="text/javascript">
    CKEDITOR.plugins.addExternal('placeholder', '/assets/ckeditor/plugins/placeholder/', 'plugin.js');
  </script>
```

In the component :
```
export class AppComponent implements OnInit {
  ckeditorContent = 'angualrckeditor';
  ngOnInit(): void {
    CKEDITOR.on('instanceCreated', function (event, data) {
      var editor = event.editor,
        element = editor.element;
      editor.name = "content"
    });
  }
}
```

and finally in the Html 
```
      <form #form="ngForm">
        <ckeditor #myEditor [(ngModel)]="ckeditorContent" name="ckeditorContent"
          [config]="{uiColor: '#a4a4a4' , allowedContent: false,forcePasteAsPlainText: false , extraPlugins: 'placeholder'}"
          debounce="500"> </ckeditor>
      </form>
```

I have to say: I have this path in my project:  `assets/ckeditor/plugins/placeholder`

**Comment by kzimny** [comment]
Add divarea plugin to your config file:
```
extraPlugins: 'divarea,placeholder'
```

**Comment by ARoshanZamir** [comment]
the correct answer is  here :

https://stackoverflow.com/questions/39208766/ng2-ckeditor-add-placeholder-plugin-using-typescript-and-angular-2-0/64329399#64329399

**Comment by kzimny** [comment]
The only one difference is the path to your plugins folder. In your example above it start with `/assets/` and in other solution with `./assets/`. In my projects the app is not installed in root folder but in subfolder so I'm using the `this.baseHref` reference as follow:

```
CKEDITOR.plugins.addExternal('youtube', '${this.baseHref}plugins/youtube/', 'plugin.js')
```
