### ISSUE TITLE
How can I get the source html?

### ISSUE THREAD

**Issue by cybrooke** [chymz/ng2-ckeditor#149]
I'm trying to create a preview of a page and for that I need the html from source. I know there's a method getData() but idk how to use it in angular2.

**Comment by pgarzina** [comment]
mb this
`
var window:any = this.windowRef.getNativeWindow()
var instance = window.CKEDITOR.instances[Object.keys(window.CKEDITOR.instances)[0]]
this.myData = instance.getData();
`

**Comment by chymz** [comment]
Try this : 

```ts
import { Component, ViewChild } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `<ckeditor #ckeditor debounce="500"></ckeditor>`
})
export class AppComponent {

  @ViewChild('ckeditor') ckeditor:any;

  onSomeAction() {
    console.log(this.ckeditor.instance.getData());
  }

}
```
