### ISSUE TITLE
model does't change on image drag and drop

### ISSUE THREAD

**Issue by pgarzina** [chymz/ng2-ckeditor#150]
hi, I'm experiencing an issue when drag/dropping in image from a folder to ckeditor. The issue appears only when I drop an image and dont add anything else after it. If I add some text after dropping an image, the model 'refreshes'.

the editor
```
                <ckeditor *ngIf="showCkEditor"
                id="signatureTemplate"
                name="signatureTemplate"
                [(ngModel)]="signatureTemplate"
                (change)="onTemplateChange($event)"
                (focus)="focusChanged('htmlTemplate',$event)"
                [config]="{
                  extraPlugins: 'uploadimage,font,footnotes',
                  contentsCss:'/assets/css/ckeditor.css',
                  uploadUrl: '...',
                  filebrowserUploadUrl: '...'
                }"
                debounce="50">
              </ckeditor>
```
after droping the image, the model, signatureTemplate, stays the same, if I add a letter after the img the model shows both the image and the letter

**Comment by eoodin** [comment]
Experiencing the same issue.

**Comment by csimpi** [comment]
same here

**Comment by kzimny** [comment]
@pgarzina & @eoodin do you still have the problem? Which version of ckeditor and ng2-ckeditor do you use?

**Comment by pgarzina** [comment]
hey, im on ckeditor 4.6.2 , angular 446
I've solved to problem with something like this
```
    var window: any = this.windowRef.getNativeWindow()
    var instance = window.CKEDITOR.instances[Object.keys(window.CKEDITOR.instances)[0]]
    this.signatureTemplate = instance.getData();
```
to get sure im getting the image if nothing added after the image

**Comment by kzimny** [comment]
The problem probably comes from ckeditor. If the workaround works for you I would close the issue. Did you try the latest version 1.2.0 of ng2-ckeditor? There are some changes in onChange event when the value change.

**Comment by pgarzina** [comment]
ok thx, ill probably try the new version on a new project :)

**Comment by DelGuapo** [comment]
Expanding on @pgarzina, i think another solution would be to implement ViewChild to gain access to the CKEDITOR class.  Its a little cleaner, but still a work-around.

in my HTML: 
``` 
            <ckeditor 
                #ckEditor
                [(ngModel)]="wysiwygModel"
                (change)="modifyParam($event)"
                [config]="WYSIWYGConfig">
            </ckeditor>
```

in my class: 
```
@ViewChild('ckEditor') ckEditor: ElementRef;

modifyParam() {
    const cke: any = <any>this.ckEditor;
    this.wysiwygModel = cke.instance.getData();
  }
```
