### ISSUE TITLE
Dynamically setting placeholder attribute value

### ISSUE THREAD

**Issue by eegasudheer** [chymz/ng2-ckeditor#151]
Hi,

In our application we are using ckeditor multiple places, we want to provide different placeholder text for each ckeditor. I tried below ways, but its not working. 

`<ckeditor [placeholder]="question.answerPlaceholder" [(ngModel)]="question.answer" debounce="500" 
[config]="ckEditorConfig" debounce="500"></ckeditor>`

`<ckeditor placeholder="{{question.answerPlaceholder}}" [(ngModel)]="question.answer" debounce="500" 
[config]="ckEditorConfig" debounce="500"></ckeditor>`

Any help is appreciated.

Thanks

**Comment by naveedahmed1** [comment]
@eegasudheer  have you found any solution? I came across this plugin https://alfonsoml.blogspot.com.es/2012/04/placeholder-text-in-ckeditor.html

I tried adding it to config, but it didnt work.

```
config={
...
extraPlugins: 'confighelper,divarea',
            placeholder:'Details'
...
}
```

**Comment by kzimny** [comment]
Hi, I suppose that you ([ngModel]) is empty when you open the page with <ckeditor></ckeditor>. If so, set the question.answer with you placeholder text as follows:
```js
import { Component } from '@angular/core';

@Component({
  selector: 'sample',
  template: `
  <ckeditor
    [(ngModel)]="ckeditorContent"
    [config]="{uiColor: '#99000'}"
    [readonly]="false"
    (change)="onChange($event)"
    (ready)="onReady($event)"
    (focus)="onFocus($event)"
    (blur)="onBlur($event)"
    debounce="500">
  </ckeditor>
  `
})
export class Sample{
  constructor(){
    this.question.answer = `<p>This is my placeholder text</p>`;
  }
}
```

**Comment by chymz** [comment]
Discussion continue in #170
