### ISSUE TITLE
CkEditor Instance value not cleared when i call form.reset()

### ISSUE THREAD

**Issue by mekramy** [chymz/ng2-ckeditor#155]
After i submitting my form data, i'll clear form for new input. but the ckeditor instance value not cleared! how can i do that?

- i use model driven form
- i use angular 4

my template code is:
`<ckeditor formControlName="content"></ckeditor>`

**Comment by kzimny** [comment]
Hi, did you try to set the value to an empty string? Look at: [how to reset value](https://ckeditor.com/forums/CKEditor-3.x/how-reset-value-ckeditor);
In HTML part:
```js
                <ckeditor
                    [config]="ckeConfig"
                    #ckeditor
                    debounce="500">
                  </ckeditor>
```
In typescript part:
```js
@ViewChild("ckeditor") ckeditor: any;

onEventOrRequest(event: any)
{
this.ckeditor.instance.setData('');
}
```

**Comment by kzimny** [comment]
@mekramy : is your problem solved? Can the task be closed?

**Comment by mekramy** [comment]
@kzimny thnaks. i move to vuejs and not work with angular any more!
other people may have same issue! any way you can close my issue if you want.

**Comment by kzimny** [comment]
If other people identify the same problem, please report and the task will be reopen.

**Comment by ronakvbhatt07** [comment]
Hi What I got this workaround. But I have validation message applied to the`CKEditor` and it happens that whenever I am trying to reset the form. I am able to reset the `CKEditor `but not the message. Anything that can be helpful here?

**Comment by kzimny** [comment]
Did you try to set the form to pristine?

```ts
<form role="form" class="form-horizontal" (ngSubmit)="save(basedataForm)" #basedataForm="ngForm"></form>
```

and in ts file

```ts
save(myForm: NgForm) {
	myForm.form.markAsPristine();
	myForm.form.markAsUntouched();
}
```

**Comment by jaydeep-aipl** [comment]
.ckeditor.instance.setData('<p></p>');
this.ckeditor.instance.updateElement();

**Comment by jaydeep-aipl** [comment]
**Fuck Off Dear

- [ ] @**
