### ISSUE TITLE
Custom plugin troubles.

### ISSUE THREAD

**Issue by Lakremon** [chymz/ng2-ckeditor#156]
Hello, everyone!
First, want thanks chymz for pretty good job in module development, you very help for all us! =)
I have a problem!
I need custom plugin for admin page. Which format selected text and wrap it in html tag with special class. If selected text contains this tag plugin should remove this tag (same like another buttons: bold, italic, etc)
Before wrap selected segment user should select one of several Entities. So, i maked it. =)
My component:
```TypeScript
import ...
@Component(...)
export class MyComponent {
    @ViewChild('ckeditor_2') ckeditor_1: CKEditorComponent;
    @ViewChild('ckeditor_2') ckeditor_2: CKEditorComponent;
    entities: Entity[] = [];
    myMainModel: MyModel;
    entityListOpen: boolean;
    currentFrame: any;
    cases: number[];
    ckeConfig = {
        height: 400,
        allowedContent: true
    };
    <...>
    constructor(private entityService: EntityService) {
        this.entityListOpen = false;
        this.entityService.getAll().subscribe(entities => {
            this.entities = entities;
        });
        <...>
    }
    <...>
    public onAddEntity(case) {
        this.zone.run(() => {
            this.entityListOpen = true;
        });
        this.currentFrame = languige == 'en' ? this.ckeditor_en : this.ckeditor_fr;
        this.currentFrame.case = case;
    }
    public selectEntity(entityId: string) {
        this.zone.run(() => {
            this.entityListOpen = false;
        });
        try {
            let iframedoc = this.currentFrame.instance.window.$.document;
            let tagName = 'span';
            let link = iframedoc.createElement(tagName);
            let selection = rangy.getIframeSelection(this.currentFrame.instance.window.$);
            let selectionRange = selection.getRangeAt(0);
            link.setAttribute("class", "likeSegment");
            link.setAttribute("data-entity-id", entityId);
            link.setAttribute("style", 'background: yellow;');
            //since you can't wrap something with an image tag
            if (tagName === 'img') {
                selectionRange.collapse(false);
                selectionRange.insertNode(link);
            } else if (tagName === "a" && selection.isCollapsed) {
                //provide some default text for an anchor
                selectionRange.collapse(false);
                link.appendChild(iframedoc.createTextNode('link'));
                selectionRange.insertNode(link);
            } else {
                selectionRange.surroundContents(link);
            }
            //detach rangy
            selection.detach();
            this.cases[this.currentFrame.case] = this.currentFrame.instance.getData();
        } catch (error) {
            console.log((<Error>error).message);
        }
    }
}
```
My template (this is PUG):
```
<...>
ckeditor("[(ngModel)]"="myMainModel.html" "debounce"="500" "config"="ckeConfig" "#ckeditor_1"="")
    ckbutton("name"="selectEntity1" "command"="selEntity1" "(click)"="onAddEntity(1)" "icon"="/entity.png" "label" = "Add antity wrap")
<...>
div.popup("*ngIf"="entityListOpen")
    select.input("[(ngModel)]"="selectedEntityId")
        option("*ngFor"="let entity of entities" "[ngValue]"="entity._id") {{entity.name.first}} {{entity.name.last}}
    button("(click)"="selectEntity(selectedEntityId)") Select entity
<...>
```
So, it work, but with some problems:
1) This component for create and change "myMainModel", but model's field didn't chnged after iframe content change. I need assign `myMainModel.html = this.cases[1]` befor post it on server side. And I have a lot bugs with cases whet user first add wrap and change document after.
2) ckeditor skip 'wrap' tag after repeated data downloading. Data download right, but ckeditor skip my tag. =(
3) How I can add my custom css in iframe. I need add `link.setAttribute("style", 'background: yellow;');`, but this is bad practic. I'll be happy if can just add `.likeSegment{background: yellow;}` css code.

So, I'll be very thenkfill for everyone whu help me! =)

**Comment by kzimny** [comment]
@Lakremon: did you find a way to solve the problems?

**Comment by Lakremon** [comment]
@kzimny hi, which one problem you mean? I got 3.

**Comment by kzimny** [comment]
Yes, I see. You can add css configuration to ckeConfig as follow:

```ts
ckeConfig: any;

  ngOnInit() {
                this.ckeConfig = {
                    allowedContent: true,
                    //extraPlugins: "divarea", <<<--- remove divarea extraPlugin
                    contentsCss: `.cke_editable  { 
                        background-color: #bfceb5; 
                    }
                    .myArea {
                        background-color: #89f441;
                    }`
                }; 
  }
```
![image](https://user-images.githubusercontent.com/12007674/36060990-e9e7f592-0e53-11e8-9619-12a1713c9074.png)


Would you prepare a plunker or a working example as angular/cli project for issues 1+2?

**Comment by Lakremon** [comment]
@kzimny So, about my issue, i already not need resolve it - project are done. The customer refused this decision for business reasons. I so thankful to you looking fore help me and another developers. Issue list looks match better then few month ago.
I geted experience on the project, and i think now i can resolve my issue myself. If you need any solution posted here, i have time and i can prepare it here for community. If is not - please, just close my issue. 
Thank you so much! Best reguards!

**Comment by kzimny** [comment]
Thank you for the comment. It would be great to see how you solved the problems 1 and 2. Yes, please share your solution with the community.
