### ISSUE TITLE
Can we use this editor for commercial purpose?

### ISSUE THREAD

**Issue by mihirkadam** [chymz/ng2-ckeditor#157]
We are creating the product and want to use CK editor for email.

**Comment by kzimny** [comment]
Hi, ng2-ckeditor is not an editor but rather a wrapper. Please refer to gn2-ckeditor license [file](https://github.com/chymz/ng2-ckeditor/blob/master/LICENSE). The ckeditor is available under several [licence models](https://ckeditor.com/ckeditor-5-builds/pricing/). You can use open source licence under GPL, LGPL, MPL therms without professional support. If you are not sure about the therms, please refer to ckeditor [forum](https://ckeditor.com/old/forums/Support/Can-I-use-CKEditor-commercial-software). Look at a similar question on [StackOverflow ](https://stackoverflow.com/questions/6305276/is-it-possible-to-use-ckeditor-in-commercial-web-site)website.
