### ISSUE TITLE
can not bind chinese which input after table

### ISSUE THREAD

**Issue by name100li** [chymz/ng2-ckeditor#161]
Please look at the red cycle. I input some words after the table in the editor，but the model data which print outside does not changed.
![test](https://user-images.githubusercontent.com/33193119/32141441-75df4932-bcbb-11e7-9862-20c47f95e26e.jpg)

**Comment by name100li** [comment]
I found that, the problem is not the table.
If the Chinese words not end with a new line.
The last line of the words will not bind to the model.

so the words must like.

`<p>你好</p><p>&nbsp;</p>`

only the 
`<p>你好</p>`
will not bind.

**Comment by kzimny** [comment]
I tried with Edge and cannot reproduce the behavior with the official ng2-ckeditor [plunker](https://embed.plnkr.co/hnB0R3/)
![chinesewords](https://user-images.githubusercontent.com/12007674/33928226-7fdd2d12-dfe5-11e7-9c5a-66c9794d0492.png)

The model change every time the text change.

**Comment by kzimny** [comment]
@name100li : is your problem solved? Can the task be closed?

**Comment by kzimny** [comment]
Issue closed due to inactivity
