### ISSUE TITLE
How to set dtd value

### ISSUE THREAD

**Issue by tejasrana95** [chymz/ng2-ckeditor#162]
I just setup it. and place 
`<ckeditor [config]="CkeditorConfig"></ckeditor>`
in my app.component.html

and in app.component.ts
`public CkeditorConfig = {
    allowedContent: true,
    extraAllowedContent: 'p(*)[*]{*};div(*)[*]{*};li(*)[*]{*};ul(*)[*]{*};span(*);i(*);',
    CKEDITOR: [{dtd: {$removeEmpty: {i: 0} } } ],
    height: 500,
    toolbarGroups: [{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
      { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
      { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
      { name: 'forms', groups: [ 'forms' ] },
      { name: 'styles', groups: [ 'styles' ] },
      { name: 'colors', groups: [ 'colors' ] },
      { name: 'tools', groups: [ 'tools' ] },
      '/',
      { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
      { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
      { name: 'links', groups: [ 'links' ] },
      { name: 'insert', groups: [ 'insert' ] },
      '/',
      { name: 'others', groups: [ 'others' ] },
  ],
    removeButtons: 'Save,NewPage,Print,Paste,PasteText,PasteFromWord,Scayt,Form,Radio,Checkbox,TextField,Textarea,Select,Button,ImageButton,HiddenField',
    removePlugins: 'htmldataprocessor',
    protectedSource: [ /{{[\s\S]*?}}/g ]
    //

   }`

But now I want to disable auto empty tag removal feature of CK editor.  I tried to add
` CKEDITOR.dtd.$removeEmpty['span'] = false;` in constructor but not working. same thing I tried in 
https://plnkr.co/edit/fnKvs4PLgweKcQNWDu3g?p=preview it is working fine.

**Comment by kzimny** [comment]
Did you try to set the additional configuration directly after <script></script> tag as follows:

<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
<script>
CKEDITOR.dtd.$removeEmpty['span'] = false;
</script>
