### ISSUE TITLE
Support for Angular 5+

### ISSUE THREAD

**Issue by tonnguyen** [chymz/ng2-ckeditor#165]
This is a feature request
Additional Notes:

Currently this project does not support Angular 5.0. Build warnings appear:
warning "ng2-ckeditor@1.1.9" has incorrect peer dependency "@angular/core@^2.1.0 || ^4.0.0".
warning "ng2-ckeditor@1.1.9" has incorrect peer dependency "@angular/forms@^2.1.0 || ^4.0.0".
warning "ng2-ckeditor@1.1.9" has incorrect peer dependency "@angular/common@^2.1.0 || ^4.0.0".

Is there any pre-release that does?

What do we need to change to implement the support?

**Comment by alaa-alshamy** [comment]
yea plz as fast as u can :)

**Comment by kzimny** [comment]
@chymz please compile the for Angular 5 as soon as possible. Many thanks Simon!

**Comment by lvidal1** [comment]
Any update?

**Comment by kzimny** [comment]
@chymz don't you keep the ng2-ckeditor up to date anymore?

**Comment by chymz** [comment]
Sorry, I've got a lot of work atm. I will merge #169 soon (this week)

**Comment by chymz** [comment]
Fixed in 1.1.12
