### ISSUE TITLE
How to use ng2-ckeditor to upload images to firebase storage?

### ISSUE THREAD

**Issue by omurbekjk** [chymz/ng2-ckeditor#166]

**Comment by kzimny** [comment]
Have you found a [ckeditor plugin ](https://ckeditor.com/cke4/addons/plugins/all) for that? If so you can use the plugin as described here: https://github.com/chymz/ng2-ckeditor/issues/159 or if not try to implement your own functionality https://github.com/chymz/ng2-ckeditor/issues/144
