### ISSUE TITLE
Multiple Instances

### ISSUE THREAD

**Issue by bstaley** [chymz/ng2-ckeditor#17]
I just wanted to note, I am using 4 instances on one page and was getting weird results. 

- The first worked fine. 
- The second's toolbar controlled the third's text. 
- The third one's toolbar was disabled. 
- The fourth one didn't show up.

When I added the `id` attribute everything began working as expected.

**Comment by chymz** [comment]
Hi,

Sorry, I'v tested it (https://embed.plnkr.co/P8Glcc/) but can't reproduce your results.
Can you elaborate you issue ?

**Comment by bstaley** [comment]
I checked your plunker out and the only difference was I am using reactive forms. Though I switched it to exactly what I had and couldn't repro it either. Thanks for checking it out.
