### ISSUE TITLE
HTML5 placeholder 

### ISSUE THREAD

**Issue by ioncode** [chymz/ng2-ckeditor#170]
for one of my projects i need this function and want to provide my realization for this needing

1. ckeditor init like ususal with some default placeholder text 
2. on first focus this text dissapered with this 
```
`  onFocus(event){
	var first = true;
	if (first)	{
		
		event.editor.setData('');
	}
	  console.log(event);
  }`
```

it can be realized on config level like 
```

`	*ngIf="answerFormGroup.value.tip" 
		style="margin-top: 20px; display: block;"
		formControlName="description"
		[config]="{uiColor: '#ffffff'}"
		[readonly]="false"
		(change)="onChange($event)"
		(ready)="onReady($event)"
		(focus)="onFocus($event)"
                 **[placeholder]="Default text here"**
		(blur)="onBlur($event)"
		debounce="500">
	  </ckeditor>`
```

**Comment by ioncode** [comment]
i have many editors on the single page app, so i realized placeholders this way:

`ckeditor:any=[];`

and event handlers 

```
`  onFocus(event){
	console.log([event, this.ckeditor]);  
	if (!this.ckeditor[event.editor.id]) {		
		this.ckeditor[event.editor.id]={
			placeholder: event.editor.getData(),
			//another: val,			
		};
		event.editor.setData('');
	}
	else {		
		if ( this.ckeditor[event.editor.id].placeholder == event.editor.getData()) {		
			event.editor.setData('');
		}		
	}  
  }
  onBlur(event){
	 if (this.ckeditor[event.editor.id] && !event.editor.getData()) {
		 event.editor.setData(this.ckeditor[event.editor.id].placeholder);
	 } 
	 console.log([event, this.ckeditor]);
  }`
```

in result placeholders are:

-  Dynamic (not hardcoded for whole project)
- Independent (for each ckeditor call by ID)
- Work as expected by enduser (dissapear on focus & returned on empty field)

**Comment by chymz** [comment]
Hi @ioncode, you need an additional plugin for this: https://ckeditor.com/cke4/addon/confighelper

But it seems a bit outdated, I dont know if it works...
