### ISSUE TITLE
Reactive Form

### ISSUE THREAD

**Issue by Korigoth** [chymz/ng2-ckeditor#171]
Any plan on supporting Reactive Form ?

**Comment by someoneNameGrey** [comment]
What kind of support do you mean? @Korigoth 
Any more details?

**Comment by Korigoth** [comment]
Reactive Form support  for  formControlName="editor"  on the editor itself

**Comment by someoneNameGrey** [comment]
Try this,
html:
`<ckeditor [(ngModal)]="editor" name="editor" formControlName="editor"></ckeditor>`
ts:
```
myForm;
editor;

ngOnInit(){
  this.myForm = new FormGroup({
  'editor': new FormControl ( this.editor, [Validator.required] )
 })
}

```

**Comment by nightullr** [comment]
I got this working for me in a reactive form. If you use `formControlName`, you don't need `ngModal` but you do need a parent [formGroup] in the template, like:

```
<form [formGroup]="myForm">
    <ckeditor name="myEditor" formControlName="editor"></ckeditor>
</form>
```

Or, you can do this if you create your FormGroup and FormControls in ngOnInit or if you have nested field components like I do, etc
```
<ckeditor name="myEditor" [formControl]="myForm.controls.editor"></ckeditor>
```

**Comment by kzimny** [comment]
Thank you all for the valuable tips.

**Comment by himajaM** [comment]
How to validate 
<ckeditor name="myEditor" [formControl]="myForm.controls.editor"></ckeditor>
in angular 7
Thanks in advance

**Comment by kzimny** [comment]
Look at the demo https://stackblitz.com/edit/ng2-ckeditor
