### ISSUE TITLE
Unexpected value 'CKEditorModule after upgrading to 1.1.11

### ISSUE THREAD

**Issue by beradrian** [chymz/ng2-ckeditor#172]
After upgrading to 1.1.11 I get the following error:
ERROR in Error: Unexpected value 'CKEditorModule in <myapp>/node_modules/ng2-ckeditor/lib/src/ckeditor.module.d.ts' imported by the module
'AppModule in <myapp>/src/app/app.module.ts'. Please add a
@NgModule annotation.

I'm using Angular5.

**Comment by chymz** [comment]
Sorry i've fucked up this version, please upgrade to 1.1.12

**Comment by beradrian** [comment]
Same error.

**Comment by chymz** [comment]
Are you sure ? `npm i ng2-ckeditor@1.1.12` ?
Which angular version ?

I'm working on a demo and dont have this error.

**Comment by kzimny** [comment]
Plunker is not working with the latest version https://embed.plnkr.co/hnB0R3/

**Comment by chymz** [comment]
I've fixed this, thanks @kzimny 

I think I will replace this demo with a sample with angular-cli

**Comment by beradrian** [comment]
I'm using Angular5

**Comment by kzimny** [comment]
I think that would help. But don't forget, people like your project because it's simple.  Keep it simple and up to date for new angular releases. I'm would try to answer questions as I did in the past.

**Comment by chymz** [comment]
thanks a lot for your help @kzimny !

@beradrian I will make a sample repo with angular cli soon

**Comment by beradrian** [comment]
If you want I can make such a sample.

**Comment by chymz** [comment]
@beradrian I've published a new version (1.1.13) can you try again ?
Thanks !

**Comment by kzimny** [comment]
Version 1.1.13 works for me on local machine and on production server with AoT compilation.

**Comment by beradrian** [comment]
Yes, it works for me too. Thanks!
