### ISSUE TITLE
Peer dependencies of 5.0.5

### ISSUE THREAD

**Issue by someoneNameGrey** [chymz/ng2-ckeditor#175]
**Error**
`npm WARN ng2-ckeditor@1.1.13 requires a peer of @angular/core@^5.0.5 but none is installed. You must install peer dependencies yourself.`
`npm WARN ng2-ckeditor@1.1.13 requires a peer of @angular/forms@^5.0.5 but none is installed. You must install peer dependencies yourself.`
`npm WARN ng2-ckeditor@1.1.13 requires a peer of @angular/common@^5.0.5 but none is installed. You must install peer dependencies yourself.`

My dependencies:
`"@angular/common": "^5.0.0",`
`"@angular/core": "^5.0.0",`
`"@angular/forms": "^5.0.0",`

It requires 5.0.5, yet I have 5.0.0 which is not too old. 
Can I choose not to update, and make some changes to the peerDep requirement? 
Or there are some important changes from 5.0.0 to 5.0.5, which I have to update it?

**Comment by kzimny** [comment]
I got the same warnings messages. It is interesting because the dependencies are set to ^5.0.0 as you can see in [pull request](https://github.com/chymz/ng2-ckeditor/pull/169/commits/840d331212fb575671b013228d72b4db01429c7a). It doesn't affect the function of ng2-ckeditor on my side.

**Comment by someoneNameGrey** [comment]
Yea it doesn't affect my side too. gotta wait for @chymz approve the pull request. So that we could enjoy the "perfect" installation. LOL

**Comment by kzimny** [comment]
In package.json the dependencies are set to angular 5.0.5:
  "devDependencies": {
    "@angular/animations": "^5.0.5",
    "@angular/common": "^5.0.5",
    "@angular/compiler": "^5.0.5",
    "@angular/compiler-cli": "^5.0.5",
    "@angular/core": "^5.0.5",
    "@angular/forms": "^5.0.5",
    "@angular/platform-browser": "^5.0.5",
    "@angular/platform-server": "^5.0.5",
    "@types/ckeditor": "0.0.45",
    "@types/core-js": "^0.9.43",
    "@types/node": "^8.0.54",
    "rxjs": "^5.5.2",
    "typescript": "^2.6.2",
    "zone.js": "^0.8.14"
  },
that's the reason for warning messages.

**Comment by someoneNameGrey** [comment]
Yea, I know that. I have also made a [pull request](https://github.com/someoneNameGrey/ng2-ckeditor/blob/patch-1/package.json) 3 hours before. But not sure whether any changes have been made which can't be supported in version lower than 5.
However, the function is working fine (at least it works on my side :) ). Just the messages are making people worries. Haha
