### ISSUE TITLE
How to add extraplugins

### ISSUE THREAD

**Issue by alimuddinhasan** [chymz/ng2-ckeditor#178]
Hi,

I want to add imageuploader https://ckeditor.com/cke4/addon/imageuploader 
How can I do this?

**Comment by kzimny** [comment]
Please have a look at the following answer https://github.com/chymz/ng2-ckeditor/issues/159. I'm sure that will help.

**Comment by alimuddinhasan** [comment]
Hi @kzimny thx for answering but I got a problem when implements this
`CKEDITOR.plugins.addExternal('imageuploader', './imageuploader/', 'plugin.js');`
I already put the plugin into specific folder but it not accesible by ckeditor.
then I change my code into
`CKEDITOR.plugins.addExternal('imageuploader', '/src/app/pages/article/imageuploader/', 'plugin.js');`
still  not work

**Comment by kzimny** [comment]
You are going to use a plugin written in php and that will not work with angular. Please look at https://github.com/chymz/ng2-ckeditor/issues/144
