### ISSUE TITLE
Error: node_modules/ng2-ckeditor/lib/src/ckeditor.component.ngfactory.js is not part of the compilation output

### ISSUE THREAD

**Issue by jhollinger** [chymz/ng2-ckeditor#179]
Version **1.1.13**. This breaks our build using a recent version of `ng-cli`. Sounds like it might be related to https://github.com/angular/angular-cli/issues/8284#issuecomment-341417325, but I can't be sure. Spent hours trying to find a workaround, but have made no progress.

**Comment by kzimny** [comment]
Seems to be a compilation issue within your project. I'm working with [angular-seed](https://github.com/mgechev/angular-seed) starter project and had trouble after update of some components. Finally I solved the problem deleted all .js and .map files compiled within my src folder. My advice may be completely wrong, but you can try. Do you compile with AOT or JIT option?

**Comment by jhollinger** [comment]
We don't have any compiled `.js` or `.map` files under src. We've even blown away the entire checkout and re-cloned to no avail. I've tried with `--aot` and without.

**Comment by kzimny** [comment]
Did you try to create a new "Hello world" project from scratch with ng2-ckeditor only? Do you get the same compilation problem? A little more info would be nice.

**Comment by jhollinger** [comment]
Will do. Got 3 or 4 major projects at once, so may be a bit. :)

**Comment by mingtaocao** [comment]
ERROR in ./node_modules/_ng2-ckeditor@1.1.14@ng2-ckeditor/lib/src/ckeditor.component.ngfactory.js
Module build failed: Error: E:\partycons\node_modules\_ng2-ckeditor@1.1.14@ng2-ckeditor\lib\src\ckeditor.component.ngfactory.js is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile

**Comment by kzimny** [comment]
Update your Node.js, install the latest version of angular-cli and try with the latest version of ng2-ckeditor. How do you link to ng2-ckeditor component in your project? Can you provide an example? You are wrong if you expect a problem solution without providing any code example. Without further information nobody will be able to help you. Especially for @jhollinger and @mingtaocao

**Comment by mingtaocao** [comment]
Ok, I'll try. Thank you. @kzimny

**Comment by jhollinger** [comment]
Going to call this resolved. Eventually it started working. Couldn't tie it to a specific event, but probably b/c we Updated All The Things.
