### ISSUE TITLE
 CKEDITOR is not defined

### ISSUE THREAD

**Issue by ringodotnl** [chymz/ng2-ckeditor#18]
Error: CKEDITOR is not defined
    at CKEditor.ckeditorInit (http://localhost:3000/vendor.bundle.js:47779:13)
    at CKEditor.ngAfterViewInit (http://localhost:3000/vendor.bundle.js:47748:13)

line 47779:
 if (!CKEDITOR) {
	        console.error('Please include CKEditor in your page');
	        return;
	      }

implementation:
 directives: [
    XLarge, CKEditor
  ],

in the template:
<ckeditor
                [(ngModel)]="ckeditorContent"
                [config]="{uiColor: '#99000'}"
                debounce="500">
            </ckeditor>

**Comment by chymz** [comment]
Did you include ckeditor library (https://github.com/chymz/ng2-cli-ckeditor-sample/blob/master/src/index.html#L17) ?
