### ISSUE TITLE
ERROR TypeError: Object doesn't support property or method 'contains'

### ISSUE THREAD

**Issue by vortaxg** [chymz/ng2-ckeditor#180]
Hi guys,

I have a project on Angular 5 and use ng2-ckeditor **Version 1.1.13.**
I've got an error in IE 11;
**ERROR TypeError: Object doesn't support property or method 'contains'**
It complains that document.contains doesn't exist.

I've found a solution all that needs to change is:
 ` if (this.instance || !document.contains(this.host.nativeElement)) {
    return;
  }`
 to
` if (this.instance || !document.body.contains(this.host.nativeElement)) {
   return;
  }`
 **in ckeditor.component.js**

**Comment by Ranjan-siva0704** [comment]
Hi guys,
When will the enhancement code be committed in the repo? In need of the editor in IE.  Awaiting the commit!!

**Comment by SergeyPlatonov** [comment]
Hi guys!
I have a similar problem. I'm looking forward to fixing

**Comment by kzimny** [comment]
I can reproduce the error in IE 11:
![image](https://user-images.githubusercontent.com/12007674/34387518-ec0c9c26-eb2e-11e7-915a-6593e76ae25e.png)

**Comment by muziekklas** [comment]
We got the same issue. Is a blocking issue to us to use this.
@chymz Got an ETA when this is fixed?

**Comment by muziekklas** [comment]
@chymz  Possible fix could be:

I tested this fix and all that needs to change is:

if (!document.contains(target)) {
    return;
}
to
if (!document.body.contains(target)) {
    return;
}
Source https://github.com/skatejs/skatejs/issues/153

**Comment by vortaxg** [comment]
http://take.ms/sy5oa

**Comment by muziekklas** [comment]
@chymz Made a PR which SHOULD fix this issue. Can you validate it?

**Comment by chymz** [comment]
1.1.14 published, thanks @muziekklas
