### ISSUE TITLE
ERROR in Metadata version mismatch for module 

### ISSUE THREAD

**Issue by yogesh-sadhokar** [chymz/ng2-ckeditor#181]
ERROR in Metadata version mismatch for module /home/deepak/TAMSWorkspace/PaladionTAMSUI/angular/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts, found version 4, expected 3, resolving symbol AppModule in /home/deepak/TAMSWorkspace/PaladionTAMSUI/angular/src/app/app.module.ts, resolving symbol AppModule in /home/deepak/TAMSWorkspace/PaladionTAMSUI/angular/src/app/app.module.ts

**Comment by yogesh-sadhokar** [comment]
{
  "name": "demo",
  "version": "1.0.0",
  "description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 1.3.2.",
  "main": "karma.conf.js",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "author": "",
  "license": "ISC",
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@cedx/ngx-webstorage": "^1.2.0",
    "angular2-cool-storage": "^3.1.0",
    "angular2-focus": "^1.1.0",
    "ckeditor": "^4.7.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "ng2-ckeditor": "^1.1.9",
    "ng2-toastr": "^4.1.2",
    "ng2-toasty": "^4.0.3",
    "ngx-perfect-scrollbar": "^4.6.3",
    "rxjs": "^5.4.2",
    "tinymce": "^4.6.4",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.1.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}

**Comment by yogesh-sadhokar** [comment]
Need a quik solution for this. without upgrading to angular 5

**Comment by yogesh-sadhokar** [comment]
"dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/cdk": "^2.0.0-beta.10",
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.2.4",
    "@angular/material": "^2.0.0-beta.10",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@cedx/ngx-webstorage": "^1.2.0",
    "angular2-cool-storage": "^3.1.0",
    "angular2-focus": "^1.1.0",
    "ckeditor": "^4.7.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "ng2-ckeditor": "^1.1.9",
    "ng2-toastr": "^4.1.2",
    "ng2-toasty": "^4.0.3",
    "ngx-perfect-scrollbar": "^4.6.3",
    "rxjs": "^5.4.2",
    "tinymce": "^4.6.4",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.14"
  }

**Comment by yogesh-sadhokar** [comment]
"dependencies": {
    "angular/animations": "^4.3.6",
    "angular/cdk": "^2.0.0-beta.10",
    "angular/common": "^4.4.6",
    "angular/compiler": "^4.2.4",
    "angular/core": "^4.4.6",
    "angular/forms": "^4.4.6",
    "angular/http": "^4.2.4",
    "angular/material": "^2.0.0-beta.10",
    "angular/platform-browser": "^4.2.4",
    "angular/platform-browser-dynamic": "^4.2.4",
    "angular/router": "^4.2.4",
    "cedx/ngx-webstorage": "^1.2.0",
    "angular2-cool-storage": "^3.1.0",
    "angular2-focus": "^1.1.0",
    "ckeditor": "^4.7.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "jquery": "^3.2.1",
    "lodash": "^4.17.4",
    "ng2-ckeditor": "^1.1.9",
    "ng2-toastr": "^4.1.2",
    "ng2-toasty": "^4.0.3",
    "ngx-perfect-scrollbar": "^4.6.3",
    "rxjs": "^5.4.2",
    "tinymce": "^4.6.4",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.14"
  }

**Comment by kzimny** [comment]
Install version 1.1.9 of ng2-ckeditor. Yo can use version 1.1.13 with angular 5

**Comment by yogesh-sadhokar** [comment]
Installed  "ng2-ckeditor": "^1.1.5" version and also downgraded some other dependencies, that resoved the issue
