### ISSUE TITLE
[question] how to hide button link info in lower left

### ISSUE THREAD

**Issue by xxNoxiouSxx** [chymz/ng2-ckeditor#182]
I am hoping someone may know the answer to this. not truly an issue just a question.

when I hover over the buttons they show link info in lower left.

- javascript:void('source')
- etc

I have attempted the following config flags but no luck. 
- Is there a config option to hide link info?
```
linkShowAdvancedTab: false,
linkShowTargetTab: false,
linkJavaScriptLinksAllowed: false,
showDisplayTextForElement: false,
```

**Comment by kzimny** [comment]
Please ask ckeditor questions in ckeditor forum. I found similar question with answer [here](https://ckeditor.com/old//forums/Plugins/Link-plugin-hide-tabs-Target-and-Advanced) 

```js
                this.ckeConfig = {
                    height: 500,
                    language: "en",
                    allowedContent: true,
                    linkShowAdvancedTab: false,
                    linkShowTargetTab: false,
                    linkJavaScriptLinksAllowed: false,
                    showDisplayTextForElement: false,
                    extraPlugins: "divarea"
                };
```
This solution doesn't work in Chrome.

**Comment by xxNoxiouSxx** [comment]
For anyone who comes across this looking for the same solution; here is mine for chrome.

add this to your CKEDITOR config.
```
on: {
        'contentDom': () => {
          var element = document.getElementsByClassName('cke_button')
          for (var i = 0; i < element.length; i++) {
            element[i].addEventListener('mouseover', (e)=>{
              e['toElement'].removeAttribute('href')
            })
          }
        }
      },
```
