### ISSUE TITLE
use ng2-ckeditor

### ISSUE THREAD

**Issue by nioperas06** [chymz/ng2-ckeditor#187]
Please do not mark this question as replecated because none of the available solution on stackoverflow has resolve my problem, I am trying to integrate ng2-ckeditor ckeditor to an existing angular 4 project. I try to follow the steps described.

I procceed as follow

referenced the follwoing js files in my index file

1 <script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
2 <script src="config.js"></script>
import module in my app.module.ts

import{CKEditorModule} from "ng2-ckeditor"; 
.
.
.;

imports: [
    BrowserModule,
    AppRoutingModule,
  .
  .
  .,
    CKEditorModule,
  ],
But when I try to use the ckeditor code in my app

<ckeditor [(ngModel)]="description" > </ckeditor>
it was marked as unkown element and I get The following text hint

[Angular]
'ckeditor' is not a known element:
1. If 'ckeditor' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
when I run ng serve command, the compilation succeeded but nothing is shown and I get the following Console error

Uncaught Error: Template parse errors:
'ckeditor' is not a known element:
1. If 'ckeditor' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("N' | translate:lang }}</span>
            <div formControlName="description" [froalaEditor] ></div>
[ERROR ->]<ckeditor></ckeditor>
          </mat-card-content>
        </mat-card>
any help would be appreciated

**Comment by kzimny** [comment]
Import FormsModule into app.module.ts class:

```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import {FormsModule} from '@angular/forms';

import { AppComponent } from './app.component';
import {CKEditorModule} from 'ng2-ckeditor';



@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CKEditorModule,
    FormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

It should solve your problem.

**Comment by Larzsify** [comment]
I also have this issue.
FormsModule is imported into app.module.ts

**Comment by ZenkriRym** [comment]
The same issue , in other component it work properly but not in the component that i ' m using now
