### ISSUE TITLE
[Bug/Missing polyfill] IE11 not working

### ISSUE THREAD

**Issue by EndarValuk** [chymz/ng2-ckeditor#188]
Good day!
Found a little bug when tried to use component with IE11 browser.
Init failed on that line. 
https://github.com/chymz/ng2-ckeditor/blob/9299de14d40e1793ec1ce49ee959cebc87727f3a/src/ckeditor.component.ts#L133

document.contains failed. IE doesn’t support it so far. 
so we need a polyfill or check(IE supports Document.Body.contains) for method existance.

Example polyfill:
> Document.prototype.contains = function(el) {
>         while(el = el.parentNode) {
>           if (el === this) return true;
>         }
>         return false;
> }

**Comment by kzimny** [comment]
Please look at #180
