### ISSUE TITLE
TypeError: Cannot read property 'getComputedStyle' of undefined

### ISSUE THREAD

**Issue by masoudline** [chymz/ng2-ckeditor#191]
when I close or navigate from one page that has a form to another page this error shows:
TypeError: Cannot read property 'getComputedStyle' of undefined

how can i resolve this problem? @chymz

**Comment by kzimny** [comment]
Can you provide your ng2-ckeditor configuration please and describe your system environment (browser, IDE, angular, and so on). How do you load the ng2-ckeditor component in html and how is the data binding configured?

**Comment by masoudline** [comment]
my data like below:
browser chrome Version 63.0.3239.132 (Official Build) (64-bit)
angular 4.0.0
IDE: phpstorm
and configuration file:
```
this.CkeditorConfig =
      {
        contentsLangDirection : 'rtl',
        removeButtons: 'Underline,Subscript,Superscript,SpecialChar,Source,Save,NewPage,DocProps,Preview,Print,' +
        'Templates,document,Cut,Copy,Paste,PasteText,PasteFromWord,Undo,Redo,Find,Replace,SelectAll,Scayt,Form,' +
        'Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,Strike,RemoveFormat,NumberedList,' +
        'BulletedList,Outdent,Indent,Blockquote,CreateDiv,JustifyLeft,JustifyCenter,JustifyRight,JustifyBlock,Anchor,' +
        'CreatePlaceholder,Image,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,InsertPre,Styles,Format,' +
        'Font,FontSize,TextColor,BGColor,UIColor,Maximize,ShowBlocks,MediaEmbed,About,Language',
      }
```

**Comment by kzimny** [comment]
The issue definitely doesn't come from ng2-ckeditor but rather from ckeditor and another plugin you are using elsewhere in your application. Please look at the similar question at stackoverflow [website](https://stackoverflow.com/questions/24178904/cannot-read-property-getcomputedstyle-of-undefined-ckeditor). I'm not familiar with react, but maybe you need to update your [react-draggable](https://github.com/georgeOsdDev/react-draggable-tab/issues/75)?

**Comment by masoudline** [comment]
I am using angular 4 and not react. I can't solve this problem. anybody can help me?

**Comment by kzimny** [comment]
Do you experience the same problem with other browsers? Maybe you can try to setup a brand new project with minimal configuration and add the ng2-ckeditor component. Please exclude all other components you are using in your master project. Does the routing change when you navigate from one page to another? I hope you are not expecting a solution without doing some tests on your side...

**Comment by fmmajd** [comment]
i have the same problem. i had a big project and had the problem, then started a new project and as soon as i added ckeditor, this happened.

**Comment by kzimny** [comment]
Unfortunately I can not work miracles without code example. Could you prepare a plunker or a **working project** and upload it somewhere? I can't spend hours looking for your solution just for fun. Working example would help.

**Comment by fmmajd** [comment]
here is the cdn url i use:
`<script src="//cdn.ckeditor.com/4.8.0/full-all/ckeditor.js"></script>`

and here is when I use the editor:
`<ckeditor
  [(ngModel)]="value"
  [config]="config"
  [readonly]="false"
  (change)="onChange($event)"
  debounce="500">
</ckeditor>
`

here is the config:
`config = {
    rtl: true,
    contentsLanguage: 'fa',
    defaultLanguage: 'fa',
    language: 'fa',
    extraPlugins: 'uploadimage',
    imageUploadUrl: api.file_manager.imageUploadUrl,
    skinName: 'moono-lisa',
    contentsLangDirection: 'rtl',
    dialog_buttonsOrder: 'rtl',
    toolbar: [[
      'PasteFromWord', 'Undo', 'Redo', 'Bold', 'Italic', 'Underline', 'RemoveFormat', 'NumberedList', 'BulletedList',
      'Indent', 'Outdent', 'JustifyRight', 'JustifyLeft', 'JustifyCenter', 'JustifyBlock', 'BidiRtl', 'BidiLtr', 'Link', 'Unlink'
    ]]
  };`

I have used your library in 3 projects, and in all of them, i have had this problem.  it's not causing any problems in the app performance, but really clutters the console, and also there seems to be a big problem underneath.

I tried to totally destroy the element in route event: NavigationEnd, but it didn't work. whenever I'm in a page with ckeditor and browse to ANY different page, this warning happens.

**Comment by kzimny** [comment]
Somethings seems to be definitely wrong in all your projects. I've prepared a small [solution](https://znf.ch/download/majd.zip) demonstrated how ng2-ckeditor work. You can navigate between pages without any warnings or errors. You need to install [angular/cli](https://angular.io/guide/quickstart) first. Then download and unzip all files to directory of your choice. Run ng serve --open from command line. You should be able to navigate between pages without any errors.

**Comment by masoudline** [comment]
@fmmajd Hi my friend
I solved this problem by adding below code to ngOnInit():
```
    declare var $ // at top of component 

    $('#CKeditor').empty(); // add this line to ngOnInit()
```
where CKeditor is an id that declare in 
```
<ckeditor id="CKeditor"></ckeditor>
```
hope this helps

**Comment by kzimny** [comment]
This is an untested proposal which has been deleted from this thread for unexplained reason. 

```ts
import { Component, OnInit, ViewChild } from '@angular/core';
declare var $; // <<< ============== add this line

@Component({
  template: `
  <ckeditor
    [(ngModel)]="content"
    #myckeditor
id="CKeditor" <<< ============== add this line
    [config]="ckeConfig"
    debounce="500">
  </ckeditor>
  `
})
export class MyEditorComponent implements OnInit {
  ckeConfig: any;
  @ViewChild("myckeditor") ckeditor: any;
  content: string;

  constructor() {
    this.content = `<p>My html content</p>`;
  }

  ngOnInit() {
$('#CKeditor').empty(); // <<< ============== add this line
    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: "divarea"
    };
  }
}

```

Does it help for someone having trouble with the error: Cannot read property 'getComputedStyle' of undefined?

**Comment by masoudline** [comment]
this doesn't solve any problem! I have the issue still

**Comment by kzimny** [comment]
@masoudline: it does not make sense to me. Please keep in mind that this is not a bug in ng2-ckeditor component. Therefore I've prepared a working project that demonstrate how to use ng2-ckeditor with navigation between pages. The next step is to follow the example and add another modules or functions from your project to find out what cause the issue on your side. Did you try to follow the stackoverflow [thread](https://stackoverflow.com/questions/24178904/cannot-read-property-getcomputedstyle-of-undefined-ckeditor) and looked for ckeditor answers?

**Comment by fmmajd** [comment]
is it possible that the problem is with RTL languages? I'm saying it because of two reasons:
* this line of error
`at $.getDirection (ckeditor.js:119)`
* masoudline seems like an Iranian name, so I'm guessing he is using RTL too. :)

also, it makes sense if the problem is with RTL. because most of the people do not use it, there are not lots of issues like this.

**Comment by kzimny** [comment]
Maybe you're right, I don't know. But before we investigate the problem in suggested RTL direction I would ask you whether you hide and show the ng2-ckeditor component on your page for some reason. Would you please read the following [thread ](https://github.com/chymz/ng2-ckeditor/issues/133) and let me know whether the ng2-ckeditor component is always set to visible?

**Comment by KSayed91** [comment]
I think using [divarea](https://ckeditor.com/cke4/addon/divarea) plugin will solve the problem.

add it's reference to it in index.html 
`<script src="http://cdn.ckeditor.com/4.5.11/full-all/plugins/divarea/plugin.js"></script>`

then add 'extraPlugins' to config:
`<ckeditor [(ngModel)]="content" [config]="{extraPlugins: 'divarea'}"></ckeditor>`


and regarding 'readOnly' it's preferred to use in in config also:
`<ckeditor [(ngModel)]="content" [config]="{readOnly: 'true'}"></ckeditor>`

**Comment by kzimny** [comment]
@masoudline and @fmmajd can the issue be closed? Was the comment from @KSayed91 helpful?

**Comment by masoudline** [comment]
@kzimny  yes.
@KSayed91 Thanks for your help

**Comment by kzimny** [comment]
@KSayed91 thank you!
