### ISSUE TITLE
CKeditor 4.8.0 - unable to view content

### ISSUE THREAD

**Issue by pbapan** [chymz/ng2-ckeditor#192]
Hi im referring to below plnkr

https://embed.plnkr.co/hnB0R3/
with 4.8.0 ckeditor bundle.

the issue I have is when I set the content, it doesn't display in editor.

@component({
selector: 'ckeditorangularcomponent',
template: <ckeditor [(ngModel)]="content" [config]="ckEditorConfig" debounce="500"> </ckeditor>,
})
export class CKEditorAngularComponent {
private content: string;
private height: number;
private width: any;
constructor() {
this.content = <p>Greetings from CKEditor...</p>;
}

in browser when I view the source I can see "Greetings from CKEditor..." but it is not visible in editor. did I do anything wrong.

And aslo if you can add some info on below post that would be great
https://stackoverflow.com/questions/48332068/ckeditor-wordcount-unable-to-find-in-cdn

**Comment by pbapan** [comment]
when I use below extraplugins, ckeditor doesn't display the content. Any suggestions
ckEditorConfig: {} =
    {
        "extraPlugins": 'wordcount,notification,htmlwriter,undo'
}

**Comment by pbapan** [comment]
found this related issue
https://github.com/chymz/ng2-ckeditor/issues/9

**Comment by kzimny** [comment]
for extra plugins please see the following [description](https://github.com/chymz/ng2-ckeditor/issues/159)
Have you solved the first problem? If not try to add extraPlugins: "divarea" to the config:
``
                this.ckeConfig = {
                    height: 500,
                    language: "en",
                    allowedContent: true,
                    extraPlugins: "divarea"
                };
``

**Comment by pbapan** [comment]
Yes I added, below is the code

**Component.ts**
import { Component } from '@angular/core';

@Component({
    selector: 'ckeditorangularcomponent',
    template: `
    <ckeditor [(ngModel)]="content"  [readonly]="false" id="editorHeadingText" name="editorHeadingText" rows=10 cols=90 [config]="ckEditorConfig" debounce="5000">
    </ckeditor>
  `,
})
export class CKEditorAngularComponent {
    private content: string;
    private height: number;
    private width: any;
    constructor() {
        this.content = `<p>Greetings from CKEditor...</p>`;
        //this.height = 500;
       // this.width = '60%';
        //  [height]="height" [width]="width"
    }
    ckEditorConfig: {} =
    {
        height: 200, // this.height,
        width: '80%', //this.width,
        allowedContent: true,
        toolbar :[
            { name: 'document', items: ['Source', '-', 'Print'] }],
        "uiColor": "#a4a4a4",
        "extraPlugins": 'divarea,wordcount,notification,htmlwriter,undo',

**Index.html**
loading ckeditor.js from local instead of CDN and in my bundle I have div area plugin selected.
    <script src="../lib/ckeditor/ckeditor.js"></script>  
  
    <script src="../node_modules/core-js/client/shim.min.js"></script>
    <script src="../node_modules/zone.js/dist/zone.js"></script>
    <script src="../node_modules/reflect-metadata/Reflect.js"></script>
    <script src="../node_modules/systemjs/dist/system.src.js"></script>
    <script src="../systemjs.config.js"></script>

**Comment by pbapan** [comment]
for above comment, to add more, to load extraPlugins there are 2 ways,
1. if you download custom bundle from ckbuilder with extraplugins all you need is include below line:
config.extraPlugins = 'divarea,wordcount,notification';

2. in case if you are loading ckeditor.js from CDN then you need explicityly add extraplugins like below
  //CKEDITOR.plugins.addExternal('wordcount', '/lib/ckeditor/plugins/wordcount/', 'plugin.js');
config.extraPlugins = 'divarea,wordcount,notification';

correct me if I'm wrong

**Comment by kzimny** [comment]
Your code example looks a little bit ugly like a spaghetti code ... Try with ngOnInit():

```ts
@component({
selector: 'ckeditorangularcomponent',
template: <ckeditor [(ngModel)]="content" #myckeditor [config]="ckeConfig" debounce="500"> </ckeditor>,
})
export class TextEditorComponent implements OnInit {

ckeConfig: any;
@ViewChild("myckeditor") ckeditor: any;

  constructor(  ) { }

  ngOnInit() {
                this.ckeConfig = {
                    allowedContent: true,
                    extraPlugins: "divarea"
                }; 
  }
  ngOnInit() {
                this.ckeConfig = {
                    allowedContent: true,
                    extraPlugins: "divarea"
                }; 
  }
}
```

Your goal is use ckeditor source completely offline, right? You have to download the source code from [here ](https://ckeditor.com/ckeditor-4/download/) and set the path to the ckeditor config.js file in index.html file as you did 
```js
<script src="../lib/ckeditor/ckeditor.js"></script>
```
In the next step you have to register the plugins. How do register them?

**Comment by pbapan** [comment]
it worked :), new to angular :)
With CK bundle https://ckeditor.com/ckeditor-4/download/ .... I can download extraPlaugins with will add all needed dependent plugins and I can simply register like below
config.extraPlugins = 'divarea,wordcount,notification';
