### ISSUE TITLE
Paste Event Not Firing on Drop

### ISSUE THREAD

**Issue by alukard13** [chymz/ng2-ckeditor#197]
Paste event should be fired on drop since 4.5 but its not being fired.

https://docs.ckeditor.com/ckeditor4/latest/guide/dev_clipboard.html#the-paste-event

**Comment by kzimny** [comment]
In the next release 1.2.0 #194 you will find a new event (editorChange)="onEditorChange($event)" . Please look at the commit #141. The return value is the event itself, you should be able to get the [name](https://github.com/chymz/ng2-ckeditor#sample) in (editorChange)="onEditorChange($event)":
```ts
    onEditorChange($event: any): void {
        
    }
```

**Comment by alukard13** [comment]
I'm not sure if #141  is the solution to my problem. I want prevent the text being copied when someone drop a url to a ckeditor instance. At the moment I 'm removing the string after the drop event but this dont work properly if someone drops html content (for example an embeded twitter).

As you can see in the Ckeditor documentation the recommened place to make this changes (or prevent them) is the paste event.

**Comment by kzimny** [comment]
Why are you not sure? You can do exactly the same as recommended in the documentation:

```ts
    onEditorChange($event: any): void {
        if ($event.name === 'paste') {
            $event.data.dataValue = $event.data.dataValue.replace('/gadzooks/gi', 'g******s');
            // maybe better
            this.ckeditor.instance.setData($event.data.dataValue.replace('/gadzooks/gi', 'g******s'));
        }
    }
```
You are listening to ckeditor event, if event is of type paste do your stuff.

**Comment by alukard13** [comment]
Thank you! Now is very clear!!!

One last (and angular noob) question . Its possible to use 1.2.0 with angular 2?

**Comment by kzimny** [comment]
When you can use the latest release 1.1.4 with angular2, you will be able to use the next version. Please let us know if the solution work.

**Comment by alukard13** [comment]
I made a workaround but I'll try 1.2.0 to check if this is working properly !!

/**********WORKAROUND***********/
private onPasteCkeditorListener = function(event){
	if(event.data.method == "drop"){
		if(event.data.dataValue.indexOf("http://") >= 0 ||event.data.dataValue.indexOf("https://") >= 0){
			event.data.dataValue = "";
		}
	}
}

let CKEDITOR = window["CKEDITOR"];
for (var instanceName in CKEDITOR.instances) { 
	CKEDITOR.instances[instanceName].removeListener('paste', this.onPasteCkeditorListener);
	CKEDITOR.instances[instanceName].on('paste', this.onPasteCkeditorListener);
}

**Comment by kzimny** [comment]
Is not all the best way, but maybe it wold help.
```ts
  registered: boolean = false;

  onEditorChange($event: any): void {
    if (!this.registered) {
      this.registered = true;
      $event.editor.document.on('paste', (evt) => { this.replaceFunction(evt) });
      $event.editor.document.on('drop', (evt) => { this.replaceFunction(evt) });
    }
  }
  replaceFunction($evt: any) {
    console.log($evt.data.getTarget().outerHTML);
  }
```

**Comment by chymz** [comment]
Events added in 1.2.1
