### ISSUE TITLE
Unexpected module 'CKEditorModule' in Angular 5 project

### ISSUE THREAD

**Issue by degrootsde** [chymz/ng2-ckeditor#199]
I added the module to an Angular 5 Cli project. When building for production (ng build --prod) it returns:
ERROR in Error: Unexpected module 'CKEditorModule in E:/[myapplicationlocation]/node_modules/ng2-ckeditor/lib/src/ckeditor.module.d.ts' declared by the module 'AppModule in E:/[myapplicationlocation]/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

Is this a known issue? My configuration is:

Angular CLI: 1.6.3
Node: 8.2.1
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.34
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.10.0

**Comment by kzimny** [comment]
I will give you feedback next week. Sorry.

**Comment by kzimny** [comment]
Not a bug in ng2-ckeditor. Project compile with ng build --prod option without errors.
