### ISSUE TITLE
Webpack build error

### ISSUE THREAD

**Issue by ferredel** [chymz/ng2-ckeditor#2]
Hi.

When I try to build for prod my project (based on angular2-webpack-starter) 

I have this error.
 
```
90% optimize assetsError in bail mode: [default] 
[...]/node_modules/ng2-ckeditor/CKEditor.d.ts:15:11 
Generic type 'EventEmitter<T>' requires 1 type argument(s).

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:prod"
```

Just reporting...

Have a nice day! :)

**Comment by chymz** [comment]
Sorry i don't use webpack, but maybe this pull request (#1) fix your problem ?
Thanks !

Details here : https://github.com/chymz/ng2-ckeditor/pull/1/commits/900e70f08ddcabafa4fb8239ecf54e4a4b6da6de

**Comment by ferredel** [comment]
@chymz Yay, that worked :)
