### ISSUE TITLE
when  the first ,the data  can't  render in the tab,then click another data,and return the first data,the data  render

### ISSUE THREAD

**Issue by XiaoZhaoxiaaa** [chymz/ng2-ckeditor#201]

**Comment by kzimny** [comment]
Well, it is difficult to help you without any description. Could you provide more information and your code? Do you have trouble with `<mat-tab-group></mat-tab-group>`? If so look at this closed [issue](https://github.com/chymz/ng2-ckeditor/issues/133).

**Comment by XiaoZhaoxiaaa** [comment]
I sloved  the problem , maybe the ckeditor  component need time to load
