### ISSUE TITLE
Form is dirty on ckeditor load

### ISSUE THREAD

**Issue by KemPavel** [chymz/ng2-ckeditor#205]
Hello, 

Form became dirty after initializing ckeditor value by patchValue({}). I'm using "ng2-ckeditor": "1.1.9".

It would be great if ckeditor could be set by patchValue and didn't mark form as dirty.

**Comment by kzimny** [comment]
Only when you change the value the form should get dirty. Did you try to initialize the ckeditor without setting patchValue({})? Did you try with updateValue()? Please look [here](https://github.com/angular/angular/issues/9768). Provide your code.

**Comment by KemPavel** [comment]
Here is the code 

**HTML**
<div [formGroup]="todoForm">
  <p>is form dirty: {{todoForm.dirty}}</p>
  <ul>
    <li *ngFor="let todo of todos" (click)="selectTodo(todo)">
      <span>{{todo.id}}</span>
      <span>{{todo.description}}</span>
    </li>
  </ul>

  <input type="text" formControlName="id">
  <div>
    <ckeditor
      formControlName="description"
      [config]="{uiColor: '#FFFFFF'}"
      [readonly]="false"
    ></ckeditor>
  </div>
</div>

**component.ts**
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'pk-edit-todo',
  templateUrl: './edit-todo.component.html',
  styleUrls: ['./edit-todo.component.css']
})
export class EditTodoComponent implements OnInit {
  private todoForm: FormGroup;
  private data: Observable<any>;
  private ckeditorContent: string = '<p>Some html</p>';
  private selectedTodo: any;
  private todos: any = [
    {id: 'todo1', description: 'description1'},
    {id: 'todo2', description: 'description2'},
    {id: 'todo3', description: 'description3'},
    {id: 'todo4', description: 'description4'}
  ];
  
  constructor(private formBuilder: FormBuilder) { }

  ngOnInit() {
    this.todoForm = this.formBuilder.group({
      id: ['', Validators.required],
      description: ''
    });

    this.data = new Observable(observer => {
      setTimeout(() => {
        observer.next(this.todos);
      }, 1000);
    });

    let subscription = this.data.subscribe( value => {
      this.selectedTodo = value[0];
      this.selectTodo(this.selectedTodo);
    });
  }

  selectTodo(todo) {
    this.todoForm.patchValue({
      id: todo.id || '',
      description: todo.description || ''
    });
  }
}

**Comment by kzimny** [comment]
If you increase the value of setTimeout you will see that the ```todoForm.dirty``` is initially false. After setTimeout the todoForm.dirty change to true.

```ts
import {Component, OnInit, ViewChild } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-root',
  template: `
    
  <div [formGroup]="todoForm">
    <p>is form dirty: {{todoForm.dirty}}</p>
    <ul>
      <li *ngFor="let todo of todos" (click)="selectTodo(todo)">
        <span>{{todo.id}}</span>
        <span>{{todo.description}}</span>
      </li>
    </ul>
    <input type="text" formControlName="id">
    <div>
      <ckeditor formControlName="description" #myckeditor [config]="ckeConfig" debounce="500"></ckeditor>
    </div>
  </div>
    
    `
})
export class AppComponent implements OnInit {
  title = 'MyEditor';
  ckeConfig: any;
  @ViewChild('myckeditor') ckeditor: any;
  content: string;

  private todoForm: FormGroup;
  private data: Observable<any>;
  private ckeditorContent: string = '<p>Some html</p>';
  private selectedTodo: any;
  private todos: any = [
    {id: 'todo1', description: 'description1'},
    {id: 'todo2', description: 'description2'},
    {id: 'todo3', description: 'description3'},
    {id: 'todo4', description: 'description4'}
  ];


  constructor(private formBuilder: FormBuilder) { }

  ngOnInit() {

    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: 'divarea'
    };

    this.todoForm = this.formBuilder.group({
      id: ['', Validators.required],
      description: ''
    });

    this.data = new Observable(observer => {
      setTimeout(() => {
        observer.next(this.todos);
      }, 5000);
    });

    let subscription = this.data.subscribe( value => {
      this.selectedTodo = value[0];
      this.selectTodo(this.selectedTodo);
    });

    this.todoForm.valueChanges.subscribe( form => {
      for (let key in form) {
        this.selectedTodo[key] = form[key];
      }
    });
  }

  selectTodo(todo) {
    this.selectedTodo = todo;
    this.todoForm.patchValue({
      id: todo.id || '',
      description: todo.description || ''
    });
  }

}
```
I would say, If you have angular specific questions ask them on stackoverflow or other forums. Your question has nothing to do with ng2-ckeditor.

**Comment by KemPavel** [comment]
> If you increase the value of setTimeout you will see that the todoForm.dirty is initially false. After setTimeout the todoForm.dirty change to true.

That's what I'm talking about if I'll set only **id** field after setTimeout **form.dirty will stay false** but if I'll set ckeditor form.dirty became true. Only the ckeditor change the form.dirty value not the other fields. 

Here is an example.

HTML
```
<div [formGroup]="todoForm">

  <p>is form dirty: {{todoForm.dirty}}</p>

  <ul>
    <li *ngFor="let todo of todos" (click)="selectTodo(todo)">
      <span>{{todo.id}}</span>
      <span>{{todo.description}}</span>
    </li>
  </ul>

  <input type="text" formControlName="id">

</div>

```

component.ts

```
import { Component, OnInit } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'pk-edit-todo',
  templateUrl: './edit-todo.component.html',
  styleUrls: ['./edit-todo.component.css']
})
export class EditTodoComponent implements OnInit {
  private todoForm: FormGroup;
  private data: Observable<any>;
  private ckeditorContent: string = '<p>Some html</p>';
  private selectedTodo: any;
  private todos: any = [
    {id: 'todo1', description: 'description1'},
    {id: 'todo2', description: 'description2'},
    {id: 'todo3', description: 'description3'},
    {id: 'todo4', description: 'description4'}
  ];
  
  constructor(private formBuilder: FormBuilder) { }

  ngOnInit() {
    this.todoForm = this.formBuilder.group({
      id: ['', Validators.required]
    });

    this.data = new Observable(observer => {
      setTimeout(() => {
        observer.next(this.todos);
      }, 5000);
    });

    let subscription = this.data.subscribe( value => {
      this.selectedTodo = value[0];
      this.selectTodo(this.selectedTodo);
    });

    this.todoForm.valueChanges.subscribe( form => {
        this.selectedTodo.id = form.id;
    });
  }

  selectTodo(todo) {
    this.selectedTodo = todo;
    this.todoForm.patchValue({
      id: todo.id || ''
    });
  }
}

```

**Comment by kzimny** [comment]
Yes, exact. You don't know why? This because the value change in ckeditor from ```description1``` to ```<p>description1</p>``` and it make the form dirty. Try the following:

```
    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: 'divarea',
      autoParagraph: false,
      enterMode: 2 // CKEDITOR.ENTER_BR
    };
```
That should solve you problem.
