### ISSUE TITLE
(fileUploadResponse) didn't work 

### ISSUE THREAD

**Issue by murdering** [chymz/ng2-ckeditor#208]
I want to overwrite the fileUploadResponse, I see the the sample there is configured the similar function
(fileUploadRequest)="onFileUploadRequest($event)".

I added similar function html, and implement the event in ts file. But the logic is not working, how can I make it working?

Html:
(fileUploadResponse)="onFileUploadRequest($event)"

Ts:
onFileUploadRequest(evt:any) {
   .....
}

**Comment by kzimny** [comment]
The fileUploadResponse event is not implemented. @chymz: could you please add the [fileUploadResponse ](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html#response)event to [1.2.1 version](https://github.com/chymz/ng2-ckeditor/milestones)?
