### ISSUE TITLE
Disable Ckeditor in contenteditable div...!

### ISSUE THREAD

**Issue by zamananjum0** [chymz/ng2-ckeditor#209]
please let me know about how we can disable inline ckeditor in content-editable div..?

**Comment by kzimny** [comment]
There is a [readonly]=[true|false] property you can use to enable/disable the editor. Does this property not work for you?

**Comment by zamananjum0** [comment]
kzimny I'm using two contenteditable div in single page so I want to use these two div for input,one is for ckeditor or another showing emojies and messages input.but this command in work in my scenario.

**Comment by kzimny** [comment]
I found a very good description on [Stackoverflow](https://stackoverflow.com/a/46733219/2795402). It's what you are looking for?

**Comment by kzimny** [comment]
Should the issue be closed?
