### ISSUE TITLE
Angular Universal (SSR) and Ckeditor 4 error

### ISSUE THREAD

**Issue by masoudline** [chymz/ng2-ckeditor#210]
Hi, I used angular universal for server-side rendering and ng2-ckeditor.
when I want to be compress and webpack ng2-ckeditor the belove error show:
```
CKEditor 4.x is missing (http://ckeditor.com/)
```
how can I resolve this problem? I must be used ng2-ckeditor !!

**Comment by kzimny** [comment]
The meassage means that the reference to ckeditor is missing in index.html file. Please look at the documentation in [angular-starter](https://github.com/angular/universal-starter) project. There are two different forms of Server Side Rendering. In prerender mode:

> Renders your application and replaces the dist index.html with a version rendered at the route

Look at the index.html file after compression. I would say that the reference to ckeditor is not there.

**Comment by masoudline** [comment]
this is my index.html file and load perfectly ckeditor but the error shows. i use webpack for convert server.ts to server.js.
```
<!doctype html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <title>My Website</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="/assets/resources/themes/omega/theme.css">
  <link rel="stylesheet" href="/assets/resources/primeng.css">

  <link rel="stylesheet" href="/assets/plugins/lightbox/lightgallery.min.css">
  <link rel="stylesheet" href="/assets/plugins/lightbox/lg-transitions.min.css">
  <script src="https://cdn.ckeditor.com/4.9.1/full/ckeditor.js"></script>
</head>
<body class="rx-home">
  <app-root>
    <div class="wrapper loader"></div>
  </app-root>
</body>

<!-- Bootstrap 3.3.6 -->

</html>

```

**Comment by kzimny** [comment]
For clarification: do you get the error message while compiling your angular project or does the error shows in browser console? If in browser console, does the reference to ckeditor exist in html markup code?

**Comment by kzimny** [comment]
Do you get more error detail or just only ``CKEditor 4.x is missing (http://ckeditor.com/)`` ? I'm not familiar with universal-starter project, but in my opinion the reference to ckeditor is not being injected into index.html file. There is a part res.render() and res.send() in server.ts code. Maybe you could ask your question in universal-starter project: [not-found](https://github.com/angular/universal-starter/issues?utf8=%E2%9C%93&q=not+found)?

**Comment by masoudline** [comment]
The just only CKEditor 4.x is missing (http://ckeditor.com/) and nothing more.
I ask my question. 
what is these message?
i load ckeditor.js in html but the message show again!

**Comment by kzimny** [comment]
The [message ](https://github.com/chymz/ng2-ckeditor/blob/df537ca86d8586ab3d9879719c11988b364c19b9/src/ckeditor.component.ts#L129) comes from ng2-ckeditor when the instance is undefined. Your project is being compiled fine with ``ng build --prod``. I don't believe that something is wrong with ng2-ckeditor. The question ist what happen in universal-starter compilation. Is an additional reference needed somewhere in server.ts or other config file in universal-starter project?

**Comment by cmddavid** [comment]
@kzimny I think it would be useful if the `CKEditorModule` can be used without ckeditor reference, for Universal rendering the ckeditor is not needed. In that case it would be nice if the error would be replaced by a warning. You can use isPlatformBrowser to make it possible: https://angular.io/api/common/isPlatformBrowser

**Comment by kzimny** [comment]
Did you already try that?

**Comment by cmddavid** [comment]
@kzimny not yet, if you want me to try it I will set up development environment for ng2-ckeditor and check if I can make it working.

**Comment by kzimny** [comment]
I don't know who else would be interested in this topic. Of course if you would find the reason and the solution that works it would help other developers having the same problem.

**Comment by cmddavid** [comment]
@kzimny I'm confident I can solve the problem, as I have a lot of experience with Angular Universal. Problem is I don't know how to set up the development environment for this repository. Do you guys have any document or wiki for that? I tried loading up this module as a child module to my test project, but I was unable to serve it properly. Seems webpack doesn't like a symlinked module. Having to build the child module manually over and over is kind of a pain.

**Comment by kzimny** [comment]
On [main page](https://github.com/chymz/ng2-ckeditor#installation) you will find a short installation instruction. In addition you need to import `import {FormsModule} from '@angular/forms';` into your own module. Is it what what you are missing? Ng2-ckeditor works fine with webpack.

**Comment by cmddavid** [comment]
It is working fine when the package has been built, the problem comes when it has not been build yet. For development purposes, I don't want to manually build the child module every time I have made a change. So I added the following to the main module as dependency to the package.json: `"ng2-ckeditor": "file:../ng2-ckeditor"`. This however is giving me the following error: 

``ERROR in ../ng2-ckeditor/ng2-ckeditor.ts
Module build failed: Error: /Users/xxx/Documents/projects/personal/ng2-ckeditor/ng2-ckeditor.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.``

Which I'm able to solve by adding the ng2-ckeditor file to the include property in the tsconfig, but then I get this error on serve / build: `ERROR in No NgModule metadata found for 'AppModule'.`

Any pointers would be appreciated, this is the first time I try to contribute to a project that doesn't work stand alone. So maybe I'm missing something obvious here.

**Comment by kzimny** [comment]
Still an open issue or did you found a solution? It seems that nobody can/want help...

**Comment by kzimny** [comment]
Close the issue?

**Comment by kzimny** [comment]
Nobody wants to investigate and solve the SSR problem. PR's are welcome, the issue can be open again in case someone really wants.
