### ISSUE TITLE
Question about License 

### ISSUE THREAD

**Issue by soleanos** [chymz/ng2-ckeditor#211]
Hi,
I don't know if it's the best place for talk about that but i would like to add this editor to my application, who will have few user and lucrative usage.
I saw on your repo it's in MIT license so i can use it without any restriction but on the CKEditor Website they talk about pay something (https://ckeditor.com/ckeditor-4/pricing/). Can you help me to understand ? Thanks :)

**Comment by kzimny** [comment]
You are lucky if you have a lucrative project. Good luck and give us at least a Star. Look at similar [question ](https://github.com/chymz/ng2-ckeditor/issues/157) in the past.
