### ISSUE TITLE
Pasting href text in editor act as a plane text .

### ISSUE THREAD

**Issue by deep3092** [chymz/ng2-ckeditor#213]
How to enable url text link while pasting on editor.? When I copied some text in which href link on it during pasting that text to my ck-editor consider as a plan text but actually hyperlink was their.Help me how to get link inside my editor.

**Comment by kzimny** [comment]
Paste text with URL links is enable by default. Try on plunker https://embed.plnkr.co/8D0aLbgkeM7rRoA9T2jK/
