### ISSUE TITLE
Error with using divarea plugin combined with material2 number input

### ISSUE THREAD

**Issue by cmddavid** [chymz/ng2-ckeditor#215]
Recently I changed my ng2-ckeditor to use the divarea plugin, as I want to be able to destroy ckeditors when they are no longer needed. Now I have this strange bug in Firefox, that when I try to use a number field, the following error pops up:

`Error: Permission denied to access property "nodeType"`

This is the complete error message:

```
columnNumber: 31
​
fileName: "http://localhost:4200/assets/js/ckeditor/ckeditor.js"
​
lineNumber: 70
​
message: "Permission denied to access property \"nodeType\""
​
stack: "CKEDITOR.dom.node@http://localhost:4200/assets/js/ckeditor/ckeditor.js:70:31\nCKEDITOR.dom.selection@http://localhost:4200/assets/js/ckeditor/ckeditor.js:448:355\nCKEDITOR.editor.prototype.getSelection@http://localhost:4200/assets/js/ckeditor/ckeditor.js:446:45\nq@http://localhost:4200/assets/js/ckeditor/ckeditor.js:684:326\nt@http://localhost:4200/assets/js/ckeditor/ckeditor.js:684:98\nb/</d<@http://localhost:4200/assets/js/ckeditor/ckeditor.js:675:80\n./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2737:17\nonInvokeTask@http://localhost:4200/vendor.js:58949:24\n./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2736:17\n./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.js:2504:28\n./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://localhost:4200/polyfills.js:2812:24\nZoneTask/this.invoke@http://localhost:4200/polyfills.js:2801:28\ntimer@http://localhost:4200/polyfills.js:4370:17\n"
```

If anyone has any idea how to prevent this error, that would be great. Reverting back to the ckeditor without the divarea plugin is no option. As it will cause a different error: https://github.com/chymz/ng2-ckeditor/issues/212.

Also worth noting only the number field is giving problems, other input fields work fine. And the error doesn't pop up in Chrome. It seems to be a Firefox only bug.

# versions used
Angular 6
Material2 6
Latest ng2-ckeditor
Ckeditor 4.9.2 custom build, I also tried other versions but that did not seem to help

**Comment by kzimny** [comment]
Did you try to use the ckeditor with full-all option fron CDN? 
`<script src="//cdn.ckeditor.com/4.8.0/full-all/ckeditor.js"></script>`

**Comment by cmddavid** [comment]
@kzimny I did, it gives the same error:

I also tried 4.7.0 full-all version.

```Error: Permission denied to access property "nodeType"
Stack trace:
CKEDITOR.dom.node@http://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:64:260
CKEDITOR.dom.selection@http://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:425:36
CKEDITOR.editor.prototype.getSelection@http://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:422:238
z@http://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:674:100
C@http://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:673:392
c/</f<@http://cdn.ckeditor.com/4.8.0/full-all/ckeditor.js:664:426
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2737:17
onInvokeTask@http://localhost:4200/vendor.js:58949:24
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://localhost:4200/polyfills.js:2736:17
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://localhost:4200/polyfills.js:2504:28
./node_modules/zone.js/dist/zone.js/</ZoneTask.invokeTask@http://localhost:4200/polyfills.js:2812:24
ZoneTask/this.invoke@http://localhost:4200/polyfills.js:2801:28
timer@http://localhost:4200/polyfills.js:4370:17

**Comment by kzimny** [comment]
The issue seems to be strange because the error doesn't pop-up in Chrome. I don't know who else would be interested in this topic. Of course if you would find the reason and the solution that works it would help other developers having the same problem. I'm not working with material design, that's why I can not help much. As you can [see ](https://stackblitz.com/edit/ng2-ckeditor) the ng2-ckeditor works fine with angular 6.

**Comment by rconn3** [comment]
I'm seeing the same issue using a normal number <input> while using Angular 5. I was able to reproduce it without the Angular wrapper, so it is probably an issue with the plugin:
https://jsfiddle.net/rcconner/yfgLq3e8/

**Comment by cmddavid** [comment]
Thats some very useful information, now we know it doesn't have anything todo with either Angular, Material2 or ng2-ckeditor. But it's a problem with ckeditor itself.

**Comment by rconn3** [comment]
I've created an issue in the ckeditor issue tracker: https://github.com/ckeditor/ckeditor-dev/issues/2216

**Comment by cmddavid** [comment]
Closing this issue as it should be fixed in the `ckeditor` package itself.
