### ISSUE TITLE
copy paste error with forcePasteAsPlainTex not working in windows & firefox 

### ISSUE THREAD

**Issue by andy-dev** [chymz/ng2-ckeditor#218]
Hello,

Copy pasting from word to ckeditor with flag `forcePasteAsPlainText` in firefox not working. 
Microsoft Word in Firefox (version 60.0.2, Windows 7 (64 bit))

Works in other browsers.

**Comment by kzimny** [comment]
This seems to be an ckeditor issue. Did you try to change the setting in index.html file:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<script src="https://cdn.ckeditor.com/4.9.2/full-all/ckeditor.js"></script>
  <script> CKEDITOR.config.forcePasteAsPlainText = true; </script>
</head>
<body>
	<my-app>loading</my-app>
</body>
</html>
```
and in ts file:
```ts
  ngOnInit() {
    this.ckeConfig = {
      allowedContent: false,
      extraPlugins: 'divarea',
      forcePasteAsPlainText: true
    };
  }
```
It should work [https://stackblitz.com/edit/ng2-ckeditor](https://stackblitz.com/edit/ng2-ckeditor)

**Comment by andy-dev** [comment]
Thank you
