### ISSUE TITLE
ng2-ckeditor not found

### ISSUE THREAD

**Issue by cerealexx** [chymz/ng2-ckeditor#22]
I've followed every step but angular doesn't seem to be able to find ckeditor when the app is served... Did I miss something?
GET http://localhost:4200/ng2-ckeditor 404 (Not Found)

**Comment by chymz** [comment]
Do you use systemjs ?

**Comment by cerealexx** [comment]
I've copied the lines from the sample to system-config. Same not found error only the path now is different:
http://localhost:4200/vendor/ng2-ckeditor/lib/CKEditor.js

**Comment by cerealexx** [comment]
I've copied the lines from the sample to system-config. Same not found error only the path now is different:
http://localhost:4200/vendor/ng2-ckeditor/lib/CKEditor.js

**Comment by chymz** [comment]
Which sample ? there are 3 samples in readme...
Can you share your all config file ?

**Comment by cerealexx** [comment]
The cli one.

```
"use strict";
// SystemJS configuration file, see links for more information
// https://github.com/systemjs/systemjs
// https://github.com/systemjs/systemjs/blob/master/docs/config-api.md
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
var map = {
    'ng2-ckeditor': 'vendor/ng2-ckeditor/lib/CKEditor.js'
};
/** User packages configuration. */
var packages = {
    'ng2-ckeditor': {
        format: 'cjs'
    }
};
////////////////////////////////////////////////////////////////////////////////////////////////
/***********************************************************************************************
 * Everything underneath this line is managed by the CLI.
 **********************************************************************************************/
var barrels = [
    // Angular specific barrels.
    '@angular/core',
    '@angular/common',
    '@angular/compiler',
    '@angular/forms',
    '@angular/http',
    '@angular/router',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    // Thirdparty barrels.
    'rxjs',
    // App specific barrels.
    'app',
    'app/shared',
    'app/noticias'
];
var cliSystemConfigPackages = {};
barrels.forEach(function (barrelName) {
    cliSystemConfigPackages[barrelName] = { main: 'index' };
});
// Apply the CLI SystemJS configuration.
System.config({
    map: {
        '@angular': 'vendor/@angular',
        'rxjs': 'vendor/rxjs',
        'main': 'main.js'
    },
    packages: cliSystemConfigPackages
});
// Apply the user's configuration.
System.config({ map: map, packages: packages });
//# sourceMappingURL=system-config.js.map
```

**Comment by chymz** [comment]
Did you update your angular-cli-build.js ? 

https://github.com/chymz/ng2-cli-ckeditor-sample/blob/master/angular-cli-build.js

**Comment by cerealexx** [comment]
Yup...

**Comment by chymz** [comment]
Do you have `dist/vendor/ng2-ckeditor/lib/CKEditor.js` in your project ?

**Comment by cerealexx** [comment]
I copied the dir from the sample and it worked. Thought all the dist stuff was autogenerated but maybe the problem was that I wasn't restarting the ng serve.

Anyway, I found that I need to use formControlName in order for this to work, so I guess I'll have to refactor how I handle all my forms. I was using [(ngModel)] for every textarea and that worked fine until now.

Thanks!
