### ISSUE TITLE
Support for extraPlugins | strinsert 

### ISSUE THREAD

**Issue by rphovley** [chymz/ng2-ckeditor#220]
We are trying to implement a custom dropdown in the toolbar using the following addon.
https://ckeditor.com/cke4/addon/strinsert

We can get it to work by adding 
`declare var CKEDITOR: any`

then configuring it with 
`    CKEDITOR.plugins.addExternal(
      'strinsert',
      '/assets/ckeditor_plugin/',
      'plugin.js'
    )`

and then finally we can actually use it in the variable we bind to `[config]`

`    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: 'strinsert',
      strinsert_strings: shortcodeList
      ]
    }
`

This has a problem though as we are combining approaches and feels like it will break as I would think this is not how this library was intended to be used.

What's the way that ng2-ckeditor is designed to include plugins for ckeditor? Is the way above correct? If it is, testing becomes difficult as  `declare var CKEDITOR: any` doesn't exist when creating the component through karma and so tests related to the component the editor is included on will fail with

`Failed: CKEDITOR is not defined
 ReferenceError: CKEDITOR is not defined
`

**Comment by kzimny** [comment]
Hi, I think you are doing it in the right way. As you can see in the [source code ](https://github.com/chymz/ng2-ckeditor/blob/76c2961526a51c9bf82221e64853f55471a6c4b1/src/ckeditor.component.ts#L20) the ckeditor is declared as CKEDITOR with type of any. There is probably no other declaration way to use an external JavaScript library in angular. As for the question about karma maybe this [topic ](https://github.com/mgechev/angular-seed/issues/1126) wold help.

**Comment by rphovley** [comment]
Gotcha, makes sense.

As for the link, it seems like that is about a global variable naming conflict between two libraries? I just need to be able to make karma know what CKEDITOR is in my tests but haven't found any working solutions yet at this point.

This stackoverflow article is the closest I've found to the issue I'm experiencing

https://stackoverflow.com/questions/41099179/test-component-with-declare-var

I have followed this and even though karma.conf.js is seemingly loading the ckeditor.component.ts by adding it like so 
```
    files: [
      './node_modules/ng2-ckeditor/src/ckeditor.component.ts',
      ...
    ]
```
karma normally gives warnings if your filepath is incorrect so it appears to be loading but the error 
`Failed: CKEDITOR is not defined ReferenceError: CKEDITOR is not defined`
still happens so it doesn't seem to be giving the tests the context it needs to know what the global var is?

**Comment by kzimny** [comment]
Unfortunately, I can not help. No idea how to get karma work with global variable declaration. I leave the question open and hope someone else can help.

**Comment by kzimny** [comment]
@rphovley: did you solve the problem? If yes, please post your solution here for other people trying to solve the same problem.

**Comment by rphovley** [comment]
@kzimny sadly, I was not able to find a solution to the problem. We had to move on due to time constraints on our project

**Comment by kzimny** [comment]
The issue was open for three months, nobody else has answered and the question is no more relevant in your project.

**Comment by sem1colon** [comment]
How to change icon when clicked on the custom toolbar button created by plugin?

**Comment by kzimny** [comment]
if the icon is a part of the plugin you can not
