### ISSUE TITLE
this.ckeditor.instance.setData is not working when ckeditor is defined in ng-template?

### ISSUE THREAD

**Issue by krutika20** [chymz/ng2-ckeditor#222]
Hi i am using angular 4
**mycomponent.html** file
<ng-template #content1 let-c="close" let-c="dismiss" id="emailModel">
 <ckeditor formControlName="description" debounce="500"  #ckeditor (change)="onChangeDescription($event)"></ckeditor>
</ng-template>

**component.module.ts**
import { CKEditorModule } from 'ng2-ckeditor';
@NgModule({
imports: [
CKEditorModule
],
})

**mycomponent.ts**
@ViewChild('ckeditor') ckeditor:any;
this.ckeditor.instance.setData('') // this statement gives an error 

**_Cannot read property 'instance' of undefined_** 
===========================================================
Reply for this as soon as possible

**Comment by kzimny** [comment]
You can not use this.ckeditor.instance outside of a method because at this point instance is always null. Set the data in onInit() or AfterViewInit() method instead.

**Comment by kzimny** [comment]
Instead of set and get data you can use the model variable as shown in [demo ](https://stackblitz.com/edit/ng2-ckeditor?file=src%2Fapp%2Fapp.component.ts) application. When you prefer to use set and get methods the ng2-ckeditor need to be visible in the DOM an the time you access the instance.

**Comment by krutika20** [comment]
but i am not using ngModel, because i am using formControlName, if you want i can send you 3 files.

**Comment by kzimny** [comment]
Prepare a working demo at stackblitz or plunker if it's working again. Please pay attention that [formControl ](https://blog.ninja-squad.com/2018/05/04/what-is-new-angular-6/) will be removed in Angular 7.0

**Comment by jnizet** [comment]
@kzimny that's not what our blog says. It says that *using formControl and ngModel on the same input* is deprecated. That's quite different from saying that formControl is deprecated.

**Comment by kzimny** [comment]
agree

**Comment by asotog** [comment]
have a similar issue, ckeditor is place inside a second tab, on first time, it works, but if go back to first tab and come again to second tab, editor begins throwing errors like 

```
ckeditor.js:formatted:9975 Uncaught TypeError: Cannot read property 'getSelection' of undefined
    at CKEDITOR.dom.selection.getNative (ckeditor.js:formatted:9975)
    at new CKEDITOR.dom.selection (ckeditor.js:formatted:9926)
    at a.CKEDITOR.editor.getSelection (ckeditor.js:formatted:9874)
    at new CKEDITOR.plugins.undo.Image (ckeditor.js:formatted:23807)
    at CKEDITOR.plugins.undo.UndoManager.save (ckeditor.js:formatted:23639)
    at a.<anonymous> (ckeditor.js:formatted:23549)
    at a.m (ckeditor.js:formatted:136)
    at a.<anonymous> (ckeditor.js:formatted:200)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:formatted:244)
    at CKEDITOR.command.exec (ckeditor.js:formatted:20947)```

**Comment by kzimny** [comment]
@asotog : look at issue #133 The solution should help

**Comment by asotog** [comment]
@kzimny thank you... will take a look, i'm using a framework built on top of angular material, don't have much access to tabs component element.

**Comment by kzimny** [comment]
I hope you are not expecting a miracle... Ng2-ckeditor is just a component and it's up to you how you use it.

**Comment by asotog** [comment]
@kzimny yeah no worries, will try to figure it out
