### ISSUE TITLE
Make a mistake in build(angular6)

### ISSUE THREAD

**Issue by zzz** [chymz/ng2-ckeditor#225]
![image](https://user-images.githubusercontent.com/39012698/42019817-a8799820-7ae8-11e8-9b1f-c7ae1cf038d6.png)
What is the reason for this?

**Comment by kzimny** [comment]
strange path ./node_modules/_ng2-ckeditor
By default the ng2-ckeditor package is installed in ./node_modules/ng2-ckeditor
Did you try to uninstall and install the ng2-ckeditor package?

**Comment by lzk1994** [comment]
@kzimny ng serve，This command runs and does not go wrong
![image](https://user-images.githubusercontent.com/39012698/42022041-c4ab9204-7aee-11e8-8de8-7389c5a8fbf5.png)

**Comment by lzk1994** [comment]
@kzimny Thank you very much! I want to ask, where is this configuration? I didn't find this configuration file.
![image](https://user-images.githubusercontent.com/39012698/42024564-1395c032-7af5-11e8-961a-35e5d7131545.png)

**Comment by kzimny** [comment]
Try the following:
```
packages: {
'ng2-ckeditor': {
main: 'lib/ng2-ckeditor',
defaultExtension: 'js'
}
}
```

**Comment by lzk1994** [comment]
I don't know where to paste this code. What is the name of the file? 
![image](https://user-images.githubusercontent.com/39012698/42029366-ded272f2-7b01-11e8-8ace-2a8c18f67c37.png)
Can you tell me the trouble?

**Comment by kzimny** [comment]
If you are not working with commonjs module code generation you don't need to set the path explicitly. I guess you are working with Angular CLI, in this case no additional configuration is needed. Try to setup a new project as follows:

```
ng new myckeditor
cd myckeditor
npm install ng2-ckeditor --save
```

The ng2-ckeditor package should be installed in ./node_modules/ng2-ckeditor folder

**Comment by kzimny** [comment]
No answer.
