### ISSUE TITLE
How to get current cursor position and paste custom text

### ISSUE THREAD

**Issue by andrew123d** [chymz/ng2-ckeditor#227]
Hi, I am looking for information how I can get current cursor position in editor and paste in this place a custom text. I find information that I can get cursor position by:                                                                   
var ranges = editor.getSelection().getRanges();
ranges[0].setStart(element.getFirst(), 0); 

But how I can get variable editor in my Angular4 application.

**Comment by kzimny** [comment]
Would this [answer ](https://github.com/chymz/ng2-ckeditor/issues/149) help? If not you can define a variable of type any as follows:

```ts
import { Component, ViewChild } from '@angular/core';
declare var CKEDITOR: any;

@Component({
  selector: 'my-app',
  template: `<ckeditor #myckeditor debounce="500"></ckeditor>`
})
export class AppComponent {

  @ViewChild('myckeditor') myckeditor:any;

  onSomeAction() {
    console.log(this.myckeditor.instance.getData());
var ranges = CKEDITOR.getSelection().getRanges();
  }

}
```

**Comment by andrew123d** [comment]
kzimny Thank you for your reply. You show me the right way :) and save me a lot of time :)

Only one bug in the code: 
`onSomeAction() {
    console.log(this.myckeditor.instance.getData());
    let ranges = this.myckeditor.instance.getSelection().getRanges()[0];
    console.log(ranges)
  }
`

Thank you again.
