### ISSUE TITLE
Do not want to use "https://cdn.ckeditor.com/4.5.11/full/ckeditor.js">

### ISSUE THREAD

**Issue by siddharthasharma1986** [chymz/ng2-ckeditor#228]
Hi,

I have tried with ckeditor.js file locally. But I got a "404" error for config.js and en.js.They are looking files in different places. 
I have used the files in below order
1) ckEditor.js
2)Config.js
3)en.js
I am using the angular 5 application.I want to use files from locally.
Can you please suggest  me the way to use these files.

**Comment by kzimny** [comment]
If you are working with angular CLI and don't want or can work with CDN try the following:

1. npm install ckeditor => install the latest ckeditor app into node_modules folder
2. add the following to your angular-cli.json apps section:
```
      "assets": [
        "assets",
        "favicon.ico",
        {
          "glob": "**/*", 
          "input": "../node_modules/ckeditor/", 
          "output": "assets/js/ckeditor/", 
          "allowOutsideOutDir": true
        }
      ],
```
3. add the script reference to the index.html file
``` 
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Myckeditor</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="./assets/js/ckeditor/ckeditor.js"></script>
</head>
<body>
  <app-root></app-root>
</body>
</html>
```
4. **don't copy any files** into ./assets/js/ckeditor folder
5. have fun!

**Comment by siddharthasharma1986** [comment]
I am getting the below issue.
Refused to execute script from 'http://localhost:4200/assets/js/ckeditor/ckeditor.js' because its 
MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by kzimny** [comment]
Show your code from .angular-cli.json, index.html, app.module.ts and app.component.ts

**Comment by siddharthasharma1986** [comment]
@kzimny  Thanks :) Problem is with path. As i corrected the path in .angular-cli.json. It starts working .

**Comment by tusharcatalyst** [comment]
@kzimny "allowOutsideOutDir": true 
has been removed in angular 8, what should be used instead?
I am getting 404 error(GET http://localhost:4200/assets/js/ckeditor/ckeditor.js net::ERR_ABORTED 404 (Not Found))

**Comment by tusharcatalyst** [comment]
how the same can be achieved in a webpack project and not an Angular project?

**Comment by pishangujeniya** [comment]
> 1. add the script reference to the index.html file

What if I don't want the js to load at the initial index.html loading, I want the js to load when the component is loaded.
