### ISSUE TITLE
avoiding the change event firing

### ISSUE THREAD

**Issue by alissonssz** [chymz/ng2-ckeditor#232]
Hi friends, 

I have a list of itens, which are children routes.  Every time that I click and load the child route the change event from the ckeditor component is fired. Is there any way to avoid this behavior?

Ps: The ckeditor content model is retrieved from database.

Any help will be very appreciated!

**Comment by alissonssz** [comment]
A solve the problem guys. Thanks!

**Comment by sir-captainmorgan21** [comment]
@alissonssz what did you do to solve this?
