### ISSUE TITLE
How to prevent source mode character encoding 

### ISSUE THREAD

**Issue by helersu** [chymz/ng2-ckeditor#239]
Hi,
ckeditor source mode change the "Ş" "Ö" "Ü" to
like this;

`<p>&Ouml;</p>`

i want to get data like that 

`<p>Ö</p>`

thanks.

**Comment by kzimny** [comment]
Try to set entities: false; in config section:
`    this.ckeConfig = {
      allowedContent: false,
      extraPlugins: 'divarea',
      entities: false
    };`

**Comment by helersu** [comment]
Thnx for help kzimny its work!
