### ISSUE TITLE
How to find the parent of selected element and how to insert node or HTML inside this element.

### ISSUE THREAD

**Issue by andrew123d** [chymz/ng2-ckeditor#242]
I used ckeditor in my Angular 4 application.  In my component I created a few buttons and when the user is click on some of this buttons,  some html must be inserted inside selected element.
For this I need:
1. Get selected element in editor ( get cursor position and get  element )
1-1.  If this element is p, strong, b, or em - get the parent element. 
2. Insert Html or new node with some html - after or before or inside of selected element 

The first task is done, here my code:
`export class ProjectPagesComponent implements OnInit {
  @ViewChild('ckeditor') ckeditor:any;
  constructor() { 
    this.newPagecontentEditor = 'Sample <b>code</b>'
  }
  ngOnInit() {
  }
  insertHtmlInEditor(){
	let editor = this.ckeditor.instance;    
	let selectedElement = editor.getSelection().getStartElement(); // get selected element
  }
}`

And it's working OK!!!
About the task 1-1 I continue looking for information, but at this time with no success. 
About the task 2. Accordingly ckeditor documentation I try to do this:
`insertHtmlInEditor(){
	let editor = this.ckeditor.instance;
    
        let newNode = '<p>Test</p>' 
        let selectedElement = editor.getSelection().getStartElement(); // get selected element
    
       let newElement = this.ckeditor.dom.element.createFromHtml( newNode, editor.document );
       selectedElement.insertElement( newElement );
}`

And I got an error. editor.dom.element not defined. Also I check an object this.ckeditor.instance. There is no object dom or element inside this.ckeditor or inside this.ckeditor.intance thats why I got an error. 
I find object element in this.ckeditor.intance - which has only one method getName(). And it's working ok.  

I am really confused because, I can not find any of methods(functions) in object  this.ckeditor,  which describe in documentation and can't to use them.  

That why, please guys, if you have any ideas how to resolve the task number 1-1 and 2, please help me. I will be very thanksfull.

**Comment by kzimny** [comment]
2. try with:
```js
insertHtmlInEditor(){
    let editor = this.ckeditor.instance;
    let selectedElement = editor.getSelection();
    let newPElement = this.ckeditor.instance.document.createElement('p');
    let p = this.ckeditor.instance.document.createTextNode("Test");
    newPElement.appendChild(p);  
    selectedElement.insertElement( newPElement );
}
```
I didn't test the code, just typed in this html editor. Apologize for any errors ;-) 

1. what about: let selectedElement = editor.getSelection().parentNode; ?

**Comment by andrew123d** [comment]
> 1. try with:
> 
> ```js
> insertHtmlInEditor(){
>     let editor = this.ckeditor.instance;
>     //let selectedElement = editor.getSelection();
>     let newPElement = this.ckeditor.instance.document.createElement('p');
>     let p = this.ckeditor.instance.document.createTextNode("Test");
>     newPElement.appendChild(p);  
>     this.ckeditor.instance.insertElement( newPElement );
> }
> ```
> 
> I didn't test the code, just typed in this html editor. Apologize for any errors ;-)
> 
> 1. what about: let selectedElement = editor.getSelection().parentNode; ?

Thank you Krzysztof Zimny. You are right. Only two part of code must be correct. createText and append - its a correct functions. This code is working for me 👍 :
```js  
    let editor = this.ckeditor.instance;
    let newPElement = this.ckeditor.instance.document.createElement('p');
    let p = this.ckeditor.instance.document.createText('Test');
    newPElement.append(p);  
    this.ckeditor.instance.insertElement( newPElement ); 
```


Thank you again, you save me a lot of time. Resolved :))))))))
