### ISSUE TITLE
How to get a key event type ?

### ISSUE THREAD

**Issue by andrew123d** [chymz/ng2-ckeditor#244]
How can I get the type of a key event (keypress, keyup, keydown etc...)?
This is my code: 
```js
<div id="client-editor-container">
                            <ckeditor #ckeditor
                            [(ngModel)]="newPagecontentEditor"
                            [config]="{uiColor: '#99000', removePlugins: 'magicline'}"
                            [readonly]="false"
                            (change)="onChange($event)"
                            (ready)="onReady($event)"
                            (focus)="onFocus($event)"
                            (blur)="onBlur($event)"
                            (contentDom)="onContentDom($event)"
                            debounce="500">
                          </ckeditor>
                        </div>
`

**Comment by kzimny** [comment]
Have you tried with [setKeystroke](https://github.com/chymz/ng2-ckeditor/issues/200)() or [this](https://github.com/chymz/ng2-ckeditor/issues/39) or [this](https://github.com/chymz/ng2-ckeditor/issues/60)? @andrew123d: try to find the solution you need in the closed issues before ask a new question.

**Comment by andrew123d** [comment]
Sorry, I didn't find this information in closed issues. Thank you for links. Sorry again.
