### ISSUE TITLE
p tag will be added on Model Updates From Component

### ISSUE THREAD

**Issue by miladzare1378** [chymz/ng2-ckeditor#247]
Hi everyone
When a property used as a model is updated (when a sentence is added by this syntax: data += newdata ) a p tag is added.
How can I fix this problem?

(I apologize for my bad English language)

thanks.

**Comment by kzimny** [comment]
Are you looking for a setting to disable auto paragraph? Try to set [enterMode](https://github.com/chymz/ng2-ckeditor/issues/206): 2 in ckeConfig. Does it help?

**Comment by miladzare1378** [comment]
Yes thank you so much, it works......
