### ISSUE TITLE
how can i add a required field ?

### ISSUE THREAD

**Issue by vinodn4** [chymz/ng2-ckeditor#248]
i need ckeditor is a required field .
i am using angular 6 and latest ckeditor

**Comment by kzimny** [comment]
Would the [closed issue](https://github.com/chymz/ng2-ckeditor/issues/205) and the [demo ](https://stackblitz.com/edit/ng2-ckeditor) help?

**Comment by vinodn4** [comment]
@kzimny thanks lot ..you are really grate
