### ISSUE TITLE
How to add words to Spell Check programmatically.

### ISSUE THREAD

**Issue by jiangyh1024** [chymz/ng2-ckeditor#252]
I want to add some custom words which come from server side to Spell Check - Dictionary to allow CKEditor not to check these custom words. How to add words to Spell Check programmatically? I've searched the CKEDITOR documents, but found nothing

**Comment by kzimny** [comment]
There are several spell checker plugins for ckeditor: https://ckeditor.com/cke4/addons/search/plugins/spell
Why don't you ask your question in ckeditor forum? When you have a question about ng2-ckeditor or have an issue with ng2-ckeditor you are in the correct forum. I propose to let your question open for a few weeks and hope for you someone else can help.

**Comment by jiangyh1024** [comment]
I found the solution myself. 
  ```
  this.ckeConfig = {
      // enable real time spell check
      scayt_autoStartup: true,
      // define toolbar item
      toolbar: [
        ['Bold', 'Italic', 'TextColor']
      ]
    };
    const customWords = ['html', 'hahaha', 'ererer'];
    const str = `array<$>${customWords.join(',')}`;
    localStorage.setItem('wsc_user_dictionary', str);
```
just store the custom words seperated by comma to localstorage, and it works.
