### ISSUE TITLE
Always shows black fonts while pasting content

### ISSUE THREAD

**Issue by yudiz-nikhil** [chymz/ng2-ckeditor#254]
I am not sure if this is an issue or I am missing something in the configuration.
when I paste content in the field from some webpage with colored fonts (red, pink....)
it always shows the **black fonts.**

Angular CLI: 6.0.8
Node: 10.4.1
OS: darwin x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                                                  Version
-----------------------------------------------------------
@angular-devkit/architect                    0.6.8
@angular-devkit/build-angular            0.6.8
@angular-devkit/build-optimizer         0.6.8
@angular-devkit/core                           0.6.8
@angular-devkit/schematics               0.6.8
@angular/cli                                          6.0.8
@ngtools/webpack                               6.0.8
@schematics/angular                          0.6.8
@schematics/update                           0.6.8
rxjs                                                         6.3.0
typescript                                              2.7.2
webpack                                               4.8.3

"ng2-ckeditor": "1.2.1",

**Comment by kzimny** [comment]
Are you looking for [document editor](https://ckeditor.com/ckeditor-4/#document)? Documentation can be found [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_example_setups.html#document-editor). Look at [docs-samples](https://github.com/ckeditor/ckeditor-docs-samples/tree/master/editors).
I hope the links helps a little bit.

**Comment by yudiz-nikhil** [comment]
No I want it for blog posting and I want to have HTML tags for it but it's not getting styles

**Comment by kzimny** [comment]
Please keep in mind that this is ng2-ckeditor issue page and not a ck-editor forum. Ng2-ckeditor component is an angular wrapper for ck-editor. I suggest to ask your question in ck-editor forum. However, after a short research in google I found the following [page](https://github.com/ckeditor/ckeditor-dev/issues/984). Why don't you search yourself instead of giving confuse emoji icons? However, I think this configuration should help:

```ts
  ngOnInit() {
    this.ckeConfig = {
      allowedContent: false,
      extraPlugins: 'divarea',
      extraAllowedContent: 'p{color}',
      pasteFilter: null
    };
```

**Comment by yudiz-nikhil** [comment]
` this.ckeConfig = { allowedContent: true, extraPlugins: "divarea", extraAllowedContent: "p{color}", pasteFilter: null };`

its working with this config
