### ISSUE TITLE
Get the editor mode

### ISSUE THREAD

**Issue by pablovb** [chymz/ng2-ckeditor#258]
Hi,

Is it possible to get the editor mode ('source'/'wysiwyg')? How? I tried the "on" event as in:

```
this.myckeditor.on('mode', function() {
     // Code to execute when the user switches editing modes
}
```

but it didn't work.

**Comment by kzimny** [comment]
The mode event is not implemented in ng2-ckeditor. Hovewer, you can add the event as mentioned [here](https://github.com/chymz/ng2-ckeditor/issues/197). Try the following:
```ts
  registered: boolean = false;
  
  onEditorChange($event: any): void {
    console.log($event.name);
    if (!this.registered) {
      this.registered = true;
      $event.editor.on('mode', (evt) => { this.replaceFunction(evt) });
    }
  }

  replaceFunction($evt: any) {
    console.log('mode changed');
  }
```
That should help.

**Comment by pablovb** [comment]
Hi,

When I click on "Source" no event is triggered. It does when clicking on other buttons.

**Comment by kzimny** [comment]
Then listen to event from other button ;-)

**Comment by kzimny** [comment]
try with:

```ts
    updateEditionMode(event: any) {
        this.ngZone.run(() => {
            this.sourceMode = (event.sender.mode === 'source');
        });
    }
```
because the this.myckeditor.instance.on('mode', ...) event is not an angular part.

**Comment by pablovb** [comment]
Nice, it works! :)

Thanks!
