### ISSUE TITLE
Support Video and Audio in editor. 

### ISSUE THREAD

**Issue by shabbir-dhangot** [chymz/ng2-ckeditor#259]
This is feature request for adding audio and video support. Currently adding video tag show your browser not support HTML5 Videos

**Comment by kzimny** [comment]
Maybe you are using an old browser. No problems in my integration:
![image](https://user-images.githubusercontent.com/12007674/47547987-cf39e600-d8f7-11e8-92e0-8a4f22728805.png)

**Comment by shabbir-dhangot** [comment]
I am using ckeditor 4. Is there any setting to enable html 5 video and audio?
My project in angular 6.

**Comment by kzimny** [comment]
Try with the following configuration:
```ts
  ngOnInit() {
    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: 'divarea'
    };
  }
```

**Comment by shabbir-dhangot** [comment]
Thank you @kzimny 
allowedContent: true, Worked for me.
