### ISSUE TITLE
ckeditor required validations not working [rc3]

### ISSUE THREAD

**Issue by parthleo10** [chymz/ng2-ckeditor#26]
I am trying to use required attribute to `<ckeditor [(ngModel)]="abc" required>` tag, but its not working. I am using angular 2 rc3 and ckeditor version 1.0.3. 
Due to some situation atm I can't update my angular to rc4, so if I use ckeditor v 1.0.4/1.0.5 it throw an angular/forms error.
Kindly suggest an solution.

**Comment by chymz** [comment]
Hi,

You can try get sources from this commit https://github.com/chymz/ng2-ckeditor/tree/7646ffcec681f604d7140206527c6541ce3a3766

It's a bad idea to stay with angular rc3 and can't support this version (I don't have time, sorry)

**Comment by parthleo10** [comment]
Thanks for your suggestion! 
So does that mean If I update angular to RC 4 and use ng2-ckeditor v 1.0.5 , validations like "requied" will work ?

**Comment by chymz** [comment]
Yes you can view it on this repo : https://github.com/chymz/ng2-cli-ckeditor-sample/blob/master/src/app/app.component.html
