### ISSUE TITLE
how to allow <i> tags via source 

### ISSUE THREAD

**Issue by deepaksinghrv** [chymz/ng2-ckeditor#263]
hello,
i am trying to add <i> tag inside <a> tag but it replacing these tag with "&bnsp". please help!

trying to add source -
```
 <div >
  <a href="http://google.com"><i class="fa fa-instagram" aria-hidden="true"></i></a>
              </div>
```
but ckeditor replace that code by-
` <div > &bnsp; </div>`

**Comment by kzimny** [comment]
Try with the following config settings:

```ts
  ngOnInit() {
    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: 'divarea',
      extraAllowedContent: 'p(*)[*]{*};div(*)[*]{*};i(*)[*]{*};li(*)[*]{*};ul(*)[*]{*}',
      protectedSource: /<i[^>]*><\/i>/g
    };
  }
```
Search for ckeditor specific questions in other [forums](https://stackoverflow.com/questions/19967092/ckeditor-4-2-2-allowedcontent-true-is-not-working).

**Comment by deepaksinghrv** [comment]
@kzimny thanks men, its working :)
