### ISSUE TITLE
when build angular --prod ,it went wrong

### ISSUE THREAD

**Issue by galileo303** [chymz/ng2-ckeditor#266]
here's the error:
ERROR in ./node_modules/_ng2-ckeditor@1.2.2@ng2-ckeditor/lib/src/ckeditor.component.ngfactory.js
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\work\ng6\portal\node_modules\_ng2-ckeditor@1.2.2@ng2-ckeditor\lib\src\ckeditor.component.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (D:\work\ng6\portal\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:719:23)
    at plugin.done.then (D:\work\ng6\portal\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

and my angular verison is 7.1.4 and angular-cli version 7.1.4
the ng2-ckeditor verison is 1.2.2

**Comment by kzimny** [comment]
The error seems to come from webpack, not from ng2-ckeditor. I currently work with angular-cli version 7.2.1 and the same version of ng2-ckeditor. Can compile my projects with --prod param without any issues. Try the following. Create a blank new angular project, then install ng2-ckeditor and compile your new project it with --prod parameter. Do you get any errors?

**Comment by galileo303** [comment]
> The error seems to come from webpack, not from ng2-ckeditor. I currently work with angular-cli version 7.2.1 and the same version of ng2-ckeditor. Can compile my projects with --prod param without any issues. Try the following. Create a blank new angular project, then install ng2-ckeditor and compile your new project it with --prod parameter. Do you get any errors?

whoops~~~when I create a blank new angular project  ,  it's  oka...thx
