### ISSUE TITLE
ckeditor5 does not render styles on the Editor

### ISSUE THREAD

**Issue by lidibe** [chymz/ng2-ckeditor#268]
Dear Team,

I'm using ckeditor 5 (classic) with Angular 6. The editor is placed under a mat-tab. However, the actions to the editor menu items "Bold", "Italic" does not have any effect on the display even though the console the text with "strong" or "i" tags.

`<p><strong>example</strong></p>`

image link [https://pasteboard.co/I9wudb2.png](https://pasteboard.co/I9wudb2.png)

Does anyone faced this issue before?

Thanks in advance for your help.

**Comment by kzimny** [comment]
Do you work with ckeditor version 4 or 5? Maybe this [closed issue](https://github.com/chymz/ng2-ckeditor/issues/133) would help?

**Comment by lidibe** [comment]
I am using the version 5. The strange issue is that when you select the text and apply "bold" for example, "Bold" is highlighted, but the text does not appear bold.

**Comment by kzimny** [comment]
I never tried ng2-ckeditor with version 5 of ckeditor. Probably that's reason why it doesn't work.

**Comment by lidibe** [comment]
Okay. thanks
