### ISSUE TITLE
CKEditor initial content (AngularFire + Firebase)

### ISSUE THREAD

**Issue by cerealexx** [chymz/ng2-ckeditor#27]
I'm trying to get an initial content value from a Firebase database object into ckeditor in my edit news component. 
The way to get this object is through AngularFire:
```
constructor(private af: AngularFire) { 
      this.news = af.database.object('news/id');
    }
```
With the other form nodes like the input title one, using interpolation such us `value="{{(news | async)?.title}}"` worked fine but since ckeditor asks for an `[(ngModel)]` to show its content, there's no way I can use that kind of syntax there.

Is there any other way to pass the object value "news.content" to CKEditor?

Thanks!

**Comment by chymz** [comment]
Hi,

I don't use AngularFire, did you try this : 

```
constructor(private af: AngularFire) { 
  af.database.object('news/id')
    .subscribe((news) => {
      this.news = news;
    });
}
```

Then you can use ngModel: 

```<ckeditor [(ngModel)]="news"></ckeditor>```

**Comment by cerealexx** [comment]
Yep, that was my first try but it brought up these errors:
> Type 'Subscription' is not assignable to type 'FirebaseObjectObservable<any>'.
>  Property '_ref' is missing in type 'Subscription'.
I'm new to AngularFire too so I don't really get what is happening.

**Comment by cerealexx** [comment]
TypeError: Cannot read property 'content' of undefined... {{news}} doesn't print anything either.

The only reference to object binding that is found in AngularFire 2 docs is this:

> To get the object in realtime, create an object binding as a property of your component or service. Then in your template, you can use the async pipe to unwrap the binding.


```
import {Component} from 'angular2/core';
import {AngularFire, FirebaseObjectObservable} from 'angularfire2';

@Component({
  selector: 'app',
  template: `
  <h1>{{ (item | async)?.name }}</h1>
  `,
})
export class AppComponent {
  item: FirebaseObjectObservable<any>;
  constructor(af: AngularFire) {
    this.item = af.database.object('/item');
  }
}
```

It only explains how to bind through interpolation, not ngModel...

**Comment by chymz** [comment]
Thank you for your clarification ! 
I'll look this soon

**Comment by chymz** [comment]
Well in AngularFire2 docs : https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md#returning-promises

It seems it returns Promises, you need to use then() instead of subscribe(), so can you try:

```javascript
constructor(private af: AngularFire) { 
  af.database.object('news/id')
    .then((news) => {
      this.news = news;
    });
}
```

**Comment by cerealexx** [comment]
Just in case it is useful for someone else. I found a workaround.

Inside the Constructor or ngOnInit:
```
this.item = this.af.database.object('items/'+this.route.snapshot.params['id'],{ preserveSnapshot: true });
      this.item.subscribe(snapshot =>{
        this.values = snapshot.val();
```
This will get the specified object on the route.params from your Firebase database.

You also need a dummy for the value that ckeditor will read through ngModel, so it does not get an undefined value. (AngularFire will update with the correct value when it's ready):
```
values: any = {
    ckeditor : ''
  }
```

And lastly, one more fix. Inside the ckeditor node you also need a *ngIf so it won't render empty before Firebase has done its thing.
`<ckeditor *ngIf="values.ckeditor" #contenido name="ckeditor" [(ngModel)]="values.ckeditor"></ckeditor>`

Hope this helps! It has been driving me crazy for a while now!
