### ISSUE TITLE
ERROR in There is no format with import statements in '/xxx/' entry-point.

### ISSUE THREAD

**Issue by stkrwilson** [chymz/ng2-ckeditor#274]
error after upgrading to Angular v8 ivy

**Comment by kzimny** [comment]
Can you please provide more information? When do you get the error message? During the npm installation or compilation process (prod or dev?)? @Timebutt : any suggestion?

**Comment by stkrwilson** [comment]
in dev ... during compile (ng serve).
similar to:
https://github.com/swimlane/ngx-datatable/issues/1699

**Comment by kzimny** [comment]
Test with version 1.2.6. It should work now.
