### ISSUE TITLE
ng2-ckeditor has no exported member 'CKEditorComponent'

### ISSUE THREAD

**Issue by Donjay2101** [chymz/ng2-ckeditor#275]
Hi,
    I am trying to build CI/CD pipline for one of our projects build on Angular 6. when I am running the project on local environment it is working fine. but when I am running this environment on CI/CD pipeline at the time of build it gives issue, and the issues is something like this:

"ng2-ckeditor has no exported member CKEditorComponent"

my initial hunch is that ng2-CKEditor depends on "npm" version. 

please help me out on this , ng2-ckeditor depends on npm version or not? if not then what could be the reason of this error.

npm version : 5.6.0
Angular version : 6+

**Comment by kzimny** [comment]
I'm working with CI/CD pipeline from Azure DevOps without any problems. As you can [see ](https://github.com/chymz/ng2-ckeditor/blob/master/package.json#L47) in package.json file ng2-ckeditor depends on typescript ```>=3.1.1 <3.2.0```. Ng2-ckeditor has been updated to angular 7.

**Comment by Donjay2101** [comment]
> 
> 
> I'm working with CI/CD pipeline from Azure DevOps without any problems. As you can [see ](https://github.com/chymz/ng2-ckeditor/blob/master/package.json#L47) in package.json file ng2-ckeditor depends on typescript `>=3.1.1 <3.2.0`. Ng2-ckeditor has been updated to angular 7.

mine is angular 6 I have seen that it updated angular version. because it gives warning while download. but it works with angular 6. becuase I am facing issue only in CI/CD (TFS).

**Comment by kzimny** [comment]
Check if CKEditorModule is [imported ](https://github.com/chymz/ng2-ckeditor#sample) in AppModule.

**Comment by Donjay2101** [comment]
although I checked that and its already imported. still let me reconfirm that.

**Comment by kzimny** [comment]
Did you try to search for ```ci/cd pipeline has no exported member``` on google? I suppose that the issue is out of ng2-ckeditor scope. Try to run your pipeline without ng2-ckeditor import to investigate the problem.

**Comment by kzimny** [comment]
CI/CD integration is out of ng2-ckeditor range

**Comment by gopaljsh** [comment]
I had the same issue and i removed the CKEditorComponent import in component file. error gone.
