### ISSUE TITLE
No event is fired when adding new links

### ISSUE THREAD

**Issue by cuongmanhle** [chymz/ng2-ckeditor#277]
The component emits the `onEditorChange` event when removing links but nothing is fired when adding new links.

**Comment by kzimny** [comment]
Add ```onChange($event)``` event listener to your ckeditor and check the [demo](https://stackblitz.com/edit/ng2-ckeditor).
![20190722_070357](https://user-images.githubusercontent.com/12007674/61607548-8da05680-ac4f-11e9-98d0-302794bef370.gif)
