### ISSUE TITLE
"Cannot read property 'getRanges' of null" on destroy?

### ISSUE THREAD

**Issue by hitas** [chymz/ng2-ckeditor#28]
I came here with #24, which redirected to #23. #23 is refering [plunkr](https://embed.plnkr.co/PqRdBfUdvJ71uUPzY8vG/) which fixes the warning, but makes it a bit worse - an error (at least by chrome's colouring, was yellow, now red).

**Comment by 7Hd** [comment]
I also meet this issue. below link maybe can use.

http://dev.ckeditor.com/ticket/10219
> bug condition is do not click edit area before destry().

> if the edit area once actived, destry action will not throw error. or we put the destry action in window.setTimeout, it will neither throw error.

**Comment by chymz** [comment]
Thanks for reporting this, I'll work on it soon

**Comment by chymz** [comment]
Thanks @7Hd !
Fixed in 1.0.6

**Comment by naveedahmed1** [comment]
I am using 1.0.6 but still receiving this error.

**Comment by cerealexx** [comment]
@naveedahmed1 Do you use divarea plugin instead of iframe?

**Comment by naveedahmed1** [comment]
Yes

**Comment by naveedahmed1** [comment]
In fact, if I dont use divarea plugin I receive below error:

```
[CKEDITOR] Error code: editor-destroy-iframe.
ckeditor.js:19 [CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-destroy-iframe
```

if I add divarea plugin I receive below error:

`"Cannot read property 'getRanges' of null" on destroy?`

**Comment by cerealexx** [comment]
Note that iframe comes with ckeditor package by default. Maybe you are just adding divarea to the package and you need to delete iframe so there's no conflict.

**Comment by naveedahmed1** [comment]
@cerealexx can you please elaborate what do you mean by " you need to delete iframe"?

Can you please also update contact info in your profile for a direct contact?

**Comment by cerealexx** [comment]
I'm guessing you are using a cdn for ckeditor with iframe usage by default. Watch your html with any browser developer tools to see if the iframe node is still there (even if you added divarea).

If that's the case, you need to [build your own](http://ckeditor.com/builder). Note there's iframe editing area plugin selected inside the package by default. Delete that one by moving it to the right column and add the div editing area to the left column.

**Comment by naveedahmed1** [comment]
@cerealexx yes I am using CDN for editor, but in my config I have the below configuration which I believe should remove the iframe plugin and add divarea plugin.

```
extraPlugins: 'divarea',
removePlugins: 'wysiwygarea',
```

**Comment by naveedahmed1** [comment]
Ok I just tried using a custom build CKEditor which I built using http://ckeditor.com/builder

But I am still having the same error:

`EXCEPTION: TypeError: Cannot read property 'getRanges' of null`

I also confirmed it by inspecting the DOM and there isnt any iframe in the dom.

**Comment by chymz** [comment]
@naveedahmed1 why did you post same comment on multiple issues ?

Anyway, can you share plunker or code to reproduce this error ? I've no problem with 2 samples repo in README...

**Comment by naveedahmed1** [comment]
@chymz  can you please have a look at this plunker and monitor the console while you toggle the editor:

https://plnkr.co/edit/og9vfnhbe7bjry9gTqII?p=preview

**Comment by chymz** [comment]
Obviously, you don't read README correctly : 
- Watch your ng2-ckeditor version (we are now in 1.0.6...)
- Your config is not declared correctly in template https://github.com/chymz/ng2-ckeditor#sample-es2016

Everything is working on my side...

**Comment by hkkhchan** [comment]
I also have these problem.
I use ng2-ckeditor because ngx-admin is using it in demo. 
I found ngx-admin also have this problem and not fixed it.
but I found a solution to fixed.
when the editor is ready call this:
`   editor.instance.focus();`

**Comment by hkkhchan** [comment]
I would like to share my solution.
I bind a ready event to call ckeditor.instance.focus();
if morn than one instance. I focus them one by one.
