### ISSUE TITLE
Modal Pop using bootstrap 4 form not working on button click in angular 8

### ISSUE THREAD

**Issue by bitlygurm** [chymz/ng2-ckeditor#282]
Please refer to the code below.

Code of HTML File:

<button type="button"
      class="btn btn--primary" data-toggle="modal" data-target="#addNew"
      style="margin-top:100px;width:90px;text-align:center;border-radius: 0px"
      (click)="addContact()" >Add New
 </button> 

                      <div id="addNew" class="modal fade " role="dialog" >
                      <div class="modal-dialog">

    
    <div class="modal-content">
        <div class="modal-header text-center">
            <h4 class="modal-title w-100 font-weight-bold">Write to us</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body mx-3" id="modalform">
              <div class="md-form mb-3">
                <i class="fas fa-user prefix grey-text"></i>&nbsp;&nbsp;&nbsp;<label data-error="wrong" data-success="right" for="form34">Your name</label>

                <input type="text" id="form34" class="form-control validate">
              </div>
      
              <div class="md-form mb-3">
                <i class="fas fa-envelope prefix grey-text"></i>&nbsp;&nbsp;&nbsp;<label data-error="wrong" data-success="right" for="form29">Your email</label>
                <input type="email" id="form29" class="form-control validate">
                
              </div>
      
              <div class="md-form mb-3">
                <i class="fas fa-tag prefix grey-text"></i>&nbsp;&nbsp;&nbsp;<label data-error="wrong" data-success="right" for="form32">Subject</label>
                <input type="text" id="form32" class="form-control validate">
                
              </div>
              <div class="md-form">
                  <i class="fas fa-pencil prefix grey-text"></i>&nbsp;&nbsp;&nbsp;<label data-error="wrong" data-success="right" for="form8">Your message</label>
                  <textarea type="text" id="form8" class="md-textarea form-control" rows="4"></textarea>
                  
                </div>
          </div>
      
          <div class="modal-footer d-flex justify-content-center">
              <button class="btn btn-info">Send</button>
            </div>
          </div>
        </div>
      </div>
      

Component.ts code:

constructor() { }

  ngOnInit() {
  }
addContact() {}
}

Thanks in advance for the help

**Comment by kzimny** [comment]
I can not see any reference to ng2-ckeditor component in your source code. Why don't you ask the your question in bootstrap forum, or is this a misunderstanding?
