### ISSUE TITLE
Where does the plugins dir go?

### ISSUE THREAD

**Issue by cerealexx** [chymz/ng2-ckeditor#29]
Seems a really easy question but I couldn't find any documentation about this.
I tried to put it inside `ckeditor/` but the cli keeps deleting it when the app is served. Should I modify the system-config?

Thanks

**Comment by chymz** [comment]
Hi,

Did you read this ? http://docs.ckeditor.com/#!/guide/dev_plugins

**Comment by cerealexx** [comment]
Yes, I guess I didn't explain myself well. I know how it works in a "normal" environment.
I don't know how it works inside the ng2-ckeditor module. I mean, does the plugins dir go inside the root, or maybe lib? And if that's so, I suppose I need to edit the system-config somehow, because it always deletes any dir I make inside ng2-ckeditor by default when I serve with cli.

**Comment by chymz** [comment]
You don't have to do anything with the content of ng2-ckeditor. You need to put CKEditor library in some dir, and put plugins in it that's all...

Do you use angular cli ?

If so, i'll try to update the sample repo to show this.

**Comment by cerealexx** [comment]
Yes, please. That would make things way easier to understand.
Thanks!

**Comment by chymz** [comment]
You can see in this repo : https://github.com/chymz/ng2-cli-ckeditor-sample

I've added `ckeditor` directory in `src` directory and then I put the `divarea` plugin in `src/ckeditor/plugins`

**Comment by cerealexx** [comment]
I see... I totally forgot ckeditor was called with a cdn so I didn't understand you when you talked about a local ckeditor dir. Thanks for your patience!

**Comment by OdaiTu** [comment]
@chymz i think i have the same problem but i didnt understant the idea or the solution
the sample u put here is 404 not found page !

**Comment by sharath1608** [comment]
@chymz Would be great if you could have the sample repo. I'm having a hard time trying to make the pbckcode plugin work right now.

**Comment by zuhrulumam** [comment]
@chymz you could have the sample repo up again ?? i got the same problem and still cannot resolve it..

thank you

**Comment by figuerres** [comment]
trying to figure this out also....  need to add glyphicons plugin...

**Comment by kzimny** [comment]
@figuerres: you can use the glyphicons in the standard html manner. Please look at the similar [question](https://github.com/chymz/ng2-ckeditor/issues/162). If you want, you can of course use the glyphicon plugin as described [here](https://github.com/chymz/ng2-ckeditor/issues/159). Is that what you were looking for?

**Comment by figuerres** [comment]
My issue is solved, just had to see how to use the ckeditor cdn with a local plugin folder. got it working now.

**Comment by venkateshwarans** [comment]
@figuerres @kzimny , I am still trying to figure out how to make ckeditor cdn with local a plugin in my local folder. Can you please tell how you got it working? Any help would be appreciated.

**Comment by kzimny** [comment]
Hi, yes you can work with CDN and local plugin folder. Please look at this question https://github.com/chymz/ng2-ckeditor/issues/220#issue-332863214
