### ISSUE TITLE
Release number mismatch between github and npm

### ISSUE THREAD

**Issue by sh977218** [chymz/ng2-ckeditor#291]
Hi, I'm looking at npm, as today 2/26/2020.
the current release number is 1.2.6 from https://www.npmjs.com/package/ng2-ckeditor
But on github the current release number is v1.1.4 from https://github.com/chymz/ng2-ckeditor/releases.
Why are they so different?

**Comment by kzimny** [comment]
Latest npm packed release is 1.2.7 https://github.com/chymz/ng2-ckeditor/releases
