### ISSUE TITLE
Support for Angular 10

### ISSUE THREAD

**Issue by RoopanV** [chymz/ng2-ckeditor#294]
I have been using this module for more than 2 years. It will really great if support for Angular 10 is provided. Currently, all peer dependencies are pointing Angular 9 which results in the following warnings during the build.

npm WARN ng2-ckeditor@1.2.7 requires a peer of @angular/core@^9.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.7 requires a peer of @angular/forms@^9.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.7 requires a peer of @angular/common@^9.0.2 but none is installed. You must install peer dependencies yourself.

**Comment by kzimny** [comment]
I will look and let you next week know when the next release can be prepared.

**Comment by kzimny** [comment]
@chymz : please create new nmp version and update https://github.com/chymz/ng2-ckeditor/releases

**Comment by chymz** [comment]
Done, thanks !
