### ISSUE TITLE
Issue with ngcc build

### ISSUE THREAD

**Issue by RoopanV** [chymz/ng2-ckeditor#296]
Hi,
         Facing below error with new ng-ckeditor@1.2.8

Warning: Unable to fully load D:/fusion/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts for source-map flattening: Circular source file mapping dependency: D:/fusion/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts.map -> D:/fusion/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts.map
Error: Tried to write D:/fusion/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts.__ivy_ngcc_bak with an ngcc back up file but it already exists so not writing, nor backing up, D:/fusion/node_modules/ng2-ckeditor/lib/ng2-ckeditor.d.ts.
This error may be because two or more entry-points overlap and ngcc has been asked to process some files more than once.
You should check other entry-points in this package and set up a config to ignore any that you are not using.

**Comment by kzimny** [comment]
@chymz: it seems to be a problem with the file structure in npm package. The compiled files are saved and published to ng2-ckeditor/lib folder. The ngcc compiler cannot find the entry point when package is build after installation. That worked in previous angular releases, but now the files from lib/ should be placed at the top in ng2-ckeditor folder. Please prepare a new npm package. Thanks!

**Comment by chymz** [comment]
Sorry! Fixed in `1.2.9`!

**Comment by kzimny** [comment]
Thanks! It works.
