### ISSUE TITLE
 Ng2-ckeditor maxlength not working

### ISSUE THREAD

**Issue by ashishbhave** [chymz/ng2-ckeditor#297]
I want allow only max 1000 character in ckeditor. Please refer following code & give me proper solution.

html file
<ckeditor [(ngModel)]="description" [readonly]="readOnlyCkeditor"
                              #myckeditor="ngModel" name="myckeditor" [config]="ckeConfig" debounce="500" [maxlength]="1000" required>
                           </ckeditor>
ts.file
ngOnInit() {
    this.ckeConfig = {
      allowedContent: false,
      extraPlugins: 'divarea',
      forcePasteAsPlainText: true
    };
  }

**Comment by kzimny** [comment]
There is no option for maxLength. But you can try as follow: #163

**Comment by ashishbhave** [comment]
Yes have already refer bug 163 , but in my case user not allow to max character length, i want to restrict on change event.
i want behavior like blow code
[https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_maxlength](url)

Thank you kzimny  for reply

**Comment by kzimny** [comment]
There is no maxlength attribute in ckeditor. You can use `(change)=""` event to check the max length.
