### ISSUE TITLE
Is there a way to browse images from local machine?

### ISSUE THREAD

**Issue by nehal076** [chymz/ng2-ckeditor#299]
![screenshot-ng2-ckeditor stackblitz io-2020 09 09-23_14_19](https://user-images.githubusercontent.com/32421196/92634634-37c6bc00-f2f2-11ea-9ae3-d36c48a6f9dd.png)

Is there any way to browse images with the Image picker from local system?

**Comment by kzimny** [comment]
As far as I know you can not browse files directly from your local machine with ckeditor. Please see #237, #238, #144
