### ISSUE TITLE
Unable to load CKEditor

### ISSUE THREAD

**Issue by MohammedAnsary** [chymz/ng2-ckeditor#3]
Hi.
Everytime I try to run the code I get this error 
```
angular2-polyfills.js:390 Error: SyntaxError: Unexpected token <
	Evaluating http://localhost/mohammed-elansary/Notes2/node_modules/ng2-ckeditor
	Error loading http://localhost/mohammed-elansary/Notes2/app/main.js
ZoneDelegate.invoke               @ angular2-polyfills.js:390
Zone.run                                   @ angular2-polyfills.js:283
(anonymous function)               @ angular2-polyfills.js:635
ZoneDelegate.invokeTask        @ angular2-polyfills.js:423
Zone.runTask                            @ angular2-polyfills.js:320
drainMicroTaskQueue               @ angular2-polyfills.js:541
ZoneTask.invoke                       @ angular2-polyfills.js:493
```
Any thoughts on how to make it work?

**Comment by chymz** [comment]
Hi,

Do you use webpack, browerify or jspm ?
Browser try to load `/node_modules/ng2-ckeditor` or the main file of this component is `/node_modules/ng2-ckeditor/lib/CKEditor.js`

Maybe i miss something in the `package.json` or you miss something in the config of your bundler ?

Thanks !

**Comment by MohammedAnsary** [comment]
Hello again,
I still haven't figured out the problem, but I tried cloning the source code into a ts file and using the default transpiler included in angular2's quickstart and everything worked just fine. I think I had something wrong in the configuration when I tried to use webpack.

**Comment by chymz** [comment]
Well i have cloned angular2-seed to test this component : https://github.com/chymz/angular2-seed-ckeditor

It works !

**Comment by MohammedAnsary** [comment]
I tried it and it works. Thanks.

**Comment by vknaveenkumar** [comment]
not working for me

**Comment by vknaveenkumar** [comment]
can anyone how use to ckconfig as directives ?

**Comment by tylerjgarland** [comment]
@chymz , it seems you have deleted your example webpack file. Do you have it in a new location?
