### ISSUE TITLE
Editor-destroy-iframe Error on form submission

### ISSUE THREAD

**Issue by naveedahmed1** [chymz/ng2-ckeditor#30]
Hi,

I am using ng2-ckeditor in one of my forms. But when I submit the form I see the below errors in console.
﻿
```
ckeditor.js:19 [CKEDITOR] Error code: editor-destroy-iframe.
ckeditor.js:19 [CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-destroy-iframe
```

Can you please guide how to resolve it?

Is there a proper way to destroy ng2-ckeditor instance on ngDestroy to avoid any memory leaks?

**Comment by 7Hd** [comment]
maybe you can try #24 
> use `divarea` plugin or inline mode

**Comment by chymz** [comment]
Yes is related to #23 & #24

**Comment by tylerjgarland** [comment]
@chymz , @naveedahmed1 , I've used this to get rid of the message. I just run this before I close my dialog.

        for (name in CKEDITOR.instances) {
            CKEDITOR.instances[name].destroy(true);
        }

**Comment by naveedahmed1** [comment]
I tried divarea plugin but now I am getting below error:

`"Cannot read property 'getRanges' of null" on destroy?`

**Comment by AshishTiwariMEAN** [comment]
`for(name in CKEDITOR.instances){
							CKEDITOR.instances[name].destroy()
						}`
Use to code to destroy all the instances created by ckeditor

**Comment by ashishnaghate** [comment]
`for(name in CKEDITOR.instances){
							CKEDITOR.instances[name].destroy()
						}`
Use to code to destroy all the instances created by ckeditor
