### ISSUE TITLE
Full Screen with Browsers Back button Issue

### ISSUE THREAD

**Issue by kalathiyan** [chymz/ng2-ckeditor#301]
Hi i am using "ng2-ckeditor": "^1.2.7" Version and facing below issue

When user click on full-screen button from toolbars and press back button of browser then ui getting broken,

Stackblitz URL For checking issue: 
https://angular-6-routing-fqavvv.stackblitz.io/about
Steps: Go To services tab and press Maximize button from ck editor toolbar
Press back button of browser

Above code Stackblitz Code Url is: 
https://stackblitz.com/edit/angular-6-routing-abbwws?file=src%2Fapp%2Fpage%2Fservice.component.html

**Comment by kzimny** [comment]
This is not an issue with ng2-ckeditor but with the "maximize" plugin from ckeditor which does not clean the styles before destroy the instance. I prepared a demo with the official ckeditor 4 wrapper for angular:
Stackblitz editor: https://stackblitz.com/edit/angular-ivy-wxq5w9
Stackblitz demo: https://angular-ivy-wxq5w9.stackblitz.io/
They have the same issue. I propose to wait for a fix in ckeditor.

**Comment by kzimny** [comment]
This issue has been fixed in v.4.17.1. Please update your ckeditor reference to latest version <script src="//cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
