### ISSUE TITLE
removes the class from h2 tag

### ISSUE THREAD

**Issue by anandkothari27** [chymz/ng2-ckeditor#302]
Hello , 
I have integrated package in angular 10 application 

when i paste HTML code direct in source it shows "

![image](https://user-images.githubusercontent.com/52647933/94991538-72461080-05a1-11eb-9ae4-d93fb058cdf5.png)

but when i come back to source it shows as below

![image](https://user-images.githubusercontent.com/52647933/94991551-90137580-05a1-11eb-8b76-a9edc5131fb0.png)

it removes class from h2 tag automatically 

please help regarding this issue

**Comment by kzimny** [comment]
When you add `allowedContent: true` to ckeditorConfig the css classes  will stay:

```
    this.ckeConfig = {
      allowedContent: true,
      extraPlugins: 'divarea'
    };
```

**Comment by anandkothari27** [comment]
ok thanks @kzimny  👍
