### ISSUE TITLE
Custom Button in Image Properties dialog

### ISSUE THREAD

**Issue by newETA** [chymz/ng2-ckeditor#303]
I was looking for the implementation of this fantastic editor, But I had an issue I need to add on the extra button in the Image Properties.

I was able to add an extra button in the toolbar,  that doesn't make any sense for me to have an extra button in the toolbar to browse the files since all images setting is here. 

Please advise if there is any way, I can add a button and event handler. 
 
![image](https://user-images.githubusercontent.com/42071761/96078717-1c1a7c80-0e81-11eb-890c-fad9cc8a94ea.png)

**Comment by kzimny** [comment]
Maybe are you looking for a ckeditor upload plugin? There are a few as far as I know. Maybe this question #240 would help to find the right solution for you. Many of them base on server side code, except they save base64 formatted string as image. If the plugins doesn't fit your requirements I would suggest to make your own file explorer. It's not impossible, look at this example #237
