### ISSUE TITLE
S1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by jayjupdhig** [chymz/ng2-ckeditor#304]
get that message when i build with latest nodejs 10.x version: https://github.com/angular/angular/issues/39674

the only one adequate solution (regarding time & finances) seems to be:

change file `ckeditor.component.d.ts` from:

```

    get value(): any;
    set value(v: any);

```

to:

```
    /*
    get value(): any;
    set value(v: any);
    */
```

Or removing the lines...

Why that?

Thx for feedback,
Jan

**Comment by kzimny** [comment]
Without deep dive in your project dependencies, try to skip the library check in tsconfig.json resp. tsconfig.base.json. Hope it will help you!

```
"compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    **"skipLibCheck": true,**
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
```

**Comment by jayjupdhig** [comment]
Thank you very much!! :-)
