### ISSUE TITLE
Error with CKEditor 4.5 : Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by EtienneCoumont** [chymz/ng2-ckeditor#308]
Hello,

I'm using CKEditor v4.5.1 and I get an error when ngOnDestroy (in ckeditor.component.ts) is called.

`ERROR TypeError: Cannot read property 'destroy' of undefined in ckeditor.js`

Actually, it looks like you call `instance.destroy();` twice and CKEditor crashes when it happen. (it happens with all 4.5 versions but not 4.6)

I replaced  `this.instance.destroy();` by `if (this.instance.status !== 'destroyed') {this.instance.destroy();}` and it seems to work.

Is CKEditor 4.5 officially supported by ng2-ckeditor

Could you add the above destroyed check to your destroy function, or another fix if you think of something better ? 

Thanks.

**Comment by kzimny** [comment]
Yes, you right. The [fix ](https://github.com/chymz/ng2-ckeditor/pull/305/files) is ready for deployment. Awaiting new release. @chymz please create new npm version. Thx!

**Comment by chymz** [comment]
Try `1.3.0`, Thanks for reporting !

**Comment by EtienneCoumont** [comment]
Thanks for the quick response. Unfortunately, that did not solve the issue.
Here is a stackblitz recreating the issue : 
https://stackblitz.com/edit/ng2-ckeditor-atcarw?devtoolsheight=33&file=src/app/app.component.ts

**Comment by kzimny** [comment]
Thank you for your feedback, version 1.3.1 should fix the issue. @chymz: could you please create a new npm package AND new release https://github.com/chymz/ng2-ckeditor/releases. Thank you.

**Comment by chymz** [comment]
`1.3.1` published !

**Comment by EtienneCoumont** [comment]
It works great.
Thanks guys, you're awesome !
