### ISSUE TITLE
Support for Angular V12

### ISSUE THREAD

**Issue by RoopanV** [chymz/ng2-ckeditor#313]
Since angular V12 is out, support for the same will be greatly appreciated.

**Comment by kzimny** [comment]
Does ng2-ckeditor not work with angular v12? Do you get an error or only peer-dependencies warning?

**Comment by RoopanV** [comment]
While I am trying to install in Angular 12 project getting below error

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: module-fed@0.0.0
npm ERR! Found: @angular/common@12.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^11.0.4" from ng2-ckeditor@1.3.3
npm ERR! node_modules/ng2-ckeditor
npm ERR!   ng2-ckeditor@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by kzimny** [comment]
@chymz : please create new release 1.3.4

**Comment by chymz** [comment]
Published, thanks!
