### ISSUE TITLE
this.onTouched is not a function - on typing anything in ckeditor

### ISSUE THREAD

**Issue by pishangujeniya** [chymz/ng2-ckeditor#315]
Error on typing anything in CKEditor in Chrome Browser console.

```javascript

core.js:6210 ERROR TypeError: this.onTouched is not a function
    at a.<anonymous> (ng2-ckeditor.js:234)
    at a.k (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:12)
    at a.push.n2S2.window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
    at CKEDITOR.plugins.undo.UndoManager.type (ckeditor.js:1136)
    at CKEDITOR.plugins.undo.NativeEditingHandler.onKeyup (ckeditor.js:1146)
    at c.k (ckeditor.js:10)
    at c.fire (ckeditor.js:12)
    at HTMLDivElement.<anonymous> (ckeditor.js:63)
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)

```

**Comment by kzimny** [comment]
The touched event is not implemented. Use the change, editorchange, ready, blur or focus events instead https://github.com/chymz/ng2-ckeditor/blob/d031a391e670007b898fb5849c06a6b763f74c42/src/ckeditor.component.ts#L43

**Comment by pishangujeniya** [comment]
> ```js
> onTouched 
> ```

The error occurs with Angular 12

I didn't do anything, simply adding `ckeditor` selector in a component is giving this error.

**Comment by kzimny** [comment]
Wich [version ](https://github.com/chymz/ng2-ckeditor#installation) of ckeditor are you using?

**Comment by pishangujeniya** [comment]
- `package.json`
```json

{
    "@types/ckeditor": "^4.9.10",
    "ckeditor4": "^4.16.1",
    "ng2-ckeditor": "^1.3.4",
}

```
- component.ts
```html
<script src="https://cdn.ckeditor.com/4.16.1/full-all/ckeditor.js"></script>
<ckeditor [config]="{ extraPlugins: 'divarea', height: '320' }"></ckeditor>

```

- ts file
```tyepscript
window.CKEDITOR_BASEPATH = '//cdn.ckeditor.com/4.16.1/full-all/';
```

**Comment by kzimny** [comment]
1. You can remove ckeditor4 package because you are using the script from CDN.
2. Move your `<script></script>` section to index.html
3. Delete `window.CKEDITOR_BASEPATH = ...`from your ts file

**Comment by pishangujeniya** [comment]
> * You can remove ckeditor4 package because you are using the script from CDN.
> * Move your `<script></script>` section to index.html

I don't want to use CDN, I don't want that js to load while index.html loads.

Any way to solve that?

**Comment by kzimny** [comment]
Follow the instruction #228 how to use ng2-ckeditor from your local machine. If you don't want to add the script directly to your index.html you have to add them programmatically in your ngOnInit() method in your component.

**Comment by MBDesu** [comment]
I am able to reproduce this issue with a very simple setup here: https://stackblitz.com/edit/angular-ivy-1l2rbr?devtoolsheight=33&file=src/app/app.component.ts

Note that all of the suggestions provided by @kzimny are followed in this example

**Comment by kzimny** [comment]
> Note that all of the suggestions provided by @kzimny are followed in this example
The error occurs because you didn't stricktly follow the sample [instruction](https://github.com/chymz/ng2-ckeditor#sample).
Please look at the [demo](https://stackblitz.com/edit/ng2-ckeditor).

**Comment by Aleksandr-ru** [comment]
Got same problem. I'm using ReactiveForms instead of ngModel so my template looks like this
```
<ckeditor
  #editor
  [config]="editorConfig"
  [readonly]="disabled"
  [value]="value"
  (ready)="onReady($event)"
  (change)="onDataChange($event)"
></ckeditor>
```
It works fine with ng9 and ng10, but after upgrading to ng14 the problem appears.

Quick workaround is not to set value until onTouched and onChange is defined.
So I removed   `[value]="value"` from template and added 3 lines of code to my component:
```
onReady(event) {
    if (this.editor) {
      // https://github.com/chymz/ng2-ckeditor/issues/28#issuecomment-672900189
      this.editor.instance.focus();

      // https://github.com/yabab-dev/ng2-ckeditor/issues/315
      this.editor.registerOnChange(() => {});
      this.editor.registerOnTouched(() => {});
      this.editor.value = this.value;
    }
  }
```
And the problem seems to be gone. No errors in console, editor works as expected.

The right solution is to change [ckeditor.component.ts lines 245-247](https://github.com/yabab-dev/ng2-ckeditor/blob/master/src/ckeditor.component.ts#L245) to 
```
onChange = (_: string) => {};
onTouched = () => {};
```
This is simply creates empty functions on init and the problem should not take place at all.
@kzimny take a look please.

**Comment by kzimny** [comment]
ckeditor 4 is end-of-life. I'm not mantaining ng2-ckeditor package anymore. Make a pull request and ask the package owner @yabab-dev for updates.
