### ISSUE TITLE
Will ng2-ckeditor work with angular 2.0.0?

### ISSUE THREAD

**Issue by ShubhamTANDF** [chymz/ng2-ckeditor#316]
We have angular app which runs on angular 2.0.0. will ng2-ckeditor work for it. If yes then any specific versions we need to install

**Comment by kzimny** [comment]
Angular version 2.0.0 is pretty old! I would recommend to update your angular to newer version. If you can not update you project you can use one of the previous ng2-ckeditor releases, maybe v.1.1.19.

**Comment by ShubhamTANDF** [comment]
thank you so much will use v.1.1.19. Any reference links or something on how to use older versions of ng2-ckeditor in angular 2.0.0

**Comment by kzimny** [comment]
Install the package with `npm install ng2-ckeditor@1.1.19 --save`. In your [own component](https://github.com/chymz/ng2-ckeditor/issues/311#issuecomment-775196244) declare the ckeditor as `any`. The rest should work, if not update your angular framework to newer version.

**Comment by ShubhamTANDF** [comment]
ERROR in main.bd776877e098544e9e6a.bundle.js from UglifyJs
SyntaxError: Unexpected token: name (CKButtonDirective) [main.bd776877e098544e9e6a.bundle.js:24786,6]

**Comment by kzimny** [comment]
AFAIK version 1.1.19 is the last with angular 2.0.0 compatible release. It's possible that CKButtonDirective has been added after release 1.1.19. Try without the ckbuttons in your html code.

**Comment by ShubhamTANDF** [comment]
there is no 1.1.19 version, using 1.1.14 to integrate with angular 2.0.0 still not successful..I m trying

**Comment by ShubhamTANDF** [comment]
I am not using ckbuttons anywhere in my code..but still I am getting this error
