### ISSUE TITLE
CKEditor does not work with RC5

### ISSUE THREAD

**Issue by golechwierowicz** [chymz/ng2-ckeditor#32]
`import {Component} from "@angular/core"`
    ` import {CKEditor} from "ng2-ckeditor"`

`@Component({`
   ` selector: "foo",`
  `  directives: [CKEditor],`
   ` providers: [],`
  `  template: ``
  <ckeditor
  debounce="500" [(ngModel)] = "content">
  </ckeditor>
`})

`export class FooComponent {`
`    content: string`
`    constructor() {`
`        this.content = "<p>Hello <strong>World !</strong></p>"`
`    }`
`}`

The code above does not work. I am using angular 2 RC 5 and in throws an error:

> EXCEPTION: Error in ./FooComponent class FooComponent - inline template:2:19
ORIGINAL EXCEPTION: No value accessor for form control with unspecified name
ORIGINAL STACKTRACE:
Error: No value accessor for form control with unspecified name

I am using forms in the same template, can this be an issue? I am using angular with NgModule and importing FormsModule when bootstraping.

**Comment by chymz** [comment]
Hi,

Which version of @angular/forms do you use ?

I've updated the plunker, and it works fine with latest versions : https://embed.plnkr.co/hnB0R3/
Some deprecated warnings, but related to #31 I think

**Comment by golechwierowicz** [comment]
Hi, 

I use 0.3.0 version. Could this be related to the ngmodule? While bootstrapping via old method you have to provide deprecateoldforms explicite.

**Comment by chymz** [comment]
I'm not up to date with NgModules, but maybe...
Can you share your bootstrap ?

I'll do some tests very soon

**Comment by golechwierowicz** [comment]
I've discovered that after removing ngModel CKEditor starts working, but without binding of course.

 `@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
    ],
    declarations: [
        AppComponent,
        FooComponent,
    ],
    providers: [
        {
            provide: SomeService,
            useClass: ISomeService
        }
    ],
    bootstrap: [AppComponent]
 })

 export class AppModule {
 }`

**Comment by golechwierowicz** [comment]
Okay, everything works as expected. NgModule has nothing to do with it. Just make sure to implement new FormsModule completely in your app. In my case AppComponent's directives were using depracated FORM_DIRECTIVES. You can mark this, as closed issue. Thanks for the support.
