### ISSUE TITLE
Office.js Word Document Styles

### ISSUE THREAD

**Issue by vimal-darji-ifour** [chymz/ng2-ckeditor#320]
Hello There, I am trying to get list of styles supported by Office Word Document, as mentioned in below image.
![image](https://user-images.githubusercontent.com/39907946/141461513-53c400c5-478c-4874-8d0d-28a2f077127b.png)
To Retrive styles from Office.js I am getting below list.
![image](https://user-images.githubusercontent.com/39907946/141461581-3778d4e2-bdcc-4798-9582-0924d32f7c46.png)

Please help me to get all styles (in Office Word Document) with Office.js API.

**Comment by kzimny** [comment]
it's a ng2-ckeditor related question?

**Comment by vimal-darji-ifour** [comment]
Ups, My bad. its not related with ng2-ckeditor.
