### ISSUE TITLE
Support for Angular V13

### ISSUE THREAD

**Issue by RoopanV** [chymz/ng2-ckeditor#321]
Can you please provide support for Angular V13. Facing below issue while installing the library:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: @angular/common@13.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.4" from ng2-ckeditor@1.3.4
npm ERR! node_modules/ng2-ckeditor
npm ERR!   ng2-ckeditor@"1.3.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

On Force installing facing below warning:
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ng2-ckeditor [es2015/esm2015] (git+https://github.com/chymz/ng2-ckeditor.git)
Encourage the library authors to publish an Ivy distribution.

**Comment by kzimny** [comment]
@chymz please create a new version

**Comment by kzimny** [comment]
@chymz : could you create a new version please?

**Comment by kzimny** [comment]
@chymz: any chance to prepare a new version?

**Comment by chymz** [comment]
Sorry @kzimny I'll do this today

**Comment by chymz** [comment]
Done, `1.3.5` published
