### ISSUE TITLE
Version 1.3.5 is incorrectly published

### ISSUE THREAD

**Issue by gkalpak** [chymz/ng2-ckeditor#323]
Hey, there!

It seems that version 1.3.5 is not published correctly. More specifically, instead of publishing the contents of the [dist/][1] directory, it seems that the whole root directory was published. This causes the root [package.json][2] to be the published package's `package.json` (instead of [dist/package.json][3]), which does not contain any of the necessary entry-point properties (such as `main`, `module`, `es2020`, etc.).

For reference, we ran into this issue (see [relevant CI failure][4]) while trying to update to v1.3.5 in our [angular/ngcc-validation][5] repo.

[1]: https://unpkg.com/browse/ng2-ckeditor@1.3.5/dist/
[2]: https://unpkg.com/browse/ng2-ckeditor@1.3.5/package.json
[3]: https://unpkg.com/browse/ng2-ckeditor@1.3.5/dist/package.json
[4]: https://circleci.com/gh/angular/ngcc-validation/77858
[5]: https://github.com/angular/ngcc-validation/pull/5245

**Comment by kzimny** [comment]
@chymz: please publish a new version with the content of the dist/ folder and not the whole root.
Version 1.3.5 doesn't work

**Comment by chymz** [comment]
@gkalpak @kzimny `1.3.6` is published
