### ISSUE TITLE
Replace or change selected text with external button click.

### ISSUE THREAD

**Issue by shubhamp861** [chymz/ng2-ckeditor#330]
How to replace selected text with different text or more on to add style . For example if i select any text from editor and click on bold button it will go and change my selected text with bold style. wanted to create a button which will change or replace my selected text in editor

**Comment by kzimny** [comment]
Add a custom button to your editor with click event as shown [here](https://github.com/chymz/ng2-ckeditor/issues/96). To get the selected text use getSelection() method as shown [here](https://github.com/chymz/ng2-ckeditor/issues/245)

**Comment by shubhamp861** [comment]
Able to get selected text and button, but still don't know how we can replace it with different text so it can reflect back same to ck editor window. 

And also can we achieve Foot Note. for example refer below link

https://www.drupal.org/docs/8/modules/footnotes/adding-footnotes-to-content-via-the-ckeditor-toolbar

**Comment by kzimny** [comment]
Your questions are out of scope of ng2-ckeditor. For more information how ckeditor works please refere the ckeditor [documentation](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_element.html). Yes, you can replace the text or add your own element.
```
const selection = this.ckeditor.instance.getSelection();
const txt = selection.getSelectedText(); // or replace the text

let element: CKEDITOR.dom.element;
element = this.ckeditor.instance.document.createElement('span');
element .setAttribute('id', 'myIdXYZ');
element.setHtml(txt);
this.ckeditor.instance.insertElement(element);
```

**Comment by shubhamp861** [comment]
Thanks this will work for me. thanks for quick response.
