### ISSUE TITLE
new Provider() deprecated and removed in RC6

### ISSUE THREAD

**Issue by ashhitch** [chymz/ng2-ckeditor#34]
Since RC4 new Provider() has been deprecated and seems in RC6 it seems they have been removed.
**From the changelog:**
```
core: These forms of providers are no longer accepted:
bind(MyClass).toFactory(...)
new Provider(MyClass, toFactory: ...)
```

We now only accept:
`{provider: MyClass, toFactory: ...}`

**Comment by chymz** [comment]
Closed in 7c2177aecc8a021f4a413a425473e88e20e4d1ef
