### ISSUE TITLE
No provider for NgControl with RC5

### ISSUE THREAD

**Issue by chambersDon** [chymz/ng2-ckeditor#35]
When I move to rc5 I get this error at runtime:
   Template parse errors: No provider for NgControl

Does anyone else get it?

**Comment by chymz** [comment]
Did you try with RC6 ?

**Comment by chambersDon** [comment]
No.  That just came out yesterday and there are a lot of changes I need to make.

Should it work with RC6?

I think the problem is with the new modules in RC5.  If it's known to work with RC6 I'll start moving to it.

**Comment by chymz** [comment]
It works with RC6, you can look these :

https://github.com/chymz/angular2-jspm-seed/tree/ng2-ckeditor
or
https://embed.plnkr.co/hnB0R3/

Did you include FormsModule in your bootstrap ?

**Comment by chambersDon** [comment]
I don't think I have formsModule implemented properly.  You can close this.
