### ISSUE TITLE
Doesn't seem to work with AoT compiler  - Please add .metadata.json file in next release

### ISSUE THREAD

**Issue by naveedahmed1** [chymz/ng2-ckeditor#36]
When I try to compile my project using ngc for Ahead of Time Compilation. The compiler throws the below error:

`Error: Unexpected value 'CKEditorModule' imported by the module 'AppModule'`

**Comment by chymz** [comment]
I don't plan to work on this until the final release of Angular 2. But if someone is interested to work on that, pull requests are welcome.

Can you share some code/config ?

Thanks !

**Comment by belprixx** [comment]
@naveedahmed1 

did u put CKEditorModule in the imports  and providers of your NgModule ?

**Comment by naveedahmed1** [comment]
@chymz I have a normal component (HomeComponent) with CKEditor ccomponent and my AppModule looks like this:

**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';

import { AppComponent } from './components/app.component';
import { HomeComponent } from './components/home/home.component';
import { CKEditorModule } from 'ng2-ckeditor';

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        ReactiveFormsModule,
        CKEditorModule
    ],
    declarations: [
        AppComponent,
        HomeComponent
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

**Your might find below comments useful:**

https://github.com/angular/angular/issues/11262#issuecomment-244449696

https://github.com/angular/angular/issues/11262#issuecomment-244472000

https://github.com/angular/angular/issues/11262#issuecomment-244489405

Complete conversation (https://github.com/angular/angular/issues/11262)

Actually the Angular team suggest that library vendors should also ship **.metadata.json** files. These files are produced automatically by ngc.

**Comment by chymz** [comment]
@naveedahmed1 thanks for this, i'll look when I have a moment !

**Comment by devCrossNet** [comment]
+1

**Comment by chymz** [comment]
@naveedahmed1 fixed in v1.1.x, feel free to reopen if needed ;)

**Comment by devCrossNet** [comment]
@chymz sorry, it was an open issue and I installed it last week. didn't check for updates.

**Comment by chymz** [comment]
No problem, just stop to add comment with only +1, github have now reaction button :D
