### ISSUE TITLE
RC6 Error when adding CKEditorModule to inports

### ISSUE THREAD

**Issue by chambersDon** [chymz/ng2-ckeditor#37]
When I add CKEditorModule to my imports I get a runtime error:

> Error: SyntaxError: Unexpected token <

This happen before I try to add CKEditor to a page.  It was working find before I upgraded to RC6.

**Comment by chymz** [comment]
Can't help you if you don't share more core... which file produce this error ?

**Comment by chambersDon** [comment]
My application was working with ng2-CKEditor pre RC5.  I have converted to RC6 now and removed ng2-ckeditor and everything is working.  Now I want to add CKEditor.

In app.module.st, I add the import:
`import {CKEditorModule} from 'ng2-ckeditor';`

Then, in app.module.ts, I add CKEeitorModule to the imports section of NgModel.
```
@NgModule({
    imports: [BrowserModule, FormsModule, ReactiveFormsModule, routing, SimpleNotificationsModule, HttpModule,
        RepairReturnRouting, RepairReturnModule, SharedModule, RepairReturnSharedModule, CKEditorModule],
    exports: [SharedModule],
    providers: [SessionService,
        ConfigService,
        AlertService, AuthGuard, TokenService, 
        AuthHttp, { provide: AuthConfig, useFactory: () => { return new AuthConfig(); } },
        RepairReturnService],
    declarations: [AppComponent, AccountPasswordResetComponent, AccountConfirmationEmailComponent, MainLayoutComponent,
        HeaderComponent, TenantComponent, publicationListComponent, AccountPasswordChangeComponent,
        DashboardComponent, RepairReturnCountByStatus, RepairReturnCountByCountry, ManageComponent,
        RepairReturnListingComponent, UserComponent, TenantComponent, SplashComponent, LoginComponent,
        FormTestComponent],
    bootstrap: [AppComponent]
})
```

It compiles but I get the run time error:
```
Error: SyntaxError: Unexpected token <
at Object.eval (http://localhost:54675/lib/spa/app.module.js:36:24)
at eval (http://localhost:54675/lib/spa/app.module.js:73:4)
at eval (http://localhost:54675/lib/spa/app.module.js:74:3)
Evaluating http://localhost:54675/lib/js/ng2-ckeditor/lib/ckeditor
Evaluating http://localhost:54675/lib/spa/app.module.js
Evaluating http://localhost:54675/lib/spa/main.js
Error loading http://localhost:54675/lib/spa/main.js

```

Line 35 in app.module.js is:
`const ng2_ckeditor_1 = require('ng2-ckeditor');`


At this point I have not even added CKEditor to a page.  It's just the import.  If I remove CKEditorModule from imports I don't get an error.

This is the same systemjs.config that worked before the RC5/6 upgrade.  Here are the relevant parts:
```
 map: {
            'ng2-ckeditor': 'lib/js/ng2-ckeditor/lib/ckeditor'
        },
        packages: {
            'ng2-ckeditor': { defaultExtension: 'js' }
        }

```


Any ideas?
Is there anything else I can post that may help?

**Comment by chymz** [comment]
So you use systemjs ? This error appear when systemjs doesnt find the required file. 
I think your require('ng2-ckeditor') return a 404 html page, it came from you `map` config.

Try to change
```
map: {
  'ng2-ckeditor': 'lib/js/ng2-ckeditor/lib/ckeditor'
}
```
to
```
map: {
  'ng2-ckeditor': 'lib/js/ng2-ckeditor/lib/CKEditor.js'
}
```

Or you can watch `config.js` in this plunker : https://embed.plnkr.co/hnB0R3/
As you can see `map` go to root dir of CKEditor module and `package` is defined like this : 

```
{ main: 'lib/CKEditor.js', defaultExtension: 'js' }
```

**Comment by chambersDon** [comment]
That fixed it.  Thanks.  

Now I get an error on the tag.  

```
Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ckeditor'. ("span>
                                <ckeditor *ngIf="e.isEditMode" [(ngModel)]="e.formattedText" [ERROR ->][config]="{uiColor: '#337ab7'}"></ckeditor>
                            </div>

```

**Comment by chambersDon** [comment]
That fixed it.

This issue is resolved.

Thanks

**Comment by tom-startsat60** [comment]
I am having the same issue with my map and packages setup. It works fine in dev but when I build it doesn't work with the same issue mentioned as above. I am using Angular 2.0.0 with angular starter framework (https://github.com/antonybudianto/angular2-starter.git).

NgModules setup corretcly too.

If more information is needed please, any help would be great.
