### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by smith64fx** [chymz/ng2-ckeditor#4]
I tried to include your .js file in my browser but I get the error:

```
ReferenceError: exports is not defined
```
On line 3 in the ckeditor.js

**Comment by chymz** [comment]
Hi,
What packages manager/bundler do you use ?
Thanks !

**Comment by smith64fx** [comment]
Hey bro!
I'm using webpack. It seemed to load the component but not the necessary JS file. Do you have a example how to include it?

**Comment by chymz** [comment]
I'll try to make a sample repo based on angular2-seed !

**Comment by chymz** [comment]
You can find a sample with webpack here : https://github.com/chymz/angular2-seed-ckeditor

**Comment by smith64fx** [comment]
Hey man, thank you a lot :) now it works!

**Comment by smith64fx** [comment]
Can be closed

**Comment by tuanphamtps** [comment]
I can't access this link:  https://github.com/chymz/angular2-seed/tree/ng2-ckeditor

I got the same error: Uncaught ReferenceError: exports is not defined

**Comment by nickykiet83** [comment]
got the same error: Uncaught ReferenceError: exports is not defined

I can't access this link: https://github.com/chymz/angular2-seed/tree/ng2-ckeditor
