### ISSUE TITLE
How ckeditor.js can be bundled in the application

### ISSUE THREAD

**Issue by PACMAN49** [chymz/ng2-ckeditor#41]
How can we provide ckeditor.js to systemjs module loader so it can be bundeled with the application ?

**Comment by chymz** [comment]
I think you can't, the ckeditor 4.x doesn’t support JS modules atm.

Ckeditor team have fully rewrited their module, and JS modules are supported in 5.x, but still in alpha : https://ckeditor5.github.io/

**Comment by Reinmar** [comment]
You're right. CKEditor 4 would need to be wrapped into a ES6 module (should be a fairly simple task).

As for CKEditor 5, by coincidence, I've just wrote a few things on how the build process looks like and possible use case – https://github.com/ckeditor/ckeditor5/issues/345. Curious to have your opinion there.

**Comment by a2un** [comment]
When will the ckeditor5 be available for angular 4 and typescript

**Comment by Reinmar** [comment]
If you want to get your hands a bit dirty, you can integrate CKEditor 5 into your Angular app quite easily straight from source: https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/builds/guides/integration/advanced-setup.html

There's a topic about [CKEditor 5's compatibility with Angular](https://github.com/ckeditor/ckeditor5/issues/347). It's generally compatible, but [there's a problem if you use Angular CLI](https://github.com/ckeditor/ckeditor5/issues/347#issuecomment-329713429).

**Comment by a2un** [comment]
Hey..
I Just could bundle my project with ckeditor4 js files in my angular4 app  that uses angular webpack bundler

**Comment by SiddharthBhutoria** [comment]
@a2un  Can you tell what did you do to make it work?

**Comment by l443018** [comment]
Use angular cli^1.6.6, and this is work for me:
```
$ yarn add ng2-ckeditor
$ yarn add ckeditor
```

angular-cli.json
```
{
  "apps": [
    {
      "assets": [
        "assets",
        { "glob": "**/*", "input": "../node_modules/ckeditor/", "output": "./assets/scripts/ckeditor/" }
      ],
....
```

index.html
```
<script src="./assets/scripts/ckeditor/ckeditor.js"></script>
```

custom-editor.module.ts
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CKEditorModule } from 'ng2-ckeditor';
import { CustomEditorComponent } from './note-editor.component';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    CKEditorModule,
  ],
  declarations: [
    CustomEditorComponent,
  ],
  exports: [
    CustomEditorComponent,
  ]
})
export class CustomEditorModule { }
```
