### ISSUE TITLE
Installation missing instructions

### ISSUE THREAD

**Issue by IAMtheIAM** [chymz/ng2-ckeditor#43]
Installation says: **Include CKEditor javascript files in your application**

How exactly do we do that with webpack? Theres a million ways to get JS in your app with webpack. Please provide detailed instructions for webpack2 angular2 ckeditor setup.

**Comment by PACMAN49** [comment]
duplicate of #41  i think.

**Comment by chymz** [comment]
Yes it's a duplicate of #41 : you cannot bundle CKEditor 4.x with webpack.

**Comment by IAMtheIAM** [comment]
I see, well I got it to work with webpack and angular2. But youre right, webpack can't bundle it, only load the existing library as-is in the global context and execute at runtime.
