### ISSUE TITLE
Unexpected value 'CKEditorModule' on AOT compilation

### ISSUE THREAD

**Issue by unsafePtr** [chymz/ng2-ckeditor#45]
Hi everyone! I have added latest version of ng2-ckeditor to SharedModule to use it from each part of app.   When i tried to make an AOT compilation it was failed with error:

> Error: Unexpected value 'CKEditorModule' imported by the module 'SharedModule'

I found that this is due to the lack of ".metadata.json". Please add it in the next release. 
https://github.com/angular/angular/issues/11262#issuecomment-244439133

**Comment by chymz** [comment]
Duplicate of #36
