### ISSUE TITLE
Cannot access instance directly

### ISSUE THREAD

**Issue by davidrensh** [chymz/ng2-ckeditor#46]
It returns undefined when I want to access instance with
 `
import { CKEditorModule } from 'ng2-ckeditor'
....
<ckeditor [(ngModel)]="content" #ckeditor name="ckeditor" [config]="....

export class TempeditorComponent implements OnInit {
  ckeditor: any;
....
       console.log("Editor details:" + this.ckeditor);
`
Is there anything wrong?

**Comment by chymz** [comment]
You need to use `@ViewChild` decorator on you `ckeditor:any`

**Comment by chymz** [comment]
Here is the full code : 

```javascript
import { Component, ViewChild } from '@angular/core';
import template from 'app/app.component.html';

@Component({
  selector: 'my-app',
  template: `<ckeditor #ckeditor debounce="500">
  </ckeditor>`
})
export class AppComponent {

  @ViewChild('ckeditor') ckeditor:any;

  ngOnInit() {
    console.log(this.ckeditor);
  }

}
```

**Comment by davidrensh** [comment]
Awesome. It works.

**Comment by bradgreens** [comment]
Worth noting, in a large app, I had to wait for ng2-ckeditor's `(ready)="onReady($event)"` event to gain access to the instance. Thanks!

**Comment by AkhilAkku95** [comment]
It doesn't work on mine. it showing undefined. any solution

**Comment by kzimny** [comment]
@bradgreens and @AkhilAkku95 : what are you expecting? No instance => no assignment => no solution for so called "problem" which depend on your implementation. How looks you angular code? Any plunker? Provide your implementation and I will try to give you some advices.

**Comment by AkhilAkku95** [comment]
@kzimny I got the solution . Thanks for replying sir

**Comment by bradgreens** [comment]
Looks like I refactored out the `(ready)` code and it's working as expected. No issue here.
