### ISSUE TITLE
Module .../node_modules/ng2-ckeditor/lib/index.js does not export CKEditorModule

### ISSUE THREAD

**Issue by andrevcf** [chymz/ng2-ckeditor#48]
I'm using rollup.js to build and then receiving the error
`Module ..../node_modules/ng2-ckeditor/lib/index.js does not export CKEditorModule (imported by /.../src/app/app.module.ts`

Importing the module just like the doc provided:

```
import { CKEditorModule } from 'ng2-ckeditor';

@NgModule({
  // ...
  imports:      [
    CKEditorModule
  ],
  // ...
})
export class AppModule { }
```

**Comment by chymz** [comment]
Can you share your config / build script ? Works for me...

**Comment by andrevcf** [comment]
It is complicated because the build is actually done by the build of ionic-app-scripts.
my package.json is bellow:
``{
  "name": "ionic-hello-world",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "watch": "ionic-app-scripts watch",
    "serve:before": "watch",
    "emulate:before": "build",
    "deploy:before": "build",
    "build:before": "build",
    "run:before": "build",
    "dev": "lite-server"
  },
  "dependencies": {
    "@angular/router": "3.0.1",
    "@ionic/storage": "1.0.3",
    "angular2-jwt": "0.1.23",
    "angular2-text-mask": "^0.22.0",
    "atmosphere.js": "^2.3.2",
    "ionic-angular": "2.0.0-rc.0",
    "ionic-native": "2.0.3",
    "ionicons": "3.0.0",
    "primeng": "^1.0.0-beta.17"
  },
  "devDependencies": {
    "@ionic/app-scripts": "0.0.30",
    "typescript": "^2.0.3",
    "lite-server": "^2.2.2"
  },

}
``

**Comment by andrevcf** [comment]
I could run including ckeditor.component.ts, ckeditor.module.ts and index.ts on a folder ng2-ckeditor inside my project...

**Comment by chymz** [comment]
What is your **rollup** config ? Thanks !

**Comment by andrevcf** [comment]
tsconfig
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}

**Comment by andrevcf** [comment]
rollup.config.js

var nodeResolve = require('rollup-plugin-node-resolve');
var commonjs = require('rollup-plugin-commonjs');
var globals = require('rollup-plugin-node-globals');
var builtins = require('rollup-plugin-node-builtins');
var json = require('rollup-plugin-json');


// https://github.com/rollup/rollup/wiki/JavaScript-API

var rollupConfig = {
  /**
   * entry: The bundle's starting point. This file will
   * be included, along with the minimum necessary code
   * from its dependencies
   */
  entry: '{{SRC}}/app/main.dev.ts',

  /**
   * sourceMap: If true, a separate sourcemap file will
   * be created.
   */
  sourceMap: true,

  /**
   * format: The format of the generated bundle
   */
  format: 'iife',

  /**
   * dest: the output filename for the bundle in the buildDir
   */
  dest: 'main.js',

  /**
   * plugins: Array of plugin objects, or a single plugin object.
   * See https://github.com/rollup/rollup/wiki/Plugins for more info.
   */
  plugins: [
    builtins(),
    commonjs(),
    nodeResolve({
      module: true,
      jsnext: true,
      main: true,
      browser: true,
      extensions: ['.js']
    }),
    globals(),
    json()
  ]

};


if (process.env.IONIC_ENV === 'prod') {
  // production mode
  rollupConfig.entry = '{{TMP}}/app/main.prod.ts';
  rollupConfig.sourceMap = false;
}


module.exports = rollupConfig;

**Comment by chymz** [comment]
Hi @andrevcf did the latest version fix your problem ? Thanks !

**Comment by chymz** [comment]
Not activity, closing...

**Comment by rashmim00** [comment]
Hi, I am experiencing same error with version 4. I did everything outlined in readme file. 

Sorry for being so ignorant but there is no lib folder in ng2-ckeditor and my tsconfig file excludes node_modules so how to get lib/index.ts. Do help me.  thank you.

**Comment by rashmim00** [comment]
I am experiencing same error with version 4. How to resolve this. 
my tsconfig looks good. I don't have rollup.config.

Thanks
