### ISSUE TITLE
Inline Edit

### ISSUE THREAD

**Issue by smith64fx** [chymz/ng2-ckeditor#5]
Hey there,
Sorry for creating issues, maybe a Slack Channel / Gitter / any other Chat would be nice for small things like this :)

I like to enable the inline editing function, how is this done?

**Comment by chymz** [comment]
Hi again!

This feature is not implemented yet. I'll try to work on this soon.

**Comment by smith64fx** [comment]
I made it to work!

```
<h1 contenteditable="true" >{{ element.value }}</h1>
```

It also works without the directive. Just with the included ckeditor.js file. I will test this out. Really great feature!

**Comment by chymz** [comment]
I didn't find a real use case for this, i close it for now

**Comment by BBegouin** [comment]
@smith64fx could you please provide some more details ? because just with the contenteditable=true and the script loaded, it doesn't seems to work for me...
Did I missed something ? 

cheers.

**Comment by rmcsharry** [comment]
@BBegouin You do not actually need ng2-ckeditor to use inline mode. You just need to add the library using a script tag in your index.html head.

ng2-ckeditor allows you to create an instance of the editor as an Angular component:
<ckeditor></ckeditor>

But if you are using ng2-ckeditor, then you already loaded the ckeditor.js files (via npm basically) so you don't need to add it again to index.html as script tag.

So, either way, the library is loaded and all you need for inline editing is to do exactly as @smith64fx said - add `contenteditable="true" `to ANY element you want inline editing.

So **NOT** this:

`<ckeditor contenteditable="true"></ckeditor>`

as that is trying to tell the angular component you want it to switch to inline (impossible).

Instead, replace your ckeditor with a standard HTML element that you want to have inline editing on, eg:

```
<div contenteditable="true">
</div>

```

Docs [here](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_inline).

**Comment by rmcsharry** [comment]
I tried this also, and that is what it says in the docs [here](https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_inline)

but it does not work. @smith64fx can you provide more details please?

**Comment by rmcsharry** [comment]
There is a directive [here](https://gist.github.com/FluffierThanThou/62dbae7426c4c5930880b6ca8eb625a9), but that seems overkill if we only need to use contenteditable="true"!

**Comment by rmcsharry** [comment]
I figured out how to do this. Very simple. Solution posted [here](https://stackoverflow.com/questions/43511437/how-to-use-ng2-ckeditor-as-inline/46733219#46733219).
