### ISSUE TITLE
use of extraPlugins

### ISSUE THREAD

**Issue by ThomasLeclerc** [chymz/ng2-ckeditor#53]
Hi i'm trying to use the uploadimage plugin but when I put `extraPlugins: 'uploadimage'` in config, it tries to get it at http://cdn.ckeditor.com/4.5.8/full/plugins/uploadimage/plugin.js/ which gives 404.

So is it an error or do I have to manually install the plugin ? if that's the case how to do it ?

**Comment by chymz** [comment]
This plugin is not part of full package of CKEditor.

It's external, so you have to put CKEditor locally and put this plugin manually in `plugins` directory.

**Comment by darivb** [comment]
what do you mean locally? I want to use codesnippet plugin, should it be located under /node_modules/ng2-ckeditor/ckeditor/plugins/codesnippet?

**Comment by chymz** [comment]
Please read the docs : http://docs.ckeditor.com/#!/guide/dev_plugins

**Comment by darivb** [comment]
thanks!
