### ISSUE TITLE
Webpack installation

### ISSUE THREAD

**Issue by jarrettj** [chymz/ng2-ckeditor#54]
Hi, good day.

How do you use this editor with webpack?

**Comment by rogueRabbit** [comment]
I want to ask the same question, If you have time, please help us, Thank you very much!

**Comment by claboran** [comment]
Hi,

had the same issue. Any help appreciated.

**Comment by chymz** [comment]
See #41

**Comment by mourahi** [comment]
1/   copy this file "ckeditor.componet.ts" to your src directory.
2/ add to your app component file : 
`import {CKEditorComponent} from './ckeditor.component';
declare var CKEDITOR : any;` 
3/add "<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>" to your index.html file, inside header tag.
4/<ckeditor
    [(ngModel)]="ckeditorContent"
    [config]="{uiColor: '#99000'}"
    (change)="onChange($event)"
    (ready)="onReady($event)"
    (blur)="onBlur($event)"
    debounce="500">
  </ckeditor>

**Comment by claboran** [comment]
Hi Adil, thanks for your help. Do you have any idea how to get it up without having to include the CKEDITOR from the CDN? I wanted to get it by npm. Here I struggled with Webpack. It seems that the recommended approach, including the js with the _angular-cli.json_ does not work. 
Thanks in advance.

Christian

**Comment by morriq** [comment]
answer for @claboran question would be very useful. :)

**Comment by chymz** [comment]
@claboran , please see #41 : you can't bundle CKEditor with webpack...

**Comment by mourahi** [comment]
Hi Christian,
ckeditor is working for me in webpack with only cdn. 
I 'am sorry, i don't have any idea to get it up without having to include the CKEDITOR from the CDN.

Adil MOURAHI

**Comment by morriq** [comment]
Hello.
Of course you can use CKEditor with webpack. you just need to use CopyWebpackPlugin with something like this: {from: '../node_modules/ckeditor', to: 'ckeditor'}

and set proper path in window.CKEDITOR_BASEPATH (='/ckeditor/')

**Comment by claboran** [comment]
@mourahi: Thanks for the help. I will take the simpler approach and use it via CDN for now. 
@morriq - In the next free slot, I will give the CopyWebpackPlugin a try as well ... 
Thanks for your help.

**Comment by Bhavin990** [comment]
i'm using ckeditor with angular 2 meanwhile i facing issue,  so please help us 
 XHR error (404 Not Found) loading http://localhost:3001/ng2-ckeditor
Error loading http://localhost:3001/ng2-ckeditor as "ng2-ckeditor" from http://localhost:3001/app/app.module.js

**Comment by SiddharthBhutoria** [comment]
@claboran did you try implementing @morriq solutions? if yes, is it working?

**Comment by SiddharthBhutoria** [comment]
@morriq I didn't get  understand  it clearly copyWebpackPlugin part. Could you please clarify or elaborate?

**Comment by chinthu** [comment]
@morriq Any update on this, did you got ckeditor running  ?
