### ISSUE TITLE
Apply skin

### ISSUE THREAD

**Issue by BenDevelopment** [chymz/ng2-ckeditor#55]
I've downloaded a skin created with the CKE skin builder but it's not well applied.
The buttons are still yellow.
This is how I did:

- Build the editor from here http://ckeditor.com/builder
- Copy the ckeditor download folder in my project assets folder
- Replace the CDN by the new editor folder:
  - `<script src="assets/third-party/ckeditor/ckeditor.js"></script>`

The background and the border has changed that mean that the new editor is well loaded. There is only this problem with the buttons which doesn't changes.

**Comment by BenDevelopment** [comment]
Forged this, it was a problem in my code.

**Comment by Gyoo** [comment]
Hello @BenDevelopment 
I am currently facing the exact same issue. How did you solve this ?

**Comment by BenDevelopment** [comment]
I don't remeber what was my problem but it was not a ckeditor probem. Are you sure you are pointing to the correct path with your js and css ?

**Comment by Gyoo** [comment]
My JS is correctly pathed, however I didn't do anything regarding CSS files. I thought the JS file loaded them directly ?

**Comment by BenDevelopment** [comment]
Yes you're right, I haven't used ckeditor for a long time. I'm afraid I can not help you with this problem :(.
