### ISSUE TITLE
Dialog Open Bug

### ISSUE THREAD

**Issue by medberg** [chymz/ng2-ckeditor#6]
When a particular dialog is clicked open for the second time the screen grays out but the dialog itself doesn't show up. It doesn't seem to matter which dialog - link, table, etc., they all do this.

![screen shot 2016-05-03 at 10 47 18 am](https://cloud.githubusercontent.com/assets/16408728/14989232/6eeceeaa-111c-11e6-86a1-801af47f7d38.png)

I am including the standard CKEditor package, however they all seem to do this:

`<script src="https://cdn.ckeditor.com/4.5.8/standard/ckeditor.js"></script>`

P.S. - Fantastic job on this so far.

**Comment by chymz** [comment]
Thanks !

Well, I tested with the sample repo (https://github.com/chymz/angular2-seed-ckeditor) on latest Chrome & FF but I can't reproduce your problem.

Can you share some code ? I think it's more a CKEditor bug...

**Comment by medberg** [comment]
Interesting, I feel like I might be missing something then. I installed via NPM as instructed and have the following relevant code in index.html:

```
    <script src="https://cdn.ckeditor.com/4.5.8/standard/ckeditor.js"></script>

    <script>
        System.config({
            packages: {
                "app": {
                    "format": 'register',
                    "defaultExtension": 'js'
                },
                "ng2-ckeditor": {
                    "defaultExtension": "js"
                }
            },
            map: {
                "ng2-ckeditor": "node_modules/ng2-ckeditor/lib/CKEditor.js"
            }
        });
        System.import('app/main').then(null, console.error.bind(console));
    </script>
```

Does this look right? To be honest I am new to SystemJS and wasn't quite sure about that piece. Thanks!

**Comment by medberg** [comment]
Closed, after further investigation this is a bug with the dialog plugin. For some reason in my build the container that dialogs get put into is not being set back to a block display after being hidden:

![screen shot 2016-05-05 at 1 05 04 pm](https://cloud.githubusercontent.com/assets/16408728/15052236/389eafd0-12c2-11e6-990f-3cd3b0407728.png)

Obviously the first path is always being taken for some reason.
