### ISSUE TITLE
How can we listen events in ckeditor like keyup and keydown?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [chymz/ng2-ckeditor#60]
Hey, I read various document in ckeditor to listen keyup events like one
CKEDITOR.on('currentInstance', function(){modified = true;});
but my question is how we implement in angular 2. I used this but it is getting error:
<ckeditor #ckeditor [(ngModel])="xyz">
I used like 
@ViewChild('ckeditor') public ckeditor: Ckeditor;

How we used keyup events in this case? Please help me soon

**Comment by chymz** [comment]
See : https://github.com/chymz/ng2-ckeditor/issues/39#issuecomment-255682421
You can listen on any CKEditor events.

Or make a PR like this : https://github.com/chymz/ng2-ckeditor/pull/58
