### ISSUE TITLE
how to open & edit & save word document or any text document in ng2-ckeditor ?

### ISSUE THREAD

**Issue by partha006** [chymz/ng2-ckeditor#63]
I need to open text file and i can able to edit using the tools in ng2-ckeditor and save the document in the same or different file name. How to do that in ng2-ckeditor . If not Kindly suggest any other way to this.

**Comment by chymz** [comment]
It's not a ng2-ckeditor question, more a JS question...

A search trail : https://developer.mozilla.org/fr/docs/Web/API/File
