### ISSUE TITLE
How can i Capture paste event

### ISSUE THREAD

**Issue by adrianeguez** [chymz/ng2-ckeditor#64]
Hello,

I tried to bind the paste event in the inicialization of the ckeditor as this:
```
<ckeditor [(ngModel)]="content" 
debounce="500" 
(paste)="onPaste($event)">

<p>Hello <strong>world</strong></p>

</ckeditor>
```
And in the Class there is my method "onPaste"

`onPaste(e){
    console.log(e);
  }
`

Unfortunately the event is not logged.

What should I do?

**Comment by chymz** [comment]
See : https://github.com/chymz/ng2-ckeditor/issues/60#issuecomment-261741145
