### ISSUE TITLE
Installation with angular-seed not working

### ISSUE THREAD

**Issue by brightonhall** [chymz/ng2-ckeditor#67]
I'm getting the error:

    (SystemJS) XHR error (404 Not Found) loading http://localhost:5556/node_modules/ng2-ckeditor.js

I'm referencing the module in my SharedModule where other modules are imported.

    import { CKEditorModule } from 'ng2-ckeditor';

In my project.config.ts file, I have this set:

    this.APP_ASSETS = [
      ...this.APP_ASSETS,
      { src: `${this.CSS_SRC}/font-awesome/css/font-awesome.min.css`, inject: true, vendor: false },
      { src: '//cdn.ckeditor.com/4.5.11/full/ckeditor.js', inject: true, vendor: false }
    ];

In my seed.config.ts file, I have this:

      SYSTEM_CONFIG_DEV: any = {
        defaultJSExtensions: true,
        paths: {
          [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
          '@angular/common': 'node_modules/@angular/common/bundles/common.umd.js',
          '@angular/compiler': 'node_modules/@angular/compiler/bundles/compiler.umd.js',
          '@angular/core': 'node_modules/@angular/core/bundles/core.umd.js',
          '@angular/forms': 'node_modules/@angular/forms/bundles/forms.umd.js',
          '@angular/http': 'node_modules/@angular/http/bundles/http.umd.js',
          '@angular/platform-browser': 'node_modules/@angular/platform-browser/bundles/platform-browser.umd.js',
          '@angular/platform-browser-dynamic': 'node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
          '@angular/router': 'node_modules/@angular/router/bundles/router.umd.js',
    
          '@angular/common/testing': 'node_modules/@angular/common/bundles/common-testing.umd.js',
          '@angular/compiler/testing': 'node_modules/@angular/compiler/bundles/compiler-testing.umd.js',
          '@angular/core/testing': 'node_modules/@angular/core/bundles/core-testing.umd.js',
          '@angular/http/testing': 'node_modules/@angular/http/bundles/http-testing.umd.js',
          '@angular/platform-browser/testing': 'node_modules/@angular/platform-browser/bundles/platform-browser-testing.umd.js',
          '@angular/platform-browser-dynamic/testing': 'node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js',
          '@angular/router/testing': 'node_modules/@angular/router/bundles/router-testing.umd.js',
          'ng2-ckeditor': 'node_modules/ng2-ckeditor',
          'primeng': 'node_modules/primeng',
          'app/*': '/app/*',
          // For test config
          'dist/dev/*': '/base/dist/dev/*',
          '*': 'node_modules/*'
        },
        packages: {
        }
      };
     
  
    SYSTEM_BUILDER_CONFIG: any = {
        defaultJSExtensions: true,
        base: this.PROJECT_ROOT,
        packageConfigPaths: [
          join('node_modules', '*', 'package.json'),
          join('node_modules', '@angular', '*', 'package.json')
        ],
        paths: {
          // Note that for multiple apps this configuration need to be updated
          // You will have to include entries for each individual application in
          // `src/client`.
          [join(this.TMP_DIR, this.BOOTSTRAP_DIR, '*')]: `${this.TMP_DIR}/${this.BOOTSTRAP_DIR}/*`,
          'dist/tmp/node_modules/*': 'dist/tmp/node_modules/*',
          'node_modules/*': 'node_modules/*',
          '*': 'node_modules/*'
        },
        packages: {
          '@angular/common': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/compiler': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/core/testing': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/core': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/forms': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/http': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/platform-browser': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/platform-browser-dynamic': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          '@angular/router': {
            main: 'index.js',
            defaultExtension: 'js'
          },
          'rxjs': {
            main: 'Rx.js',
            defaultExtension: 'js'
          },
          'ng2-ckeditor': {
            main: 'lib/index.js',
            defaultExtension: 'js',
          },
          'primeng': {
            main: './primeng.js',
            defaultExtension: 'js'
          }
        }
      };  
    
 
 Any help is appreciated.

**Comment by gauravsoni119** [comment]
Hi @brightonhall ,
Either you need to give path to ckeditor.js in index.html as  <script>https://cdn.ckeditor.com/4.5.11/full/ckeditor.js</script> or you need to download ckeditor from http://ckeditor.com/download and then add to project.config.ts inside this.APP_ASSETS as following:-
{ src: `${this.ASSETS_SRC}/ckeditor/ckeditor.js`, inject: true, vendor: false }

**Comment by chymz** [comment]
Sorry but there are a lots of angular-seed projects, which one ?
Thanks !

**Comment by gauravsoni119** [comment]
I described an example of https://github.com/mgechev/angular-seed

**Comment by brightonhall** [comment]
This is my seed project: https://github.com/mgechev/angular-seed.

@gauravsoni119 - I installed ckeditor via NPM.  Can I not use ckeditor via NPM, or must I include it just via the script tag?  If I use the download method, where does it live? Do I download it to a folder in my app?  You can see I'm confused with this, and I'm wondering why the NPM installed method doesn't work.

But the actual error says it can't find ng2-ckeditor.js, not ckeditor.js.  So why is that happening?

**Comment by gauravsoni119** [comment]
@brightonhall  - Please take look at https://embed.plnkr.co/hnB0R3/. You can either download ckeditor from http://ckeditor.com/download and place it into inside assets folder or you can add it like:-
<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script> in index.html.
Then you need to install package by command "npm install ng2-ckeditor".

**Comment by KillerCodeMonkey** [comment]
@brightonhall you need to set the correct path to ng2-ckeditor

```
'ng2-ckeditor': 'node_modules/ng2-ckeditor',
```
sets only the path to the folder. So SystemJS search this file:

`node_modules/ng2-ckeditor.js`

Users had similar issues with my ngx-quill project and angular-seed.
Per default only the SYSTEM_CONFIG_DEV is used! So you need to specify the correct path there.

Try:

1. `'ng2-ckeditor': 'node_modules/ng2-ckeditor/lib/index.js'`
2. sometimes you need to specify the correct module type like commonjs, there you add ng2-ckeditor to the empty `packages` object in the SYSTEM_CONFIG_DEV

```
packages: {
  'ngx-quill': {
    format: 'cjs'
  }
}
```

And that is why i do not like huge seed project --> because the magic that happens ;)

**Comment by tonychangcheng** [comment]
I fixed the issue by adding below config

seed.config.ts: 
      'ng2-ckeditor': 'node_modules/ng2-ckeditor/lib/index.js',

      'ng2-ckeditor': {
        main: 'lib/index.js',
        defaultExtension: 'js'
      }

project.config.ts
    this.NPM_DEPENDENCIES = [
      ...this.NPM_DEPENDENCIES,
      ...
      {src: 'ckeditor/ckeditor.js', inject: 'libs'},
    ];
