### ISSUE TITLE
Is it possible to resize the editor

### ISSUE THREAD

**Issue by AshMcConnell** [chymz/ng2-ckeditor#69]
Is it possible to resize the editor to 100% height? (and handle window resizing)

Thanks!
Ash

**Comment by mwamufiya** [comment]
ckEditor does have an auto grow on startup configuration. I'd recommend leveraging the ckEditor properties rather than looking for ng2-ckeditor to re-invent the wheel here.

http://docs.ckeditor.com/#!/api/CKEDITOR.config
