### ISSUE TITLE
toolbar:basic not working 

### ISSUE THREAD

**Issue by sergeu90** [chymz/ng2-ckeditor#70]
<ckeditor [(ngModel)]="ckeditorContent" [config]="{uiColor:'#858580',toolbar:'Basic'}" debounce="500" [ngModelOptions]="{standalone: true}">

**Comment by chymz** [comment]
Did you defined your 'Basic' toolbar before using it ?

**Comment by sachq** [comment]
**Inside your Component template file**
`<ckeditor [(ngModel)]="ckeditorContent" [config]="ckEditorConfig" debounce="500" [ngModelOptions]="{standalone: true}">`

**Inside your app.component.ts file**
```
export class AppComponent {
  public ckEditorConfig: any = {
   toolbar: 'Basic',
   toolbar_Basic: ['Bold', 'Italic'] /* you can add more tools to the list */
  }
}
```

To understand more on CKEditor, Follow the below link,
[CKEditor Config](http://docs.ckeditor.com/#!/api/CKEDITOR.config)

**Comment by VireshRajvansh** [comment]
@sachq 
 i use your code but toolbar Basic disable all the icons and tool of the  ckeditor why?
