### ISSUE TITLE
customize toolbar 

### ISSUE THREAD

**Issue by hardslk** [chymz/ng2-ckeditor#73]
how to customize the toolbar?
I put this customconfig file but don't work
CKEDITOR.editorConfig = function( config ) {

	// %REMOVE_START%
	// The configuration options below are needed when running CKEditor from source files.
	config.plugins = 'dialogui,dialog,about,a11yhelp,basicstyles,blockquote,clipboard,panel,floatpanel,menu,contextmenu,resize,button,toolbar,elementspath,enterkey,entities,popup,filebrowser,floatingspace,listblock,richcombo,format,horizontalrule,htmlwriter,wysiwygarea,indent,indentlist,fakeobjects,link,list,magicline,maximize,pastetext,pastefromword,removeformat,sourcearea,specialchar,menubutton,scayt,stylescombo,tab,undo,wsc,panelbutton,colorbutton,colordialog,docprops,docfont,font,format_buttons,justify,pbckcode,indentblock,inlinecancel,closebtn,inlinesave,floating-tools';
	// config.skin = 'office2013';
	// %REMOVE_END%

	// Define changes to default configuration here.
	// For complete reference see:
	// http://docs.ckeditor.com/#!/api/CKEDITOR.config

	// The toolbar groups arrangement, optimized for two toolbar rows.
	config.toolbarGroups = [
		{ name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
		{ name: 'insert' },
		{ name: 'forms' },
		{ name: 'tools' },
		{ name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
		{ name: 'styles' },
		{ name: 'colors' },
		{ name: 'about' },
    { name: 'font' }
	];

	// Remove some buttons provided by the standard plugins, which are
	// not needed in the Standard(s) toolbar.
	config.removeButtons = 'Underline,Subscript,Superscript';

	// Set the most common block elements.
	config.format_tags = 'p;h1;h2;h3;pre';

	// Simplify the dialog windows.
	config.removeDialogTabs = 'image:advanced;link:advanced';
};

**Comment by mwamufiya** [comment]
Use @ViewChild in the host component to obtain the instance of CK editor, then simply set the config properties that you want as you normally would.


````
import (CKEditorComponent) from 'ng2-ckeditor';

export class MyClas implements AfterViewInit{`
    @ViewChild(CKEditorComponent) ckEditor:CKEditorComponent; //<---- Get the CKEditor Angular component

    //In looking at ng2-ckeditor, most of the work is being done after view init. so you'll need to make sure your sure to execute your code after that is complete
    ngAfterViewChecked(){
       let editor = this.ckEditor.instance;

       editor.config.toolbarGroups = [
            { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
            { name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] }
        ]

        editor.config.removeButtons = 'Source,Save,Templates,Find,Replace,Scayt,SelectAll,Form,Radio';
   }
}
````

An even better approach would be to capture the "ready" event that is emitted by the the ckEditor component. and perform this action when the CK editor is ready. Thereby ensuring the ckEditor Instance is ready for use.

````
<ckeditor (ready)="setToolbars()"> </ckeditor>
````

Then in your "setToolbars()" method, you do the same work.

**Comment by hardslk** [comment]
Thanks,Great job.now I can customize toolbar as per my requirements.
