### ISSUE TITLE
Problem with ckeditor data binding

### ISSUE THREAD

**Issue by milen4eto** [chymz/ng2-ckeditor#74]
Hello, I have a small problem with this CkEditor ngModel data binding. It's not working properly on a 100%.
When I use tables, justify buttons and code snippet button, the data preview is different, than the text in the editor. Is someone knows how to correct this problem? Please help, because this styles are important for me :) Thanks in advance :)

There is a [picture](https://www.dropbox.com/s/wxq6wehe6877ecv/Screenshot%202017-02-02%2010.52.31.jpg?dl=0) of a problem if someone can't understand me:

**Comment by chymz** [comment]
CKEditor question, see this : http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-contentsCss
