### ISSUE TITLE
CKEditor Configuration, why it remove id in span attribute?

### ISSUE THREAD

**Issue by conqsys** [chymz/ng2-ckeditor#78]
my ckeditor has this configuration: config.allowedContent = true

If I insert this code into my editor:

```
<div class="col-xs-12">
 <input type="text" name="LastName" class="form-control" id="LastName">
        <div class="help-block animated fadeInDown">
        <span id="errLastNameMsg"></span>
       </div>
    </div>
```

this is a simple id `<span id="errLastNameMsg"></span>` with span content.

After Ckeditor compile it is.
 ```
<div class="col-xs-12"><input class="form-control" id="LastName" 
    name="LastName" type="text" /> 
    <div class="help-block animated fadeInDown">&nbsp;</div>
    </div>

```

It Strip `<span id="errLastNameMsg"></span>` `with &nbsp;`

thanks in advance for your's solution.

**Comment by chymz** [comment]
It's a ckeditor question, see this : http://stackoverflow.com/questions/18261198/ckeditor-removing-empty-span-automatically
