### ISSUE TITLE
Bind with form Control

### ISSUE THREAD

**Issue by amirduran** [chymz/ng2-ckeditor#80]
Is it possible to bind Editor with FormControl object?
Is it possible to provide to the Editor an Observable object?

**Comment by chymz** [comment]
Can you clarify your needs ?
What do you mean by "bind Editor with FormControl" ?
What is the goal of Observable here ?

Thanks !

**Comment by mwamufiya** [comment]
Yes it is.  
With dynamic forms you will need to create the form control prior to instantiating the CkEditor. In this example, the question.key points to a FormControl within a FormGroup whose id == question.key

`<ckeditor`
`        [formControlName]="question.key"`
`        [config]="ckEditorConfig"`
`        debounce="250">`
`</ckeditor>`
