### ISSUE TITLE
On refresh getting ReferenceError: CKEDITOR is not defined

### ISSUE THREAD

**Issue by shofman10** [chymz/ng2-ckeditor#83]
In my angular application, if I naturally navigate to a page with ckeditor on it, I don't get this error, but if I refresh the specific page(F5) that has this ckeditor on it, I get the following error: 

Exception: Call to Node module failed with error: ReferenceError: CKEDITOR is not defined
at CKEditorComponent.ckeditorInit (C:\Projects\MVC-BZS-KnowledgeBase\src\KnowledgeBase.Web\node_modules\ng2-ckeditor\lib\ckeditor.component.js:71:14)...

Seems like a fix was provided in #61 but I'm still receiving this error

**Comment by EdByrnee** [comment]
+1

Getting this error regardless of navigation method.

**Comment by chymz** [comment]
Can you please share some code ? 
Can you reproduce this on plunker : https://embed.plnkr.co/hnB0R3/ ?
Do you use Angular Universal ?
