### ISSUE TITLE
ngModel / Error

### ISSUE THREAD

**Issue by kamalkech** [chymz/ng2-ckeditor#84]
```
<ckeditor
    [(ngModel)]="article.description"
    [config]="{uiColor: '#99000'}"
    (change)="onChange($event)"
    (ready)="onReady($event)"
    (focus)="onFocus($event)"
   (blur)="onBlur($event)"
   debounce="500">
</ckeditor>
```

Error message : If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.

Any idea ?

**Comment by mwamufiya** [comment]
as the error implies, you need to add a "name" property to your form control. ie: name="randomName"

**Comment by kamalkech** [comment]
@mwamufiya yeh that what i do and it's work fine and i forget to close issue and thank you for your answer
