### ISSUE TITLE
Error self.context.myFunction using @Output

### ISSUE THREAD

**Issue by crisiiii** [chymz/ng2-ckeditor#89]
Hi,

I'm getting a problem with the @Output directive. This is my code:

**representatives-list.component.ts**
```
@Output() selected = new EventEmitter();
showRepresentative(event){  		
     this.selected.emit(event.data);
}
```
**app.component.html**
`<ar-representatives-list (selected)="onRepresentativeSelected(data)"></ar-representatives-list>`

**app.component.ts**
```
onRepresentativeSelected(data){
	console.log(data);
}
```

When the `selected `event it's emitted, it returns the following error:
`Uncaught TypeError: self.context.onRepresentativeSelected is not a function`

What's happening?

**Comment by chymz** [comment]
What does your problem have to do with this plugin ?
