### ISSUE TITLE
Add support to Angular Cli

### ISSUE THREAD

**Issue by ShakurOo** [chymz/ng2-ckeditor#90]
Please add support to angular cli. I have to import manually the script in the index.html...
`<script src="https://cdn.ckeditor.com/4.6.1/full/ckeditor.js"></script> `

When I add the path in the angular-cli.json, i have the following alert : 
`CKEditor 4.x is missing (http://ckeditor.com/)`

**Comment by chymz** [comment]
It's not possible to include CKEditor 4.x in webpack bundles due to its plugins system.

See : https://github.com/chymz/ng2-ckeditor/issues/41#issuecomment-250254364
