### ISSUE TITLE
Value not updated in the view

### ISSUE THREAD

**Issue by JurajLigo** [chymz/ng2-ckeditor#91]
My html code is:
`<ckeditor #editor
                  [(ngModel)]="service.description"
                  [ngModelOptions]="{standalone: true}">
          </ckeditor>`

My typescript code in constructor is like this:
`servicesService.getServiceByIdFromApi(id).then(
                        (service) => {
                            this.service = service;
                          
                        }
                    );`

the attribute service.description is not empty has always value, problem is that 
no value in the view is shown and ckeditor is empty despite when i debug it the property
_value of ckeditor is filled with correct value. I have no idea why the view doesnt show this value
When i remove calling service `servicesService.getServiceByIdFromApi(id) and hard set this.service = service in the constructor everything works fine. What is the problem ? Is it problem with Promise and then clausule in the calling service or why the value isnt shown in the view

thanks

**Comment by kzimny** [comment]
seems not to be a problem with ckeditor but. Have you tried to load your value with promise?

**Comment by JurajLigo** [comment]
Yes I load my value using Promise and i think that is the problem because without calling Promise everything works fine. So I think calling with Promise is problem. What do you think ?

**Comment by kzimny** [comment]
It depends on the architecture you have implemented. We don't use promis in our application.

**Comment by JurajLigo** [comment]
So with Promises it doesnt work correctly ?

**Comment by kzimny** [comment]
this is not an issue with ng2-ckeditor, I think it something is wrong with your angular code

**Comment by JurajLigo** [comment]
Could you please show me plunker code with ng2-ckeditor working with value from Promise ? I saw just examples where value is set directly in constructor. this also works for me but  i need value from Promise

**Comment by kzimny** [comment]
you can find a good example here [https://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html](url). I would recommend to ask questions about angular in other forums.
