### ISSUE TITLE
How to include autogrow plugin?

### ISSUE THREAD

**Issue by amirduran** [chymz/ng2-ckeditor#92]
I want to enable auto grow functionality explained here: http://sdk.ckeditor.com/samples/autogrow.html

How can I import additional autogrow plugin in my ng2-ckeditor?

**Comment by labyed** [comment]
hey, i got the same issue, did u manage the problem? ty

**Comment by denispodtykan** [comment]
> hey, i got the same issue, did u manage the problem? ty
instead 
	<script src="https://cdn.ckeditor.com/4.5.11/full/ckeditor.js"></script>
add
	<script src="https://cdn.ckeditor.com/4.5.11/**standard-all**/ckeditor.js"></script>
and add **extraPlugins:'autogrow'**, in congif
