### ISSUE TITLE
why is ckbutton not visible in toolbar

### ISSUE THREAD

**Issue by kzimny** [chymz/ng2-ckeditor#93]
I added ckbutton to toolbar as follow:

`import { Component, Input, OnInit } from "@angular/core";
import { NgForm } from "@angular/forms";

@Component({
    selector: "app-html-control",
    template: `
                <ckeditor
                    [config]="ckeConfig"
                    debounce="500">
                        <ckbutton [name]="'xyz'"
                          [command]="'saveXyz'"
                          [icon]="'save.png'"
                          [label]="Custom action'"
                          [toolbar]="'styles,1'">
                        </ckbutton>
                  </ckeditor>
`,
})
export class HtmlControlComponent implements OnInit {

    ckeConfig: any;

    constructor() { }

    ngOnInit() {

        this.ckeConfig = {
            height: 400,
            toolbar: [
                { name: 'editing', items: ['Scayt', 'Find', 'Replace', 'SelectAll'] },
                { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'] },
                { name: 'links', items: ['Link', 'Unlink', 'Anchor'] },
                { name: 'insert', items: ['Image', 'Table', 'HorizontalRule', 'SpecialChar', 'Iframe'] },
                { name: 'tools', items: ['Maximize', 'ShowBlocks', 'Preview', 'Print', 'Templates'] },
                { name: 'document', items: ['Source'] },
                '/',
                { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat'] },
                { name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', 'CreateDiv', '-', 'Blockquote'] },
                { name: 'justify', items: ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] },
                { name: 'styles', items: ['Styles', 'Format', 'FontSize', '-', 'TextColor', 'BGColor'] }
            ]
        };
    }
}`

Whe is ckbutton is not visible in the toolbar? There is no error message...

**Comment by g-schmitz** [comment]
Hi, looks like this is the default behavoir of ckeditor. You would've to use the `toolbarGroups` property instead like mentioned here:
http://ckeditor.com/apps/ckeditor/4.4.0/samples/plugins/toolbar/toolbar.html

**Comment by kzimny** [comment]
I solved the problem. The new button `<ckbutton [name]="'xyz'" [command]="'saveXyz'" [icon]="'save.png'" [label]="Custom action'" [toolbar]="'styles,1'"> </ckbutton>` need to be added to the toolbar configuration part. 
`this.ckeConfig = {
        height: 400,
        toolbar: [
            { name: 'styles', items: [**'xyz'**, 'Styles', 'Format', 'FontSize', '-', 'TextColor', 'BGColor'] }
        ]
    };`

**Comment by hellosandeep** [comment]
If you are unable to see all editor icon try to change js file path 

`<script src="http://cdn.ckeditor.com/4.7.1/full/ckeditor.js"></script> `
