### ISSUE TITLE
How do cheditor as ready only 

### ISSUE THREAD

**Issue by RobertRajcool** [chymz/ng2-ckeditor#94]

**Comment by kzimny** [comment]
read only on Startup:
[http://docs.ckeditor.com/#!/guide/dev_readonly](url)

`this.ckeConfig = {
            height: 400,
            readOnly: true
 };`

or from event `this.ckeditor.instance.setReadOnly()`

**Comment by RobertRajcool** [comment]
@kzimny thanks its working
