### ISSUE TITLE
Model not updating when in source mode

### ISSUE THREAD

**Issue by AshMcConnell** [chymz/ng2-ckeditor#95]
Hi Folks,

I have noticed if the user updates the editor in "source mode" the model doesn't get updated.  Is there a workaround for this?  Our users quite regularly will switch to source mode and press save without switching back to WYSIWYG.

Thanks!
Ash

**Comment by kzimny** [comment]
we solved this issue by getting editor data from ckeditor instance like as follow:
`let data = this.ckeditor.instance.getData();`
hope this will solve your problem. ;-)

**Comment by AshMcConnell** [comment]
Thanks, I'll see if we can get round the issue with this workaround

**Comment by tbcashy** [comment]
@kzimny @AshMcConnell Had the same issue and the fix works just fine. :+1:

**Comment by tbcashy** [comment]
@kzimny @AshMcConnell To create a global workaround I tried this and it works for me:

`    this.instance.on('key', () => {
      setTimeout(() => {
        let value = this.instance.getData();
        this.updateValue(value);
      },0);
    });`

Just insert this snippet on the bottom of ckeditorInit.
