### ISSUE TITLE
How to upload image from my computer using ckeditor?

### ISSUE THREAD

**Issue by trinhsong** [chymz/ng2-ckeditor#96]
i installed it on angular cli.
Its working but some event are warning like onChange, onReady,...
upload image from url is work perfectly.
I want upload image from local. Can u help me?

**Comment by xifengxx** [comment]
I also want to know it, upload image from local to serve, then return back to the url for using.

**Comment by kzimny** [comment]
there is no plugin for that in angular. you need to write some code to insert images or links to images from your server path. Try something like that:
`                        <ckbutton [name]="'imageExplorer'"
                          [command]="'openImageExplorer'"
                          (click)="openImageExplorer($event)"
                          [icon]="'./images/Icon.png'"
                          [label]="'Open image explorer'"
                          [toolbar]="'insert,1'">
                        </ckbutton>`

in your config:
`        this.ckeConfig = {
            height: 400,
            language: "en",
            allowedContent: true,
            toolbar: [
                { name: "clipboard", items: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo"] },
                { name: "links", items: ["Link", "Unlink", "Anchor"] },
                { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe", "imageExplorer"] }
            ]
        };
`
from your dialog window insert the link as follow:
`    onAddImage() {
        try
        {
            let link = this.ckeditor.instance.document.createElement("img");
            link.setAttribute("alt", "Image");
            link.setAttribute("src", "./Images/test.png");

            this.ckeditor.instance.insertElement(link);
        }
        catch(error)
        {
            console.log((<Error>error).message);
        }

        this.showFiles = false;
    }`

**Comment by chymz** [comment]
You need to use an external solution like CKFinder (https://cksource.com/ckfinder) our implement your own system (ckeditor plugin and a server to manage your files)

**Comment by amannguptaggg** [comment]
I can't understand anything where to write these code. I am using angular 8  and I want to upload images on my  blog website. can you please help me ???

**Comment by HungPrince** [comment]
> there is no plugin for that in angular. you need to write some code to insert images or links to images from your server path. Try something like that:
> 
> ```
> <ckbutton [name]="'imageExplorer'"
>  [command]="'openImageExplorer'"
>  (click)="openImageExplorer($event)"
>  [icon]="'./images/Icon.png'"
>  [label]="'Open image explorer'"
>  [toolbar]="'insert,1'">
> </ckbutton>
> ```
> 
> in your config:
> 
> ```js
> this.ckeConfig = {
>             height: 400,
>             language: "en",
>             allowedContent: true,
>             toolbar: [
>                 { name: "clipboard", items: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo"] },
>                 { name: "links", items: ["Link", "Unlink", "Anchor"] },
>                 { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe", "imageExplorer"] }
>             ]
>         };
> ```
> 
> from your dialog window insert the link as follow:
> 
> ```js
> onAddImage() {
>         try
>         {
>             let link = this.ckeditor.instance.document.createElement("img");
>             link.setAttribute("alt", "Image");
>             link.setAttribute("src", "./Images/test.png");
> 
>             this.ckeditor.instance.insertElement(link);
>         }
>         catch(error)
>         {
>             console.log((<Error>error).message);
>         }
> 
>         this.showFiles = false;
>     }
> ```



> there is no plugin for that in angular. you need to write some code to insert images or links to images from your server path. Try something like that:
> 
> ```
> <ckbutton [name]="'imageExplorer'"
>  [command]="'openImageExplorer'"
>  (click)="openImageExplorer($event)"
>  [icon]="'./images/Icon.png'"
>  [label]="'Open image explorer'"
>  [toolbar]="'insert,1'">
> </ckbutton>
> ```
> 
> in your config:
> 
> ```js
> this.ckeConfig = {
>             height: 400,
>             language: "en",
>             allowedContent: true,
>             toolbar: [
>                 { name: "clipboard", items: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "-", "Undo", "Redo"] },
>                 { name: "links", items: ["Link", "Unlink", "Anchor"] },
>                 { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe", "imageExplorer"] }
>             ]
>         };
> ```
> 
> from your dialog window insert the link as follow:
> 
> ```js
> onAddImage() {
>         try
>         {
>             let link = this.ckeditor.instance.document.createElement("img");
>             link.setAttribute("alt", "Image");
>             link.setAttribute("src", "./Images/test.png");
> 
>             this.ckeditor.instance.insertElement(link);
>         }
>         catch(error)
>         {
>             console.log((<Error>error).message);
>         }
> 
>         this.showFiles = false;
>     }
> ```

How can i add icon button? what is your icon path [icon]="'./images/Icon.png'" ? Where you put icon.png ?

**Comment by kzimny** [comment]
I did not found any other way. Look at my [solution](https://github.com/chymz/ng2-ckeditor/issues/279). Maybe someone else has a better solution?
