### ISSUE TITLE
How to remove  all "Paste" options?

### ISSUE THREAD

**Issue by milen4eto** [chymz/ng2-ckeditor#97]
Hello, I need your help.
Can someone tell me how to disable all "Paste" options from my ng2-ckeditor? I have to forbid Paste, Paste PlainText and etc? 
I tried this:
<ckeditor [config]="{ removePlugins: 'pastefromword, contextmenu', removeButtons: 'Paste, PasteText'}"></ckeditor>
but it's not working :(

**Comment by kzimny** [comment]
try to set the editor config in ngOnInit() method:
`    ngOnInit() {
        this.ckeConfig = {
            toolbar: [
                { name: "editing", items: ["Scayt", "Find", "Replace", "SelectAll"] },
                { name: "clipboard", items: ["Cut", "Copy", "Undo", "Redo"] },
                { name: "links", items: ["Link", "Unlink", "Anchor"] },
                { name: "insert", items: ["Image", "Table", "HorizontalRule", "SpecialChar", "Iframe"] },
                { name: "tools", items: ["Maximize", "ShowBlocks", "Preview", "Print", "Templates"] },
                { name: "document", items: ["Source"] },
                "/",
                { name: "basicstyles", items: ["Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat"] },
                { name: "paragraph", items: ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "CreateDiv", "-", "Blockquote"] },
                { name: "justify", items: ["JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock"] },
                { name: "styles", items: ["Styles", "Format", "FontSize", "-", "TextColor", "BGColor"] }
            ]
        };
    }`
