### ISSUE TITLE
[CKEDITOR] Error code: editor-destroy-iframe.

### ISSUE THREAD

**Issue by kjhatis** [chymz/ng2-ckeditor#99]
[CKEDITOR] For more information about this error go to http://docs.ckeditor.com/#!/guide/dev_errors-section-editor-destroy-iframe
(anonymous) @ ckeditor.js:21
m @ ckeditor.js:10
CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:12
CKEDITOR.warn @ ckeditor.js:19
detach @ ckeditor.js:850
CKEDITOR.editor.editable @ ckeditor.js:368
destroy @ ckeditor.js:253
(anonymous) @ CKEditor.es6:69
ZoneDelegate.invokeTask @ zone.js@0.6.25?main=browser:236
onInvokeTask @ core.umd.js:5966
ZoneDelegate.invokeTask @ zone.js@0.6.25?main=browser:235
Zone.runTask @ zone.js@0.6.25?main=browser:136
ZoneTask.invoke @ zone.js@0.6.25?main=browser:304

**Comment by kzimny** [comment]
look at this [thread](https://github.com/chymz/ng2-ckeditor/issues/24)
